// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Accessibility
    {
        /// <summary>
        /// Unique accessibility node identifier.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record AXNodeId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Enum of possible property types.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record AXValueType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly AXValueType BOOLEAN = new("boolean");
            public static readonly AXValueType TRISTATE = new("tristate");
            public static readonly AXValueType BOOLEAN_OR_UNDEFINED = new("booleanOrUndefined");
            public static readonly AXValueType IDREF = new("idref");
            public static readonly AXValueType IDREF_LIST = new("idrefList");
            public static readonly AXValueType INTEGER = new("integer");
            public static readonly AXValueType NODE = new("node");
            public static readonly AXValueType NODE_LIST = new("nodeList");
            public static readonly AXValueType NUMBER = new("number");
            public static readonly AXValueType STRING = new("string");
            public static readonly AXValueType COMPUTED_STRING = new("computedString");
            public static readonly AXValueType TOKEN = new("token");
            public static readonly AXValueType TOKEN_LIST = new("tokenList");
            public static readonly AXValueType DOM_RELATION = new("domRelation");
            public static readonly AXValueType ROLE = new("role");
            public static readonly AXValueType INTERNAL_ROLE = new("internalRole");
            public static readonly AXValueType VALUE_UNDEFINED = new("valueUndefined");
        }
        /// <summary>
        /// Enum of possible property sources.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record AXValueSourceType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly AXValueSourceType ATTRIBUTE = new("attribute");
            public static readonly AXValueSourceType IMPLICIT = new("implicit");
            public static readonly AXValueSourceType STYLE = new("style");
            public static readonly AXValueSourceType CONTENTS = new("contents");
            public static readonly AXValueSourceType PLACEHOLDER = new("placeholder");
            public static readonly AXValueSourceType RELATED_ELEMENT = new("relatedElement");
        }
        /// <summary>
        /// Enum of possible native property sources (as a subtype of a particular AXValueSourceType).
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record AXValueNativeSourceType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly AXValueNativeSourceType DESCRIPTION = new("description");
            public static readonly AXValueNativeSourceType FIGCAPTION = new("figcaption");
            public static readonly AXValueNativeSourceType LABEL = new("label");
            public static readonly AXValueNativeSourceType LABELFOR = new("labelfor");
            public static readonly AXValueNativeSourceType LABELWRAPPED = new("labelwrapped");
            public static readonly AXValueNativeSourceType LEGEND = new("legend");
            public static readonly AXValueNativeSourceType RUBYANNOTATION = new("rubyannotation");
            public static readonly AXValueNativeSourceType TABLECAPTION = new("tablecaption");
            public static readonly AXValueNativeSourceType TITLE = new("title");
            public static readonly AXValueNativeSourceType OTHER = new("other");
        }
        /// <summary>
        /// A single source for a computed AX property.
        /// </summary>
        /// <param name="Type">What type of source this is.</param>
        /// <param name="Value">The value of this property source.</param>
        /// <param name="Attribute">The name of the relevant attribute, if any.</param>
        /// <param name="AttributeValue">The value of the relevant attribute, if any.</param>
        /// <param name="Superseded">Whether this source is superseded by a higher priority source.</param>
        /// <param name="NativeSource">The native markup source for this value, e.g. a `&lt;label&gt;` element.</param>
        /// <param name="NativeSourceValue">The value, such as a node or node list, of the native source.</param>
        /// <param name="Invalid">Whether the value for this property is invalid.</param>
        /// <param name="InvalidReason">Reason for the value being invalid, if it is.</param>
        public record AXValueSource(
            Accessibility.AXValueSourceType Type,
            Accessibility.AXValue? Value = default,
            string? Attribute = default,
            Accessibility.AXValue? AttributeValue = default,
            bool? Superseded = default,
            Accessibility.AXValueNativeSourceType? NativeSource = default,
            Accessibility.AXValue? NativeSourceValue = default,
            bool? Invalid = default,
            string? InvalidReason = default
        ) : Core.IType
        {
        }
        /// <param name="BackendDOMNodeId">The BackendNodeId of the related DOM node.</param>
        /// <param name="Idref">The IDRef value provided, if any.</param>
        /// <param name="Text">The text alternative of this node in the current context.</param>
        public record AXRelatedNode(
            DOM.BackendNodeId BackendDOMNodeId,
            string? Idref = default,
            string? Text = default
        ) : Core.IType
        {
        }
        /// <param name="Name">The name of this property.</param>
        /// <param name="Value">The value of this property.</param>
        public record AXProperty(
            Accessibility.AXPropertyName Name,
            Accessibility.AXValue Value
        ) : Core.IType
        {
        }
        /// <summary>
        /// A single computed AX property.
        /// </summary>
        /// <param name="Type">The type of this value.</param>
        /// <param name="Value">The computed value of this property.</param>
        /// <param name="RelatedNodes">One or more related nodes, if applicable.</param>
        /// <param name="Sources">The sources which contributed to the computation of this property.</param>
        public record AXValue(
            Accessibility.AXValueType Type,
            JsonNode? Value = default,
            IReadOnlyList<Accessibility.AXRelatedNode>? RelatedNodes = default,
            IReadOnlyList<Accessibility.AXValueSource>? Sources = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Values of AXProperty name:<br/>
        /// - from &apos;busy&apos; to &apos;roledescription&apos;: states which apply to every AX node<br/>
        /// - from &apos;live&apos; to &apos;root&apos;: attributes which apply to nodes in live regions<br/>
        /// - from &apos;autocomplete&apos; to &apos;valuetext&apos;: attributes which apply to widgets<br/>
        /// - from &apos;checked&apos; to &apos;selected&apos;: states which apply to widgets<br/>
        /// - from &apos;activedescendant&apos; to &apos;owns&apos;: relationships between elements other than parent/child/sibling<br/>
        /// - from &apos;activeFullscreenElement&apos; to &apos;uninteresting&apos;: reasons why this noode is hidden
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record AXPropertyName(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly AXPropertyName ACTIONS = new("actions");
            public static readonly AXPropertyName BUSY = new("busy");
            public static readonly AXPropertyName DISABLED = new("disabled");
            public static readonly AXPropertyName EDITABLE = new("editable");
            public static readonly AXPropertyName FOCUSABLE = new("focusable");
            public static readonly AXPropertyName FOCUSED = new("focused");
            public static readonly AXPropertyName HIDDEN = new("hidden");
            public static readonly AXPropertyName HIDDEN_ROOT = new("hiddenRoot");
            public static readonly AXPropertyName INVALID = new("invalid");
            public static readonly AXPropertyName KEYSHORTCUTS = new("keyshortcuts");
            public static readonly AXPropertyName SETTABLE = new("settable");
            public static readonly AXPropertyName ROLEDESCRIPTION = new("roledescription");
            public static readonly AXPropertyName LIVE = new("live");
            public static readonly AXPropertyName ATOMIC = new("atomic");
            public static readonly AXPropertyName RELEVANT = new("relevant");
            public static readonly AXPropertyName ROOT = new("root");
            public static readonly AXPropertyName AUTOCOMPLETE = new("autocomplete");
            public static readonly AXPropertyName HAS_POPUP = new("hasPopup");
            public static readonly AXPropertyName LEVEL = new("level");
            public static readonly AXPropertyName MULTISELECTABLE = new("multiselectable");
            public static readonly AXPropertyName ORIENTATION = new("orientation");
            public static readonly AXPropertyName MULTILINE = new("multiline");
            public static readonly AXPropertyName READONLY = new("readonly");
            public static readonly AXPropertyName REQUIRED = new("required");
            public static readonly AXPropertyName VALUEMIN = new("valuemin");
            public static readonly AXPropertyName VALUEMAX = new("valuemax");
            public static readonly AXPropertyName VALUETEXT = new("valuetext");
            public static readonly AXPropertyName CHECKED = new("checked");
            public static readonly AXPropertyName EXPANDED = new("expanded");
            public static readonly AXPropertyName MODAL = new("modal");
            public static readonly AXPropertyName PRESSED = new("pressed");
            public static readonly AXPropertyName SELECTED = new("selected");
            public static readonly AXPropertyName ACTIVEDESCENDANT = new("activedescendant");
            public static readonly AXPropertyName CONTROLS = new("controls");
            public static readonly AXPropertyName DESCRIBEDBY = new("describedby");
            public static readonly AXPropertyName DETAILS = new("details");
            public static readonly AXPropertyName ERRORMESSAGE = new("errormessage");
            public static readonly AXPropertyName FLOWTO = new("flowto");
            public static readonly AXPropertyName LABELLEDBY = new("labelledby");
            public static readonly AXPropertyName OWNS = new("owns");
            public static readonly AXPropertyName URL = new("url");
            public static readonly AXPropertyName ACTIVE_FULLSCREEN_ELEMENT = new("activeFullscreenElement");
            public static readonly AXPropertyName ACTIVE_MODAL_DIALOG = new("activeModalDialog");
            public static readonly AXPropertyName ACTIVE_ARIA_MODAL_DIALOG = new("activeAriaModalDialog");
            public static readonly AXPropertyName ARIA_HIDDEN_ELEMENT = new("ariaHiddenElement");
            public static readonly AXPropertyName ARIA_HIDDEN_SUBTREE = new("ariaHiddenSubtree");
            public static readonly AXPropertyName EMPTY_ALT = new("emptyAlt");
            public static readonly AXPropertyName EMPTY_TEXT = new("emptyText");
            public static readonly AXPropertyName INERT_ELEMENT = new("inertElement");
            public static readonly AXPropertyName INERT_SUBTREE = new("inertSubtree");
            public static readonly AXPropertyName LABEL_CONTAINER = new("labelContainer");
            public static readonly AXPropertyName LABEL_FOR = new("labelFor");
            public static readonly AXPropertyName NOT_RENDERED = new("notRendered");
            public static readonly AXPropertyName NOT_VISIBLE = new("notVisible");
            public static readonly AXPropertyName PRESENTATIONAL_ROLE = new("presentationalRole");
            public static readonly AXPropertyName PROBABLY_PRESENTATIONAL = new("probablyPresentational");
            public static readonly AXPropertyName INACTIVE_CAROUSEL_TAB_CONTENT = new("inactiveCarouselTabContent");
            public static readonly AXPropertyName UNINTERESTING = new("uninteresting");
        }
        /// <summary>
        /// A node in the accessibility tree.
        /// </summary>
        /// <param name="NodeId">Unique identifier for this node.</param>
        /// <param name="Ignored">Whether this node is ignored for accessibility</param>
        /// <param name="IgnoredReasons">Collection of reasons why this node is hidden.</param>
        /// <param name="Role">This `Node`&apos;s role, whether explicit or implicit.</param>
        /// <param name="ChromeRole">This `Node`&apos;s Chrome raw role.</param>
        /// <param name="Name">The accessible name for this `Node`.</param>
        /// <param name="Description">The accessible description for this `Node`.</param>
        /// <param name="Value">The value for this `Node`.</param>
        /// <param name="Properties">All other properties</param>
        /// <param name="ParentId">ID for this node&apos;s parent.</param>
        /// <param name="ChildIds">IDs for each of this node&apos;s child nodes.</param>
        /// <param name="BackendDOMNodeId">The backend ID for the associated DOM node, if any.</param>
        /// <param name="FrameId">The frame ID for the frame associated with this nodes document.</param>
        public record AXNode(
            Accessibility.AXNodeId NodeId,
            bool Ignored,
            IReadOnlyList<Accessibility.AXProperty>? IgnoredReasons = default,
            Accessibility.AXValue? Role = default,
            Accessibility.AXValue? ChromeRole = default,
            Accessibility.AXValue? Name = default,
            Accessibility.AXValue? Description = default,
            Accessibility.AXValue? Value = default,
            IReadOnlyList<Accessibility.AXProperty>? Properties = default,
            Accessibility.AXNodeId? ParentId = default,
            IReadOnlyList<Accessibility.AXNodeId>? ChildIds = default,
            DOM.BackendNodeId? BackendDOMNodeId = default,
            Page.FrameId? FrameId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Disables the accessibility domain.
        /// </summary>
        public static Accessibility.DisableRequest Disable()
        {
            return new Accessibility.DisableRequest();
        }
        /// <summary>
        /// Disables the accessibility domain.
        /// </summary>
        [Core.MethodName("Accessibility.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Disables the accessibility domain.
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.<br/>
        /// This turns on accessibility for the page, which can impact performance until accessibility is disabled.
        /// </summary>
        public static Accessibility.EnableRequest Enable()
        {
            return new Accessibility.EnableRequest();
        }
        /// <summary>
        /// Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.<br/>
        /// This turns on accessibility for the page, which can impact performance until accessibility is disabled.
        /// </summary>
        [Core.MethodName("Accessibility.enable")]
        public record EnableRequest() : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.<br/>
        /// This turns on accessibility for the page, which can impact performance until accessibility is disabled.
        /// </summary>
        public record EnableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to get the partial accessibility tree for.</param>
        /// <param name="BackendNodeId">Identifier of the backend node to get the partial accessibility tree for.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper to get the partial accessibility tree for.</param>
        /// <param name="FetchRelatives">Whether to fetch this node&apos;s ancestors, siblings and children. Defaults to true.</param>
        public static Accessibility.GetPartialAXTreeRequest GetPartialAXTree(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default, bool? FetchRelatives = default)
        {
            return new Accessibility.GetPartialAXTreeRequest(NodeId, BackendNodeId, ObjectId, FetchRelatives);
        }
        /// <summary>
        /// Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to get the partial accessibility tree for.</param>
        /// <param name="BackendNodeId">Identifier of the backend node to get the partial accessibility tree for.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper to get the partial accessibility tree for.</param>
        /// <param name="FetchRelatives">Whether to fetch this node&apos;s ancestors, siblings and children. Defaults to true.</param>
        [Core.MethodName("Accessibility.getPartialAXTree")]
        public record GetPartialAXTreeRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default,
            bool? FetchRelatives = default
        ) : Core.ICommand<GetPartialAXTreeRequestResult>
        {
        }
        /// <summary>
        /// Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
        /// </summary>
        /// <param name="Nodes">The `Accessibility.AXNode` for this DOM node, if it exists, plus its ancestors, siblings and<br/>
        /// children, if requested.</param>
        public record GetPartialAXTreeRequestResult(
            IReadOnlyList<Accessibility.AXNode> Nodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Fetches the entire accessibility tree for the root Document
        /// </summary>
        /// <param name="Depth">The maximum depth at which descendants of the root node should be retrieved.<br/>
        /// If omitted, the full tree is returned.</param>
        /// <param name="FrameId">The frame for whose document the AX tree should be retrieved.<br/>
        /// If omitted, the root frame is used.</param>
        public static Accessibility.GetFullAXTreeRequest GetFullAXTree(int? Depth = default, Page.FrameId? FrameId = default)
        {
            return new Accessibility.GetFullAXTreeRequest(Depth, FrameId);
        }
        /// <summary>
        /// Fetches the entire accessibility tree for the root Document
        /// </summary>
        /// <param name="Depth">The maximum depth at which descendants of the root node should be retrieved.<br/>
        /// If omitted, the full tree is returned.</param>
        /// <param name="FrameId">The frame for whose document the AX tree should be retrieved.<br/>
        /// If omitted, the root frame is used.</param>
        [Core.MethodName("Accessibility.getFullAXTree")]
        public record GetFullAXTreeRequest(
            int? Depth = default,
            Page.FrameId? FrameId = default
        ) : Core.ICommand<GetFullAXTreeRequestResult>
        {
        }
        /// <summary>
        /// Fetches the entire accessibility tree for the root Document
        /// </summary>
        public record GetFullAXTreeRequestResult(
            IReadOnlyList<Accessibility.AXNode> Nodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Fetches the root node.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        /// <param name="FrameId">The frame in whose document the node resides.<br/>
        /// If omitted, the root frame is used.</param>
        public static Accessibility.GetRootAXNodeRequest GetRootAXNode(Page.FrameId? FrameId = default)
        {
            return new Accessibility.GetRootAXNodeRequest(FrameId);
        }
        /// <summary>
        /// Fetches the root node.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        /// <param name="FrameId">The frame in whose document the node resides.<br/>
        /// If omitted, the root frame is used.</param>
        [Core.MethodName("Accessibility.getRootAXNode")]
        public record GetRootAXNodeRequest(
            Page.FrameId? FrameId = default
        ) : Core.ICommand<GetRootAXNodeRequestResult>
        {
        }
        /// <summary>
        /// Fetches the root node.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        public record GetRootAXNodeRequestResult(
            Accessibility.AXNode Node
        ) : Core.IType
        {
        }
        /// <summary>
        /// Fetches a node and all ancestors up to and including the root.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to get.</param>
        /// <param name="BackendNodeId">Identifier of the backend node to get.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper to get.</param>
        public static Accessibility.GetAXNodeAndAncestorsRequest GetAXNodeAndAncestors(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default)
        {
            return new Accessibility.GetAXNodeAndAncestorsRequest(NodeId, BackendNodeId, ObjectId);
        }
        /// <summary>
        /// Fetches a node and all ancestors up to and including the root.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to get.</param>
        /// <param name="BackendNodeId">Identifier of the backend node to get.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper to get.</param>
        [Core.MethodName("Accessibility.getAXNodeAndAncestors")]
        public record GetAXNodeAndAncestorsRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default
        ) : Core.ICommand<GetAXNodeAndAncestorsRequestResult>
        {
        }
        /// <summary>
        /// Fetches a node and all ancestors up to and including the root.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        public record GetAXNodeAndAncestorsRequestResult(
            IReadOnlyList<Accessibility.AXNode> Nodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Fetches a particular accessibility node by AXNodeId.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        /// <param name="FrameId">The frame in whose document the node resides.<br/>
        /// If omitted, the root frame is used.</param>
        public static Accessibility.GetChildAXNodesRequest GetChildAXNodes(Accessibility.AXNodeId Id, Page.FrameId? FrameId = default)
        {
            return new Accessibility.GetChildAXNodesRequest(Id, FrameId);
        }
        /// <summary>
        /// Fetches a particular accessibility node by AXNodeId.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        /// <param name="FrameId">The frame in whose document the node resides.<br/>
        /// If omitted, the root frame is used.</param>
        [Core.MethodName("Accessibility.getChildAXNodes")]
        public record GetChildAXNodesRequest(
            Accessibility.AXNodeId Id,
            Page.FrameId? FrameId = default
        ) : Core.ICommand<GetChildAXNodesRequestResult>
        {
        }
        /// <summary>
        /// Fetches a particular accessibility node by AXNodeId.<br/>
        /// Requires `enable()` to have been called previously.
        /// </summary>
        public record GetChildAXNodesRequestResult(
            IReadOnlyList<Accessibility.AXNode> Nodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Query a DOM node&apos;s accessibility subtree for accessible name and role.<br/>
        /// This command computes the name and role for all nodes in the subtree, including those that are<br/>
        /// ignored for accessibility, and returns those that match the specified name and role. If no DOM<br/>
        /// node is specified, or the DOM node does not exist, the command returns an error. If neither<br/>
        /// `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
        /// </summary>
        /// <param name="NodeId">Identifier of the node for the root to query.</param>
        /// <param name="BackendNodeId">Identifier of the backend node for the root to query.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper for the root to query.</param>
        /// <param name="AccessibleName">Find nodes with this computed name.</param>
        /// <param name="Role">Find nodes with this computed role.</param>
        public static Accessibility.QueryAXTreeRequest QueryAXTree(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default, string? AccessibleName = default, string? Role = default)
        {
            return new Accessibility.QueryAXTreeRequest(NodeId, BackendNodeId, ObjectId, AccessibleName, Role);
        }
        /// <summary>
        /// Query a DOM node&apos;s accessibility subtree for accessible name and role.<br/>
        /// This command computes the name and role for all nodes in the subtree, including those that are<br/>
        /// ignored for accessibility, and returns those that match the specified name and role. If no DOM<br/>
        /// node is specified, or the DOM node does not exist, the command returns an error. If neither<br/>
        /// `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
        /// </summary>
        /// <param name="NodeId">Identifier of the node for the root to query.</param>
        /// <param name="BackendNodeId">Identifier of the backend node for the root to query.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper for the root to query.</param>
        /// <param name="AccessibleName">Find nodes with this computed name.</param>
        /// <param name="Role">Find nodes with this computed role.</param>
        [Core.MethodName("Accessibility.queryAXTree")]
        public record QueryAXTreeRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default,
            string? AccessibleName = default,
            string? Role = default
        ) : Core.ICommand<QueryAXTreeRequestResult>
        {
        }
        /// <summary>
        /// Query a DOM node&apos;s accessibility subtree for accessible name and role.<br/>
        /// This command computes the name and role for all nodes in the subtree, including those that are<br/>
        /// ignored for accessibility, and returns those that match the specified name and role. If no DOM<br/>
        /// node is specified, or the DOM node does not exist, the command returns an error. If neither<br/>
        /// `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
        /// </summary>
        /// <param name="Nodes">A list of `Accessibility.AXNode` matching the specified attributes,<br/>
        /// including nodes that are ignored for accessibility.</param>
        public record QueryAXTreeRequestResult(
            IReadOnlyList<Accessibility.AXNode> Nodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// The loadComplete event mirrors the load complete event sent by the browser to assistive<br/>
        /// technology when the web page has finished loading.
        /// </summary>
        /// <param name="Root">New document root node.</param>
        [Core.MethodName("Accessibility.loadComplete")]
        public record LoadComplete(
            Accessibility.AXNode Root
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// The nodesUpdated event is sent every time a previously requested node has changed the in tree.
        /// </summary>
        /// <param name="Nodes">Updated node data.</param>
        [Core.MethodName("Accessibility.nodesUpdated")]
        public record NodesUpdated(
            IReadOnlyList<Accessibility.AXNode> Nodes
        ) : Core.IEvent
        {
        }
    }
}
