// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Animation
    {
        /// <summary>
        /// Animation instance.
        /// </summary>
        /// <param name="Id">`Animation`&apos;s id.</param>
        /// <param name="Name">`Animation`&apos;s name.</param>
        /// <param name="PausedState">`Animation`&apos;s internal paused state.</param>
        /// <param name="PlayState">`Animation`&apos;s play state.</param>
        /// <param name="PlaybackRate">`Animation`&apos;s playback rate.</param>
        /// <param name="StartTime">`Animation`&apos;s start time.<br/>
        /// Milliseconds for time based animations and<br/>
        /// percentage [0 - 100] for scroll driven animations<br/>
        /// (i.e. when viewOrScrollTimeline exists).</param>
        /// <param name="CurrentTime">`Animation`&apos;s current time.</param>
        /// <param name="Type">Animation type of `Animation`.</param>
        /// <param name="Source">`Animation`&apos;s source animation node.</param>
        /// <param name="CssId">A unique ID for `Animation` representing the sources that triggered this CSS<br/>
        /// animation/transition.</param>
        /// <param name="ViewOrScrollTimeline">View or scroll timeline</param>
        public record AnimationType(
            string Id,
            string Name,
            bool PausedState,
            string PlayState,
            double PlaybackRate,
            double StartTime,
            double CurrentTime,
            string Type,
            Animation.AnimationEffect? Source = default,
            string? CssId = default,
            Animation.ViewOrScrollTimeline? ViewOrScrollTimeline = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Timeline instance
        /// </summary>
        /// <param name="Axis">Orientation of the scroll</param>
        /// <param name="SourceNodeId">Scroll container node</param>
        /// <param name="StartOffset">Represents the starting scroll position of the timeline<br/>
        /// as a length offset in pixels from scroll origin.</param>
        /// <param name="EndOffset">Represents the ending scroll position of the timeline<br/>
        /// as a length offset in pixels from scroll origin.</param>
        /// <param name="SubjectNodeId">The element whose principal box&apos;s visibility in the<br/>
        /// scrollport defined the progress of the timeline.<br/>
        /// Does not exist for animations with ScrollTimeline</param>
        public record ViewOrScrollTimeline(
            DOM.ScrollOrientation Axis,
            DOM.BackendNodeId? SourceNodeId = default,
            double? StartOffset = default,
            double? EndOffset = default,
            DOM.BackendNodeId? SubjectNodeId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// AnimationEffect instance
        /// </summary>
        /// <param name="Delay">`AnimationEffect`&apos;s delay.</param>
        /// <param name="EndDelay">`AnimationEffect`&apos;s end delay.</param>
        /// <param name="IterationStart">`AnimationEffect`&apos;s iteration start.</param>
        /// <param name="Duration">`AnimationEffect`&apos;s iteration duration.<br/>
        /// Milliseconds for time based animations and<br/>
        /// percentage [0 - 100] for scroll driven animations<br/>
        /// (i.e. when viewOrScrollTimeline exists).</param>
        /// <param name="Direction">`AnimationEffect`&apos;s playback direction.</param>
        /// <param name="Fill">`AnimationEffect`&apos;s fill mode.</param>
        /// <param name="Easing">`AnimationEffect`&apos;s timing function.</param>
        /// <param name="Iterations">`AnimationEffect`&apos;s iterations. Omitted if the value is infinite.</param>
        /// <param name="BackendNodeId">`AnimationEffect`&apos;s target node.</param>
        /// <param name="KeyframesRule">`AnimationEffect`&apos;s keyframes.</param>
        public record AnimationEffect(
            double Delay,
            double EndDelay,
            double IterationStart,
            double Duration,
            string Direction,
            string Fill,
            string Easing,
            double? Iterations = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Animation.KeyframesRule? KeyframesRule = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Keyframes Rule
        /// </summary>
        /// <param name="Keyframes">List of animation keyframes.</param>
        /// <param name="Name">CSS keyframed animation&apos;s name.</param>
        public record KeyframesRule(
            IReadOnlyList<Animation.KeyframeStyle> Keyframes,
            string? Name = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Keyframe Style
        /// </summary>
        /// <param name="Offset">Keyframe&apos;s time offset.</param>
        /// <param name="Easing">`AnimationEffect`&apos;s timing function.</param>
        public record KeyframeStyle(
            string Offset,
            string Easing
        ) : Core.IType
        {
        }
        /// <summary>
        /// Disables animation domain notifications.
        /// </summary>
        public static Animation.DisableRequest Disable()
        {
            return new Animation.DisableRequest();
        }
        /// <summary>
        /// Disables animation domain notifications.
        /// </summary>
        [Core.MethodName("Animation.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Disables animation domain notifications.
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables animation domain notifications.
        /// </summary>
        public static Animation.EnableRequest Enable()
        {
            return new Animation.EnableRequest();
        }
        /// <summary>
        /// Enables animation domain notifications.
        /// </summary>
        [Core.MethodName("Animation.enable")]
        public record EnableRequest() : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables animation domain notifications.
        /// </summary>
        public record EnableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Returns the current time of the an animation.
        /// </summary>
        /// <param name="Id">Id of animation.</param>
        public static Animation.GetCurrentTimeRequest GetCurrentTime(string Id)
        {
            return new Animation.GetCurrentTimeRequest(Id);
        }
        /// <summary>
        /// Returns the current time of the an animation.
        /// </summary>
        /// <param name="Id">Id of animation.</param>
        [Core.MethodName("Animation.getCurrentTime")]
        public record GetCurrentTimeRequest(
            string Id
        ) : Core.ICommand<GetCurrentTimeRequestResult>
        {
        }
        /// <summary>
        /// Returns the current time of the an animation.
        /// </summary>
        /// <param name="CurrentTime">Current time of the page.</param>
        public record GetCurrentTimeRequestResult(
            double CurrentTime
        ) : Core.IType
        {
        }
        /// <summary>
        /// Gets the playback rate of the document timeline.
        /// </summary>
        public static Animation.GetPlaybackRateRequest GetPlaybackRate()
        {
            return new Animation.GetPlaybackRateRequest();
        }
        /// <summary>
        /// Gets the playback rate of the document timeline.
        /// </summary>
        [Core.MethodName("Animation.getPlaybackRate")]
        public record GetPlaybackRateRequest() : Core.ICommand<GetPlaybackRateRequestResult>
        {
        }
        /// <summary>
        /// Gets the playback rate of the document timeline.
        /// </summary>
        /// <param name="PlaybackRate">Playback rate for animations on page.</param>
        public record GetPlaybackRateRequestResult(
            double PlaybackRate
        ) : Core.IType
        {
        }
        /// <summary>
        /// Releases a set of animations to no longer be manipulated.
        /// </summary>
        /// <param name="Animations">List of animation ids to seek.</param>
        public static Animation.ReleaseAnimationsRequest ReleaseAnimations(IReadOnlyList<string> Animations)
        {
            return new Animation.ReleaseAnimationsRequest(Animations);
        }
        /// <summary>
        /// Releases a set of animations to no longer be manipulated.
        /// </summary>
        /// <param name="Animations">List of animation ids to seek.</param>
        [Core.MethodName("Animation.releaseAnimations")]
        public record ReleaseAnimationsRequest(
            IReadOnlyList<string> Animations
        ) : Core.ICommand<ReleaseAnimationsRequestResult>
        {
        }
        /// <summary>
        /// Releases a set of animations to no longer be manipulated.
        /// </summary>
        public record ReleaseAnimationsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Gets the remote object of the Animation.
        /// </summary>
        /// <param name="AnimationId">Animation id.</param>
        public static Animation.ResolveAnimationRequest ResolveAnimation(string AnimationId)
        {
            return new Animation.ResolveAnimationRequest(AnimationId);
        }
        /// <summary>
        /// Gets the remote object of the Animation.
        /// </summary>
        /// <param name="AnimationId">Animation id.</param>
        [Core.MethodName("Animation.resolveAnimation")]
        public record ResolveAnimationRequest(
            string AnimationId
        ) : Core.ICommand<ResolveAnimationRequestResult>
        {
        }
        /// <summary>
        /// Gets the remote object of the Animation.
        /// </summary>
        /// <param name="RemoteObject">Corresponding remote object.</param>
        public record ResolveAnimationRequestResult(
            Runtime.RemoteObject RemoteObject
        ) : Core.IType
        {
        }
        /// <summary>
        /// Seek a set of animations to a particular time within each animation.
        /// </summary>
        /// <param name="Animations">List of animation ids to seek.</param>
        /// <param name="CurrentTime">Set the current time of each animation.</param>
        public static Animation.SeekAnimationsRequest SeekAnimations(IReadOnlyList<string> Animations, double CurrentTime)
        {
            return new Animation.SeekAnimationsRequest(Animations, CurrentTime);
        }
        /// <summary>
        /// Seek a set of animations to a particular time within each animation.
        /// </summary>
        /// <param name="Animations">List of animation ids to seek.</param>
        /// <param name="CurrentTime">Set the current time of each animation.</param>
        [Core.MethodName("Animation.seekAnimations")]
        public record SeekAnimationsRequest(
            IReadOnlyList<string> Animations,
            double CurrentTime
        ) : Core.ICommand<SeekAnimationsRequestResult>
        {
        }
        /// <summary>
        /// Seek a set of animations to a particular time within each animation.
        /// </summary>
        public record SeekAnimationsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets the paused state of a set of animations.
        /// </summary>
        /// <param name="Animations">Animations to set the pause state of.</param>
        /// <param name="Paused">Paused state to set to.</param>
        public static Animation.SetPausedRequest SetPaused(IReadOnlyList<string> Animations, bool Paused)
        {
            return new Animation.SetPausedRequest(Animations, Paused);
        }
        /// <summary>
        /// Sets the paused state of a set of animations.
        /// </summary>
        /// <param name="Animations">Animations to set the pause state of.</param>
        /// <param name="Paused">Paused state to set to.</param>
        [Core.MethodName("Animation.setPaused")]
        public record SetPausedRequest(
            IReadOnlyList<string> Animations,
            bool Paused
        ) : Core.ICommand<SetPausedRequestResult>
        {
        }
        /// <summary>
        /// Sets the paused state of a set of animations.
        /// </summary>
        public record SetPausedRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets the playback rate of the document timeline.
        /// </summary>
        /// <param name="PlaybackRate">Playback rate for animations on page</param>
        public static Animation.SetPlaybackRateRequest SetPlaybackRate(double PlaybackRate)
        {
            return new Animation.SetPlaybackRateRequest(PlaybackRate);
        }
        /// <summary>
        /// Sets the playback rate of the document timeline.
        /// </summary>
        /// <param name="PlaybackRate">Playback rate for animations on page</param>
        [Core.MethodName("Animation.setPlaybackRate")]
        public record SetPlaybackRateRequest(
            double PlaybackRate
        ) : Core.ICommand<SetPlaybackRateRequestResult>
        {
        }
        /// <summary>
        /// Sets the playback rate of the document timeline.
        /// </summary>
        public record SetPlaybackRateRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets the timing of an animation node.
        /// </summary>
        /// <param name="AnimationId">Animation id.</param>
        /// <param name="Duration">Duration of the animation.</param>
        /// <param name="Delay">Delay of the animation.</param>
        public static Animation.SetTimingRequest SetTiming(string AnimationId, double Duration, double Delay)
        {
            return new Animation.SetTimingRequest(AnimationId, Duration, Delay);
        }
        /// <summary>
        /// Sets the timing of an animation node.
        /// </summary>
        /// <param name="AnimationId">Animation id.</param>
        /// <param name="Duration">Duration of the animation.</param>
        /// <param name="Delay">Delay of the animation.</param>
        [Core.MethodName("Animation.setTiming")]
        public record SetTimingRequest(
            string AnimationId,
            double Duration,
            double Delay
        ) : Core.ICommand<SetTimingRequestResult>
        {
        }
        /// <summary>
        /// Sets the timing of an animation node.
        /// </summary>
        public record SetTimingRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Event for when an animation has been cancelled.
        /// </summary>
        /// <param name="Id">Id of the animation that was cancelled.</param>
        [Core.MethodName("Animation.animationCanceled")]
        public record AnimationCanceled(
            string Id
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Event for each animation that has been created.
        /// </summary>
        /// <param name="Id">Id of the animation that was created.</param>
        [Core.MethodName("Animation.animationCreated")]
        public record AnimationCreated(
            string Id
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Event for animation that has been started.
        /// </summary>
        /// <param name="Animation">Animation that was started.</param>
        [Core.MethodName("Animation.animationStarted")]
        public record AnimationStarted(
            Animation.AnimationType Animation
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Event for animation that has been updated.
        /// </summary>
        /// <param name="Animation">Animation that was updated.</param>
        [Core.MethodName("Animation.animationUpdated")]
        public record AnimationUpdated(
            Animation.AnimationType Animation
        ) : Core.IEvent
        {
        }
    }
}
