// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class CacheStorage
    {
        /// <summary>
        /// Unique identifier of the Cache object.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record CacheId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// type of HTTP response cached
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record CachedResponseType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly CachedResponseType BASIC = new("basic");
            public static readonly CachedResponseType CORS = new("cors");
            public static readonly CachedResponseType DEFAULT = new("default");
            public static readonly CachedResponseType ERROR = new("error");
            public static readonly CachedResponseType OPAQUE_RESPONSE = new("opaqueResponse");
            public static readonly CachedResponseType OPAQUE_REDIRECT = new("opaqueRedirect");
        }
        /// <summary>
        /// Data entry.
        /// </summary>
        /// <param name="RequestURL">Request URL.</param>
        /// <param name="RequestMethod">Request method.</param>
        /// <param name="RequestHeaders">Request headers</param>
        /// <param name="ResponseTime">Number of seconds since epoch.</param>
        /// <param name="ResponseStatus">HTTP response status code.</param>
        /// <param name="ResponseStatusText">HTTP response status text.</param>
        /// <param name="ResponseType">HTTP response type</param>
        /// <param name="ResponseHeaders">Response headers</param>
        public record DataEntry(
            string RequestURL,
            string RequestMethod,
            IReadOnlyList<CacheStorage.Header> RequestHeaders,
            double ResponseTime,
            int ResponseStatus,
            string ResponseStatusText,
            CacheStorage.CachedResponseType ResponseType,
            IReadOnlyList<CacheStorage.Header> ResponseHeaders
        ) : Core.IType
        {
        }
        /// <summary>
        /// Cache identifier.
        /// </summary>
        /// <param name="CacheId">An opaque unique id of the cache.</param>
        /// <param name="SecurityOrigin">Security origin of the cache.</param>
        /// <param name="StorageKey">Storage key of the cache.</param>
        /// <param name="CacheName">The name of the cache.</param>
        /// <param name="StorageBucket">Storage bucket of the cache.</param>
        public record Cache(
            CacheStorage.CacheId CacheId,
            string SecurityOrigin,
            string StorageKey,
            string CacheName,
            Storage.StorageBucket? StorageBucket = default
        ) : Core.IType
        {
        }
        public record Header(
            string Name,
            string Value
        ) : Core.IType
        {
        }
        /// <summary>
        /// Cached response
        /// </summary>
        /// <param name="Body">Entry content, base64-encoded. (Encoded as a base64 string when passed over JSON)</param>
        public record CachedResponse(
            string Body
        ) : Core.IType
        {
        }
        /// <summary>
        /// Deletes a cache.
        /// </summary>
        /// <param name="CacheId">Id of cache for deletion.</param>
        public static CacheStorage.DeleteCacheRequest DeleteCache(CacheStorage.CacheId CacheId)
        {
            return new CacheStorage.DeleteCacheRequest(CacheId);
        }
        /// <summary>
        /// Deletes a cache.
        /// </summary>
        /// <param name="CacheId">Id of cache for deletion.</param>
        [Core.MethodName("CacheStorage.deleteCache")]
        public record DeleteCacheRequest(
            CacheStorage.CacheId CacheId
        ) : Core.ICommand<DeleteCacheRequestResult>
        {
        }
        /// <summary>
        /// Deletes a cache.
        /// </summary>
        public record DeleteCacheRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Deletes a cache entry.
        /// </summary>
        /// <param name="CacheId">Id of cache where the entry will be deleted.</param>
        /// <param name="Request">URL spec of the request.</param>
        public static CacheStorage.DeleteEntryRequest DeleteEntry(CacheStorage.CacheId CacheId, string Request)
        {
            return new CacheStorage.DeleteEntryRequest(CacheId, Request);
        }
        /// <summary>
        /// Deletes a cache entry.
        /// </summary>
        /// <param name="CacheId">Id of cache where the entry will be deleted.</param>
        /// <param name="Request">URL spec of the request.</param>
        [Core.MethodName("CacheStorage.deleteEntry")]
        public record DeleteEntryRequest(
            CacheStorage.CacheId CacheId,
            string Request
        ) : Core.ICommand<DeleteEntryRequestResult>
        {
        }
        /// <summary>
        /// Deletes a cache entry.
        /// </summary>
        public record DeleteEntryRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Requests cache names.
        /// </summary>
        /// <param name="SecurityOrigin">At least and at most one of securityOrigin, storageKey, storageBucket must be specified.<br/>
        /// Security origin.</param>
        /// <param name="StorageKey">Storage key.</param>
        /// <param name="StorageBucket">Storage bucket. If not specified, it uses the default bucket.</param>
        public static CacheStorage.RequestCacheNamesRequest RequestCacheNames(string? SecurityOrigin = default, string? StorageKey = default, Storage.StorageBucket? StorageBucket = default)
        {
            return new CacheStorage.RequestCacheNamesRequest(SecurityOrigin, StorageKey, StorageBucket);
        }
        /// <summary>
        /// Requests cache names.
        /// </summary>
        /// <param name="SecurityOrigin">At least and at most one of securityOrigin, storageKey, storageBucket must be specified.<br/>
        /// Security origin.</param>
        /// <param name="StorageKey">Storage key.</param>
        /// <param name="StorageBucket">Storage bucket. If not specified, it uses the default bucket.</param>
        [Core.MethodName("CacheStorage.requestCacheNames")]
        public record RequestCacheNamesRequest(
            string? SecurityOrigin = default,
            string? StorageKey = default,
            Storage.StorageBucket? StorageBucket = default
        ) : Core.ICommand<RequestCacheNamesRequestResult>
        {
        }
        /// <summary>
        /// Requests cache names.
        /// </summary>
        /// <param name="Caches">Caches for the security origin.</param>
        public record RequestCacheNamesRequestResult(
            IReadOnlyList<CacheStorage.Cache> Caches
        ) : Core.IType
        {
        }
        /// <summary>
        /// Fetches cache entry.
        /// </summary>
        /// <param name="CacheId">Id of cache that contains the entry.</param>
        /// <param name="RequestURL">URL spec of the request.</param>
        /// <param name="RequestHeaders">headers of the request.</param>
        public static CacheStorage.RequestCachedResponseRequest RequestCachedResponse(CacheStorage.CacheId CacheId, string RequestURL, IReadOnlyList<CacheStorage.Header> RequestHeaders)
        {
            return new CacheStorage.RequestCachedResponseRequest(CacheId, RequestURL, RequestHeaders);
        }
        /// <summary>
        /// Fetches cache entry.
        /// </summary>
        /// <param name="CacheId">Id of cache that contains the entry.</param>
        /// <param name="RequestURL">URL spec of the request.</param>
        /// <param name="RequestHeaders">headers of the request.</param>
        [Core.MethodName("CacheStorage.requestCachedResponse")]
        public record RequestCachedResponseRequest(
            CacheStorage.CacheId CacheId,
            string RequestURL,
            IReadOnlyList<CacheStorage.Header> RequestHeaders
        ) : Core.ICommand<RequestCachedResponseRequestResult>
        {
        }
        /// <summary>
        /// Fetches cache entry.
        /// </summary>
        /// <param name="Response">Response read from the cache.</param>
        public record RequestCachedResponseRequestResult(
            CacheStorage.CachedResponse Response
        ) : Core.IType
        {
        }
        /// <summary>
        /// Requests data from cache.
        /// </summary>
        /// <param name="CacheId">ID of cache to get entries from.</param>
        /// <param name="SkipCount">Number of records to skip.</param>
        /// <param name="PageSize">Number of records to fetch.</param>
        /// <param name="PathFilter">If present, only return the entries containing this substring in the path</param>
        public static CacheStorage.RequestEntriesRequest RequestEntries(CacheStorage.CacheId CacheId, int? SkipCount = default, int? PageSize = default, string? PathFilter = default)
        {
            return new CacheStorage.RequestEntriesRequest(CacheId, SkipCount, PageSize, PathFilter);
        }
        /// <summary>
        /// Requests data from cache.
        /// </summary>
        /// <param name="CacheId">ID of cache to get entries from.</param>
        /// <param name="SkipCount">Number of records to skip.</param>
        /// <param name="PageSize">Number of records to fetch.</param>
        /// <param name="PathFilter">If present, only return the entries containing this substring in the path</param>
        [Core.MethodName("CacheStorage.requestEntries")]
        public record RequestEntriesRequest(
            CacheStorage.CacheId CacheId,
            int? SkipCount = default,
            int? PageSize = default,
            string? PathFilter = default
        ) : Core.ICommand<RequestEntriesRequestResult>
        {
        }
        /// <summary>
        /// Requests data from cache.
        /// </summary>
        /// <param name="CacheDataEntries">Array of object store data entries.</param>
        /// <param name="ReturnCount">Count of returned entries from this storage. If pathFilter is empty, it<br/>
        /// is the count of all entries from this storage.</param>
        public record RequestEntriesRequestResult(
            IReadOnlyList<CacheStorage.DataEntry> CacheDataEntries,
            double ReturnCount
        ) : Core.IType
        {
        }
    }
}
