// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Debugger
    {
        /// <summary>
        /// Breakpoint identifier.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record BreakpointId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Call frame identifier.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record CallFrameId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Location in the source code.
        /// </summary>
        /// <param name="ScriptId">Script identifier as reported in the `Debugger.scriptParsed`.</param>
        /// <param name="LineNumber">Line number in the script (0-based).</param>
        /// <param name="ColumnNumber">Column number in the script (0-based).</param>
        public record Location(
            Runtime.ScriptId ScriptId,
            int LineNumber,
            int? ColumnNumber = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Location in the source code.
        /// </summary>
        public record ScriptPosition(
            int LineNumber,
            int ColumnNumber
        ) : Core.IType
        {
        }
        /// <summary>
        /// Location range within one script.
        /// </summary>
        public record LocationRange(
            Runtime.ScriptId ScriptId,
            Debugger.ScriptPosition Start,
            Debugger.ScriptPosition End
        ) : Core.IType
        {
        }
        /// <summary>
        /// JavaScript call frame. Array of call frames form the call stack.
        /// </summary>
        /// <param name="CallFrameId">Call frame identifier. This identifier is only valid while the virtual machine is paused.</param>
        /// <param name="FunctionName">Name of the JavaScript function called on this call frame.</param>
        /// <param name="Location">Location in the source code.</param>
        /// <param name="Url">JavaScript script name or url.<br/>
        /// Deprecated in favor of using the `location.scriptId` to resolve the URL via a previously<br/>
        /// sent `Debugger.scriptParsed` event.</param>
        /// <param name="ScopeChain">Scope chain for this call frame.</param>
        /// <param name="This">`this` object for this call frame.</param>
        /// <param name="FunctionLocation">Location in the source code.</param>
        /// <param name="ReturnValue">The value being returned, if the function is at return point.</param>
        /// <param name="CanBeRestarted">Valid only while the VM is paused and indicates whether this frame<br/>
        /// can be restarted or not. Note that a `true` value here does not<br/>
        /// guarantee that Debugger#restartFrame with this CallFrameId will be<br/>
        /// successful, but it is very likely.</param>
        public record CallFrame(
            Debugger.CallFrameId CallFrameId,
            string FunctionName,
            Debugger.Location Location,
            string Url,
            IReadOnlyList<Debugger.Scope> ScopeChain,
            Runtime.RemoteObject This,
            Debugger.Location? FunctionLocation = default,
            Runtime.RemoteObject? ReturnValue = default,
            bool? CanBeRestarted = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Scope description.
        /// </summary>
        /// <param name="Type">Scope type.</param>
        /// <param name="Object">Object representing the scope. For `global` and `with` scopes it represents the actual<br/>
        /// object; for the rest of the scopes, it is artificial transient object enumerating scope<br/>
        /// variables as its properties.</param>
        /// <param name="StartLocation">Location in the source code where scope starts</param>
        /// <param name="EndLocation">Location in the source code where scope ends</param>
        public record Scope(
            string Type,
            Runtime.RemoteObject Object,
            string? Name = default,
            Debugger.Location? StartLocation = default,
            Debugger.Location? EndLocation = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Search match for resource.
        /// </summary>
        /// <param name="LineNumber">Line number in resource content.</param>
        /// <param name="LineContent">Line with match content.</param>
        public record SearchMatch(
            double LineNumber,
            string LineContent
        ) : Core.IType
        {
        }
        /// <param name="ScriptId">Script identifier as reported in the `Debugger.scriptParsed`.</param>
        /// <param name="LineNumber">Line number in the script (0-based).</param>
        /// <param name="ColumnNumber">Column number in the script (0-based).</param>
        public record BreakLocation(
            Runtime.ScriptId ScriptId,
            int LineNumber,
            int? ColumnNumber = default,
            string? Type = default
        ) : Core.IType
        {
        }
        /// <param name="Lines">The next chunk of disassembled lines.</param>
        /// <param name="BytecodeOffsets">The bytecode offsets describing the start of each line.</param>
        public record WasmDisassemblyChunk(
            IReadOnlyList<string> Lines,
            IReadOnlyList<int> BytecodeOffsets
        ) : Core.IType
        {
        }
        /// <summary>
        /// Enum of possible script languages.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ScriptLanguage(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly ScriptLanguage JAVA_SCRIPT = new("JavaScript");
            public static readonly ScriptLanguage WEB_ASSEMBLY = new("WebAssembly");
        }
        /// <summary>
        /// Debug symbols available for a wasm script.
        /// </summary>
        /// <param name="Type">Type of the debug symbols.</param>
        /// <param name="ExternalURL">URL of the external symbol source.</param>
        public record DebugSymbols(
            string Type,
            string? ExternalURL = default
        ) : Core.IType
        {
        }
        /// <param name="BreakpointId">Breakpoint unique identifier.</param>
        /// <param name="Location">Actual breakpoint location.</param>
        public record ResolvedBreakpoint(
            Debugger.BreakpointId BreakpointId,
            Debugger.Location Location
        ) : Core.IType
        {
        }
        /// <summary>
        /// Continues execution until specific location is reached.
        /// </summary>
        /// <param name="Location">Location to continue to.</param>
        public static Debugger.ContinueToLocationRequest ContinueToLocation(Debugger.Location Location, string? TargetCallFrames = default)
        {
            return new Debugger.ContinueToLocationRequest(Location, TargetCallFrames);
        }
        /// <summary>
        /// Continues execution until specific location is reached.
        /// </summary>
        /// <param name="Location">Location to continue to.</param>
        [Core.MethodName("Debugger.continueToLocation")]
        public record ContinueToLocationRequest(
            Debugger.Location Location,
            string? TargetCallFrames = default
        ) : Core.ICommand<ContinueToLocationRequestResult>
        {
        }
        /// <summary>
        /// Continues execution until specific location is reached.
        /// </summary>
        public record ContinueToLocationRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Disables debugger for given page.
        /// </summary>
        public static Debugger.DisableRequest Disable()
        {
            return new Debugger.DisableRequest();
        }
        /// <summary>
        /// Disables debugger for given page.
        /// </summary>
        [Core.MethodName("Debugger.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Disables debugger for given page.
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables debugger for the given page. Clients should not assume that the debugging has been<br/>
        /// enabled until the result for this command is received.
        /// </summary>
        /// <param name="MaxScriptsCacheSize">The maximum size in bytes of collected scripts (not referenced by other heap objects)<br/>
        /// the debugger can hold. Puts no limit if parameter is omitted.</param>
        public static Debugger.EnableRequest Enable(double? MaxScriptsCacheSize = default)
        {
            return new Debugger.EnableRequest(MaxScriptsCacheSize);
        }
        /// <summary>
        /// Enables debugger for the given page. Clients should not assume that the debugging has been<br/>
        /// enabled until the result for this command is received.
        /// </summary>
        /// <param name="MaxScriptsCacheSize">The maximum size in bytes of collected scripts (not referenced by other heap objects)<br/>
        /// the debugger can hold. Puts no limit if parameter is omitted.</param>
        [Core.MethodName("Debugger.enable")]
        public record EnableRequest(
            double? MaxScriptsCacheSize = default
        ) : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables debugger for the given page. Clients should not assume that the debugging has been<br/>
        /// enabled until the result for this command is received.
        /// </summary>
        /// <param name="DebuggerId">Unique identifier of the debugger.</param>
        public record EnableRequestResult(
            Runtime.UniqueDebuggerId DebuggerId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Evaluates expression on a given call frame.
        /// </summary>
        /// <param name="CallFrameId">Call frame identifier to evaluate on.</param>
        /// <param name="Expression">Expression to evaluate.</param>
        /// <param name="ObjectGroup">String object group name to put result into (allows rapid releasing resulting object handles<br/>
        /// using `releaseObjectGroup`).</param>
        /// <param name="IncludeCommandLineAPI">Specifies whether command line API should be available to the evaluated expression, defaults<br/>
        /// to false.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object that should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="ThrowOnSideEffect">Whether to throw an exception if side effect cannot be ruled out during evaluation.</param>
        /// <param name="Timeout">Terminate execution after timing out (number of milliseconds).</param>
        public static Debugger.EvaluateOnCallFrameRequest EvaluateOnCallFrame(Debugger.CallFrameId CallFrameId, string Expression, string? ObjectGroup = default, bool? IncludeCommandLineAPI = default, bool? Silent = default, bool? ReturnByValue = default, bool? GeneratePreview = default, bool? ThrowOnSideEffect = default, Runtime.TimeDelta? Timeout = default)
        {
            return new Debugger.EvaluateOnCallFrameRequest(CallFrameId, Expression, ObjectGroup, IncludeCommandLineAPI, Silent, ReturnByValue, GeneratePreview, ThrowOnSideEffect, Timeout);
        }
        /// <summary>
        /// Evaluates expression on a given call frame.
        /// </summary>
        /// <param name="CallFrameId">Call frame identifier to evaluate on.</param>
        /// <param name="Expression">Expression to evaluate.</param>
        /// <param name="ObjectGroup">String object group name to put result into (allows rapid releasing resulting object handles<br/>
        /// using `releaseObjectGroup`).</param>
        /// <param name="IncludeCommandLineAPI">Specifies whether command line API should be available to the evaluated expression, defaults<br/>
        /// to false.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object that should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="ThrowOnSideEffect">Whether to throw an exception if side effect cannot be ruled out during evaluation.</param>
        /// <param name="Timeout">Terminate execution after timing out (number of milliseconds).</param>
        [Core.MethodName("Debugger.evaluateOnCallFrame")]
        public record EvaluateOnCallFrameRequest(
            Debugger.CallFrameId CallFrameId,
            string Expression,
            string? ObjectGroup = default,
            bool? IncludeCommandLineAPI = default,
            bool? Silent = default,
            bool? ReturnByValue = default,
            bool? GeneratePreview = default,
            bool? ThrowOnSideEffect = default,
            Runtime.TimeDelta? Timeout = default
        ) : Core.ICommand<EvaluateOnCallFrameRequestResult>
        {
        }
        /// <summary>
        /// Evaluates expression on a given call frame.
        /// </summary>
        /// <param name="Result">Object wrapper for the evaluation result.</param>
        /// <param name="ExceptionDetails">Exception details.</param>
        public record EvaluateOnCallFrameRequestResult(
            Runtime.RemoteObject Result,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns possible locations for breakpoint. scriptId in start and end range locations should be<br/>
        /// the same.
        /// </summary>
        /// <param name="Start">Start of range to search possible breakpoint locations in.</param>
        /// <param name="End">End of range to search possible breakpoint locations in (excluding). When not specified, end<br/>
        /// of scripts is used as end of range.</param>
        /// <param name="RestrictToFunction">Only consider locations which are in the same (non-nested) function as start.</param>
        public static Debugger.GetPossibleBreakpointsRequest GetPossibleBreakpoints(Debugger.Location Start, Debugger.Location? End = default, bool? RestrictToFunction = default)
        {
            return new Debugger.GetPossibleBreakpointsRequest(Start, End, RestrictToFunction);
        }
        /// <summary>
        /// Returns possible locations for breakpoint. scriptId in start and end range locations should be<br/>
        /// the same.
        /// </summary>
        /// <param name="Start">Start of range to search possible breakpoint locations in.</param>
        /// <param name="End">End of range to search possible breakpoint locations in (excluding). When not specified, end<br/>
        /// of scripts is used as end of range.</param>
        /// <param name="RestrictToFunction">Only consider locations which are in the same (non-nested) function as start.</param>
        [Core.MethodName("Debugger.getPossibleBreakpoints")]
        public record GetPossibleBreakpointsRequest(
            Debugger.Location Start,
            Debugger.Location? End = default,
            bool? RestrictToFunction = default
        ) : Core.ICommand<GetPossibleBreakpointsRequestResult>
        {
        }
        /// <summary>
        /// Returns possible locations for breakpoint. scriptId in start and end range locations should be<br/>
        /// the same.
        /// </summary>
        /// <param name="Locations">List of the possible breakpoint locations.</param>
        public record GetPossibleBreakpointsRequestResult(
            IReadOnlyList<Debugger.BreakLocation> Locations
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns source for the script with given id.
        /// </summary>
        /// <param name="ScriptId">Id of the script to get source for.</param>
        public static Debugger.GetScriptSourceRequest GetScriptSource(Runtime.ScriptId ScriptId)
        {
            return new Debugger.GetScriptSourceRequest(ScriptId);
        }
        /// <summary>
        /// Returns source for the script with given id.
        /// </summary>
        /// <param name="ScriptId">Id of the script to get source for.</param>
        [Core.MethodName("Debugger.getScriptSource")]
        public record GetScriptSourceRequest(
            Runtime.ScriptId ScriptId
        ) : Core.ICommand<GetScriptSourceRequestResult>
        {
        }
        /// <summary>
        /// Returns source for the script with given id.
        /// </summary>
        /// <param name="ScriptSource">Script source (empty in case of Wasm bytecode).</param>
        /// <param name="Bytecode">Wasm bytecode. (Encoded as a base64 string when passed over JSON)</param>
        public record GetScriptSourceRequestResult(
            string ScriptSource,
            string? Bytecode = default
        ) : Core.IType
        {
        }
        /// <param name="ScriptId">Id of the script to disassemble</param>
        public static Debugger.DisassembleWasmModuleRequest DisassembleWasmModule(Runtime.ScriptId ScriptId)
        {
            return new Debugger.DisassembleWasmModuleRequest(ScriptId);
        }
        /// <param name="ScriptId">Id of the script to disassemble</param>
        [Core.MethodName("Debugger.disassembleWasmModule")]
        public record DisassembleWasmModuleRequest(
            Runtime.ScriptId ScriptId
        ) : Core.ICommand<DisassembleWasmModuleRequestResult>
        {
        }
        /// <param name="TotalNumberOfLines">The total number of lines in the disassembly text.</param>
        /// <param name="FunctionBodyOffsets">The offsets of all function bodies, in the format [start1, end1,<br/>
        /// start2, end2, ...] where all ends are exclusive.</param>
        /// <param name="Chunk">The first chunk of disassembly.</param>
        /// <param name="StreamId">For large modules, return a stream from which additional chunks of<br/>
        /// disassembly can be read successively.</param>
        public record DisassembleWasmModuleRequestResult(
            int TotalNumberOfLines,
            IReadOnlyList<int> FunctionBodyOffsets,
            Debugger.WasmDisassemblyChunk Chunk,
            string? StreamId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Disassemble the next chunk of lines for the module corresponding to the<br/>
        /// stream. If disassembly is complete, this API will invalidate the streamId<br/>
        /// and return an empty chunk. Any subsequent calls for the now invalid stream<br/>
        /// will return errors.
        /// </summary>
        public static Debugger.NextWasmDisassemblyChunkRequest NextWasmDisassemblyChunk(string StreamId)
        {
            return new Debugger.NextWasmDisassemblyChunkRequest(StreamId);
        }
        /// <summary>
        /// Disassemble the next chunk of lines for the module corresponding to the<br/>
        /// stream. If disassembly is complete, this API will invalidate the streamId<br/>
        /// and return an empty chunk. Any subsequent calls for the now invalid stream<br/>
        /// will return errors.
        /// </summary>
        [Core.MethodName("Debugger.nextWasmDisassemblyChunk")]
        public record NextWasmDisassemblyChunkRequest(
            string StreamId
        ) : Core.ICommand<NextWasmDisassemblyChunkRequestResult>
        {
        }
        /// <summary>
        /// Disassemble the next chunk of lines for the module corresponding to the<br/>
        /// stream. If disassembly is complete, this API will invalidate the streamId<br/>
        /// and return an empty chunk. Any subsequent calls for the now invalid stream<br/>
        /// will return errors.
        /// </summary>
        /// <param name="Chunk">The next chunk of disassembly.</param>
        public record NextWasmDisassemblyChunkRequestResult(
            Debugger.WasmDisassemblyChunk Chunk
        ) : Core.IType
        {
        }
        /// <summary>
        /// This command is deprecated. Use getScriptSource instead.
        /// </summary>
        /// <param name="ScriptId">Id of the Wasm script to get source for.</param>
        [Obsolete]
        public static Debugger.GetWasmBytecodeRequest GetWasmBytecode(Runtime.ScriptId ScriptId)
        {
            return new Debugger.GetWasmBytecodeRequest(ScriptId);
        }
        /// <summary>
        /// This command is deprecated. Use getScriptSource instead.
        /// </summary>
        /// <param name="ScriptId">Id of the Wasm script to get source for.</param>
        [Obsolete]
        [Core.MethodName("Debugger.getWasmBytecode")]
        public record GetWasmBytecodeRequest(
            Runtime.ScriptId ScriptId
        ) : Core.ICommand<GetWasmBytecodeRequestResult>
        {
        }
        /// <summary>
        /// This command is deprecated. Use getScriptSource instead.
        /// </summary>
        /// <param name="Bytecode">Script source. (Encoded as a base64 string when passed over JSON)</param>
        [Obsolete]
        public record GetWasmBytecodeRequestResult(
            string Bytecode
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns stack trace with given `stackTraceId`.
        /// </summary>
        public static Debugger.GetStackTraceRequest GetStackTrace(Runtime.StackTraceId StackTraceId)
        {
            return new Debugger.GetStackTraceRequest(StackTraceId);
        }
        /// <summary>
        /// Returns stack trace with given `stackTraceId`.
        /// </summary>
        [Core.MethodName("Debugger.getStackTrace")]
        public record GetStackTraceRequest(
            Runtime.StackTraceId StackTraceId
        ) : Core.ICommand<GetStackTraceRequestResult>
        {
        }
        /// <summary>
        /// Returns stack trace with given `stackTraceId`.
        /// </summary>
        public record GetStackTraceRequestResult(
            Runtime.StackTrace StackTrace
        ) : Core.IType
        {
        }
        /// <summary>
        /// Stops on the next JavaScript statement.
        /// </summary>
        public static Debugger.PauseRequest Pause()
        {
            return new Debugger.PauseRequest();
        }
        /// <summary>
        /// Stops on the next JavaScript statement.
        /// </summary>
        [Core.MethodName("Debugger.pause")]
        public record PauseRequest() : Core.ICommand<PauseRequestResult>
        {
        }
        /// <summary>
        /// Stops on the next JavaScript statement.
        /// </summary>
        public record PauseRequestResult() : Core.IType
        {
        }
        /// <param name="ParentStackTraceId">Debugger will pause when async call with given stack trace is started.</param>
        [Obsolete]
        public static Debugger.PauseOnAsyncCallRequest PauseOnAsyncCall(Runtime.StackTraceId ParentStackTraceId)
        {
            return new Debugger.PauseOnAsyncCallRequest(ParentStackTraceId);
        }
        /// <param name="ParentStackTraceId">Debugger will pause when async call with given stack trace is started.</param>
        [Obsolete]
        [Core.MethodName("Debugger.pauseOnAsyncCall")]
        public record PauseOnAsyncCallRequest(
            Runtime.StackTraceId ParentStackTraceId
        ) : Core.ICommand<PauseOnAsyncCallRequestResult>
        {
        }
        [Obsolete]
        public record PauseOnAsyncCallRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes JavaScript breakpoint.
        /// </summary>
        public static Debugger.RemoveBreakpointRequest RemoveBreakpoint(Debugger.BreakpointId BreakpointId)
        {
            return new Debugger.RemoveBreakpointRequest(BreakpointId);
        }
        /// <summary>
        /// Removes JavaScript breakpoint.
        /// </summary>
        [Core.MethodName("Debugger.removeBreakpoint")]
        public record RemoveBreakpointRequest(
            Debugger.BreakpointId BreakpointId
        ) : Core.ICommand<RemoveBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Removes JavaScript breakpoint.
        /// </summary>
        public record RemoveBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Restarts particular call frame from the beginning. The old, deprecated<br/>
        /// behavior of `restartFrame` is to stay paused and allow further CDP commands<br/>
        /// after a restart was scheduled. This can cause problems with restarting, so<br/>
        /// we now continue execution immediatly after it has been scheduled until we<br/>
        /// reach the beginning of the restarted frame.<br/>
        /// <br/>
        /// To stay back-wards compatible, `restartFrame` now expects a `mode`<br/>
        /// parameter to be present. If the `mode` parameter is missing, `restartFrame`<br/>
        /// errors out.<br/>
        /// <br/>
        /// The various return values are deprecated and `callFrames` is always empty.<br/>
        /// Use the call frames from the `Debugger#paused` events instead, that fires<br/>
        /// once V8 pauses at the beginning of the restarted function.
        /// </summary>
        /// <param name="CallFrameId">Call frame identifier to evaluate on.</param>
        /// <param name="Mode">The `mode` parameter must be present and set to &apos;StepInto&apos;, otherwise<br/>
        /// `restartFrame` will error out.</param>
        public static Debugger.RestartFrameRequest RestartFrame(Debugger.CallFrameId CallFrameId, string? Mode = default)
        {
            return new Debugger.RestartFrameRequest(CallFrameId, Mode);
        }
        /// <summary>
        /// Restarts particular call frame from the beginning. The old, deprecated<br/>
        /// behavior of `restartFrame` is to stay paused and allow further CDP commands<br/>
        /// after a restart was scheduled. This can cause problems with restarting, so<br/>
        /// we now continue execution immediatly after it has been scheduled until we<br/>
        /// reach the beginning of the restarted frame.<br/>
        /// <br/>
        /// To stay back-wards compatible, `restartFrame` now expects a `mode`<br/>
        /// parameter to be present. If the `mode` parameter is missing, `restartFrame`<br/>
        /// errors out.<br/>
        /// <br/>
        /// The various return values are deprecated and `callFrames` is always empty.<br/>
        /// Use the call frames from the `Debugger#paused` events instead, that fires<br/>
        /// once V8 pauses at the beginning of the restarted function.
        /// </summary>
        /// <param name="CallFrameId">Call frame identifier to evaluate on.</param>
        /// <param name="Mode">The `mode` parameter must be present and set to &apos;StepInto&apos;, otherwise<br/>
        /// `restartFrame` will error out.</param>
        [Core.MethodName("Debugger.restartFrame")]
        public record RestartFrameRequest(
            Debugger.CallFrameId CallFrameId,
            string? Mode = default
        ) : Core.ICommand<RestartFrameRequestResult>
        {
        }
        /// <summary>
        /// Restarts particular call frame from the beginning. The old, deprecated<br/>
        /// behavior of `restartFrame` is to stay paused and allow further CDP commands<br/>
        /// after a restart was scheduled. This can cause problems with restarting, so<br/>
        /// we now continue execution immediatly after it has been scheduled until we<br/>
        /// reach the beginning of the restarted frame.<br/>
        /// <br/>
        /// To stay back-wards compatible, `restartFrame` now expects a `mode`<br/>
        /// parameter to be present. If the `mode` parameter is missing, `restartFrame`<br/>
        /// errors out.<br/>
        /// <br/>
        /// The various return values are deprecated and `callFrames` is always empty.<br/>
        /// Use the call frames from the `Debugger#paused` events instead, that fires<br/>
        /// once V8 pauses at the beginning of the restarted function.
        /// </summary>
        /// <param name="CallFrames">New stack trace.</param>
        /// <param name="AsyncStackTrace">Async stack trace, if any.</param>
        /// <param name="AsyncStackTraceId">Async stack trace, if any.</param>
        public record RestartFrameRequestResult(
            IReadOnlyList<Debugger.CallFrame> CallFrames,
            Runtime.StackTrace? AsyncStackTrace = default,
            Runtime.StackTraceId? AsyncStackTraceId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Resumes JavaScript execution.
        /// </summary>
        /// <param name="TerminateOnResume">Set to true to terminate execution upon resuming execution. In contrast<br/>
        /// to Runtime.terminateExecution, this will allows to execute further<br/>
        /// JavaScript (i.e. via evaluation) until execution of the paused code<br/>
        /// is actually resumed, at which point termination is triggered.<br/>
        /// If execution is currently not paused, this parameter has no effect.</param>
        public static Debugger.ResumeRequest Resume(bool? TerminateOnResume = default)
        {
            return new Debugger.ResumeRequest(TerminateOnResume);
        }
        /// <summary>
        /// Resumes JavaScript execution.
        /// </summary>
        /// <param name="TerminateOnResume">Set to true to terminate execution upon resuming execution. In contrast<br/>
        /// to Runtime.terminateExecution, this will allows to execute further<br/>
        /// JavaScript (i.e. via evaluation) until execution of the paused code<br/>
        /// is actually resumed, at which point termination is triggered.<br/>
        /// If execution is currently not paused, this parameter has no effect.</param>
        [Core.MethodName("Debugger.resume")]
        public record ResumeRequest(
            bool? TerminateOnResume = default
        ) : Core.ICommand<ResumeRequestResult>
        {
        }
        /// <summary>
        /// Resumes JavaScript execution.
        /// </summary>
        public record ResumeRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Searches for given string in script content.
        /// </summary>
        /// <param name="ScriptId">Id of the script to search in.</param>
        /// <param name="Query">String to search for.</param>
        /// <param name="CaseSensitive">If true, search is case sensitive.</param>
        /// <param name="IsRegex">If true, treats string parameter as regex.</param>
        public static Debugger.SearchInContentRequest SearchInContent(Runtime.ScriptId ScriptId, string Query, bool? CaseSensitive = default, bool? IsRegex = default)
        {
            return new Debugger.SearchInContentRequest(ScriptId, Query, CaseSensitive, IsRegex);
        }
        /// <summary>
        /// Searches for given string in script content.
        /// </summary>
        /// <param name="ScriptId">Id of the script to search in.</param>
        /// <param name="Query">String to search for.</param>
        /// <param name="CaseSensitive">If true, search is case sensitive.</param>
        /// <param name="IsRegex">If true, treats string parameter as regex.</param>
        [Core.MethodName("Debugger.searchInContent")]
        public record SearchInContentRequest(
            Runtime.ScriptId ScriptId,
            string Query,
            bool? CaseSensitive = default,
            bool? IsRegex = default
        ) : Core.ICommand<SearchInContentRequestResult>
        {
        }
        /// <summary>
        /// Searches for given string in script content.
        /// </summary>
        /// <param name="Result">List of search matches.</param>
        public record SearchInContentRequestResult(
            IReadOnlyList<Debugger.SearchMatch> Result
        ) : Core.IType
        {
        }
        /// <summary>
        /// Enables or disables async call stacks tracking.
        /// </summary>
        /// <param name="MaxDepth">Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async<br/>
        /// call stacks (default).</param>
        public static Debugger.SetAsyncCallStackDepthRequest SetAsyncCallStackDepth(int MaxDepth)
        {
            return new Debugger.SetAsyncCallStackDepthRequest(MaxDepth);
        }
        /// <summary>
        /// Enables or disables async call stacks tracking.
        /// </summary>
        /// <param name="MaxDepth">Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async<br/>
        /// call stacks (default).</param>
        [Core.MethodName("Debugger.setAsyncCallStackDepth")]
        public record SetAsyncCallStackDepthRequest(
            int MaxDepth
        ) : Core.ICommand<SetAsyncCallStackDepthRequestResult>
        {
        }
        /// <summary>
        /// Enables or disables async call stacks tracking.
        /// </summary>
        public record SetAsyncCallStackDepthRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Replace previous blackbox execution contexts with passed ones. Forces backend to skip<br/>
        /// stepping/pausing in scripts in these execution contexts. VM will try to leave blackboxed script by<br/>
        /// performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.
        /// </summary>
        /// <param name="UniqueIds">Array of execution context unique ids for the debugger to ignore.</param>
        public static Debugger.SetBlackboxExecutionContextsRequest SetBlackboxExecutionContexts(IReadOnlyList<string> UniqueIds)
        {
            return new Debugger.SetBlackboxExecutionContextsRequest(UniqueIds);
        }
        /// <summary>
        /// Replace previous blackbox execution contexts with passed ones. Forces backend to skip<br/>
        /// stepping/pausing in scripts in these execution contexts. VM will try to leave blackboxed script by<br/>
        /// performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.
        /// </summary>
        /// <param name="UniqueIds">Array of execution context unique ids for the debugger to ignore.</param>
        [Core.MethodName("Debugger.setBlackboxExecutionContexts")]
        public record SetBlackboxExecutionContextsRequest(
            IReadOnlyList<string> UniqueIds
        ) : Core.ICommand<SetBlackboxExecutionContextsRequestResult>
        {
        }
        /// <summary>
        /// Replace previous blackbox execution contexts with passed ones. Forces backend to skip<br/>
        /// stepping/pausing in scripts in these execution contexts. VM will try to leave blackboxed script by<br/>
        /// performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.
        /// </summary>
        public record SetBlackboxExecutionContextsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Replace previous blackbox patterns with passed ones. Forces backend to skip stepping/pausing in<br/>
        /// scripts with url matching one of the patterns. VM will try to leave blackboxed script by<br/>
        /// performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.
        /// </summary>
        /// <param name="Patterns">Array of regexps that will be used to check script url for blackbox state.</param>
        /// <param name="SkipAnonymous">If true, also ignore scripts with no source url.</param>
        public static Debugger.SetBlackboxPatternsRequest SetBlackboxPatterns(IReadOnlyList<string> Patterns, bool? SkipAnonymous = default)
        {
            return new Debugger.SetBlackboxPatternsRequest(Patterns, SkipAnonymous);
        }
        /// <summary>
        /// Replace previous blackbox patterns with passed ones. Forces backend to skip stepping/pausing in<br/>
        /// scripts with url matching one of the patterns. VM will try to leave blackboxed script by<br/>
        /// performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.
        /// </summary>
        /// <param name="Patterns">Array of regexps that will be used to check script url for blackbox state.</param>
        /// <param name="SkipAnonymous">If true, also ignore scripts with no source url.</param>
        [Core.MethodName("Debugger.setBlackboxPatterns")]
        public record SetBlackboxPatternsRequest(
            IReadOnlyList<string> Patterns,
            bool? SkipAnonymous = default
        ) : Core.ICommand<SetBlackboxPatternsRequestResult>
        {
        }
        /// <summary>
        /// Replace previous blackbox patterns with passed ones. Forces backend to skip stepping/pausing in<br/>
        /// scripts with url matching one of the patterns. VM will try to leave blackboxed script by<br/>
        /// performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.
        /// </summary>
        public record SetBlackboxPatternsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Makes backend skip steps in the script in blackboxed ranges. VM will try leave blacklisted<br/>
        /// scripts by performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.<br/>
        /// Positions array contains positions where blackbox state is changed. First interval isn&apos;t<br/>
        /// blackboxed. Array should be sorted.
        /// </summary>
        /// <param name="ScriptId">Id of the script.</param>
        public static Debugger.SetBlackboxedRangesRequest SetBlackboxedRanges(Runtime.ScriptId ScriptId, IReadOnlyList<Debugger.ScriptPosition> Positions)
        {
            return new Debugger.SetBlackboxedRangesRequest(ScriptId, Positions);
        }
        /// <summary>
        /// Makes backend skip steps in the script in blackboxed ranges. VM will try leave blacklisted<br/>
        /// scripts by performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.<br/>
        /// Positions array contains positions where blackbox state is changed. First interval isn&apos;t<br/>
        /// blackboxed. Array should be sorted.
        /// </summary>
        /// <param name="ScriptId">Id of the script.</param>
        [Core.MethodName("Debugger.setBlackboxedRanges")]
        public record SetBlackboxedRangesRequest(
            Runtime.ScriptId ScriptId,
            IReadOnlyList<Debugger.ScriptPosition> Positions
        ) : Core.ICommand<SetBlackboxedRangesRequestResult>
        {
        }
        /// <summary>
        /// Makes backend skip steps in the script in blackboxed ranges. VM will try leave blacklisted<br/>
        /// scripts by performing &apos;step in&apos; several times, finally resorting to &apos;step out&apos; if unsuccessful.<br/>
        /// Positions array contains positions where blackbox state is changed. First interval isn&apos;t<br/>
        /// blackboxed. Array should be sorted.
        /// </summary>
        public record SetBlackboxedRangesRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets JavaScript breakpoint at a given location.
        /// </summary>
        /// <param name="Location">Location to set breakpoint in.</param>
        /// <param name="Condition">Expression to use as a breakpoint condition. When specified, debugger will only stop on the<br/>
        /// breakpoint if this expression evaluates to true.</param>
        public static Debugger.SetBreakpointRequest SetBreakpoint(Debugger.Location Location, string? Condition = default)
        {
            return new Debugger.SetBreakpointRequest(Location, Condition);
        }
        /// <summary>
        /// Sets JavaScript breakpoint at a given location.
        /// </summary>
        /// <param name="Location">Location to set breakpoint in.</param>
        /// <param name="Condition">Expression to use as a breakpoint condition. When specified, debugger will only stop on the<br/>
        /// breakpoint if this expression evaluates to true.</param>
        [Core.MethodName("Debugger.setBreakpoint")]
        public record SetBreakpointRequest(
            Debugger.Location Location,
            string? Condition = default
        ) : Core.ICommand<SetBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets JavaScript breakpoint at a given location.
        /// </summary>
        /// <param name="BreakpointId">Id of the created breakpoint for further reference.</param>
        /// <param name="ActualLocation">Location this breakpoint resolved into.</param>
        public record SetBreakpointRequestResult(
            Debugger.BreakpointId BreakpointId,
            Debugger.Location ActualLocation
        ) : Core.IType
        {
        }
        /// <summary>
        /// Sets instrumentation breakpoint.
        /// </summary>
        /// <param name="Instrumentation">Instrumentation name.</param>
        public static Debugger.SetInstrumentationBreakpointRequest SetInstrumentationBreakpoint(string Instrumentation)
        {
            return new Debugger.SetInstrumentationBreakpointRequest(Instrumentation);
        }
        /// <summary>
        /// Sets instrumentation breakpoint.
        /// </summary>
        /// <param name="Instrumentation">Instrumentation name.</param>
        [Core.MethodName("Debugger.setInstrumentationBreakpoint")]
        public record SetInstrumentationBreakpointRequest(
            string Instrumentation
        ) : Core.ICommand<SetInstrumentationBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets instrumentation breakpoint.
        /// </summary>
        /// <param name="BreakpointId">Id of the created breakpoint for further reference.</param>
        public record SetInstrumentationBreakpointRequestResult(
            Debugger.BreakpointId BreakpointId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this<br/>
        /// command is issued, all existing parsed scripts will have breakpoints resolved and returned in<br/>
        /// `locations` property. Further matching script parsing will result in subsequent<br/>
        /// `breakpointResolved` events issued. This logical breakpoint will survive page reloads.
        /// </summary>
        /// <param name="LineNumber">Line number to set breakpoint at.</param>
        /// <param name="Url">URL of the resources to set breakpoint on.</param>
        /// <param name="UrlRegex">Regex pattern for the URLs of the resources to set breakpoints on. Either `url` or<br/>
        /// `urlRegex` must be specified.</param>
        /// <param name="ScriptHash">Script hash of the resources to set breakpoint on.</param>
        /// <param name="ColumnNumber">Offset in the line to set breakpoint at.</param>
        /// <param name="Condition">Expression to use as a breakpoint condition. When specified, debugger will only stop on the<br/>
        /// breakpoint if this expression evaluates to true.</param>
        public static Debugger.SetBreakpointByUrlRequest SetBreakpointByUrl(int LineNumber, string? Url = default, string? UrlRegex = default, string? ScriptHash = default, int? ColumnNumber = default, string? Condition = default)
        {
            return new Debugger.SetBreakpointByUrlRequest(LineNumber, Url, UrlRegex, ScriptHash, ColumnNumber, Condition);
        }
        /// <summary>
        /// Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this<br/>
        /// command is issued, all existing parsed scripts will have breakpoints resolved and returned in<br/>
        /// `locations` property. Further matching script parsing will result in subsequent<br/>
        /// `breakpointResolved` events issued. This logical breakpoint will survive page reloads.
        /// </summary>
        /// <param name="LineNumber">Line number to set breakpoint at.</param>
        /// <param name="Url">URL of the resources to set breakpoint on.</param>
        /// <param name="UrlRegex">Regex pattern for the URLs of the resources to set breakpoints on. Either `url` or<br/>
        /// `urlRegex` must be specified.</param>
        /// <param name="ScriptHash">Script hash of the resources to set breakpoint on.</param>
        /// <param name="ColumnNumber">Offset in the line to set breakpoint at.</param>
        /// <param name="Condition">Expression to use as a breakpoint condition. When specified, debugger will only stop on the<br/>
        /// breakpoint if this expression evaluates to true.</param>
        [Core.MethodName("Debugger.setBreakpointByUrl")]
        public record SetBreakpointByUrlRequest(
            int LineNumber,
            string? Url = default,
            string? UrlRegex = default,
            string? ScriptHash = default,
            int? ColumnNumber = default,
            string? Condition = default
        ) : Core.ICommand<SetBreakpointByUrlRequestResult>
        {
        }
        /// <summary>
        /// Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this<br/>
        /// command is issued, all existing parsed scripts will have breakpoints resolved and returned in<br/>
        /// `locations` property. Further matching script parsing will result in subsequent<br/>
        /// `breakpointResolved` events issued. This logical breakpoint will survive page reloads.
        /// </summary>
        /// <param name="BreakpointId">Id of the created breakpoint for further reference.</param>
        /// <param name="Locations">List of the locations this breakpoint resolved into upon addition.</param>
        public record SetBreakpointByUrlRequestResult(
            Debugger.BreakpointId BreakpointId,
            IReadOnlyList<Debugger.Location> Locations
        ) : Core.IType
        {
        }
        /// <summary>
        /// Sets JavaScript breakpoint before each call to the given function.<br/>
        /// If another function was created from the same source as a given one,<br/>
        /// calling it will also trigger the breakpoint.
        /// </summary>
        /// <param name="ObjectId">Function object id.</param>
        /// <param name="Condition">Expression to use as a breakpoint condition. When specified, debugger will<br/>
        /// stop on the breakpoint if this expression evaluates to true.</param>
        public static Debugger.SetBreakpointOnFunctionCallRequest SetBreakpointOnFunctionCall(Runtime.RemoteObjectId ObjectId, string? Condition = default)
        {
            return new Debugger.SetBreakpointOnFunctionCallRequest(ObjectId, Condition);
        }
        /// <summary>
        /// Sets JavaScript breakpoint before each call to the given function.<br/>
        /// If another function was created from the same source as a given one,<br/>
        /// calling it will also trigger the breakpoint.
        /// </summary>
        /// <param name="ObjectId">Function object id.</param>
        /// <param name="Condition">Expression to use as a breakpoint condition. When specified, debugger will<br/>
        /// stop on the breakpoint if this expression evaluates to true.</param>
        [Core.MethodName("Debugger.setBreakpointOnFunctionCall")]
        public record SetBreakpointOnFunctionCallRequest(
            Runtime.RemoteObjectId ObjectId,
            string? Condition = default
        ) : Core.ICommand<SetBreakpointOnFunctionCallRequestResult>
        {
        }
        /// <summary>
        /// Sets JavaScript breakpoint before each call to the given function.<br/>
        /// If another function was created from the same source as a given one,<br/>
        /// calling it will also trigger the breakpoint.
        /// </summary>
        /// <param name="BreakpointId">Id of the created breakpoint for further reference.</param>
        public record SetBreakpointOnFunctionCallRequestResult(
            Debugger.BreakpointId BreakpointId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Activates / deactivates all breakpoints on the page.
        /// </summary>
        /// <param name="Active">New value for breakpoints active state.</param>
        public static Debugger.SetBreakpointsActiveRequest SetBreakpointsActive(bool Active)
        {
            return new Debugger.SetBreakpointsActiveRequest(Active);
        }
        /// <summary>
        /// Activates / deactivates all breakpoints on the page.
        /// </summary>
        /// <param name="Active">New value for breakpoints active state.</param>
        [Core.MethodName("Debugger.setBreakpointsActive")]
        public record SetBreakpointsActiveRequest(
            bool Active
        ) : Core.ICommand<SetBreakpointsActiveRequestResult>
        {
        }
        /// <summary>
        /// Activates / deactivates all breakpoints on the page.
        /// </summary>
        public record SetBreakpointsActiveRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Defines pause on exceptions state. Can be set to stop on all exceptions, uncaught exceptions,<br/>
        /// or caught exceptions, no exceptions. Initial pause on exceptions state is `none`.
        /// </summary>
        /// <param name="State">Pause on exceptions mode.</param>
        public static Debugger.SetPauseOnExceptionsRequest SetPauseOnExceptions(string State)
        {
            return new Debugger.SetPauseOnExceptionsRequest(State);
        }
        /// <summary>
        /// Defines pause on exceptions state. Can be set to stop on all exceptions, uncaught exceptions,<br/>
        /// or caught exceptions, no exceptions. Initial pause on exceptions state is `none`.
        /// </summary>
        /// <param name="State">Pause on exceptions mode.</param>
        [Core.MethodName("Debugger.setPauseOnExceptions")]
        public record SetPauseOnExceptionsRequest(
            string State
        ) : Core.ICommand<SetPauseOnExceptionsRequestResult>
        {
        }
        /// <summary>
        /// Defines pause on exceptions state. Can be set to stop on all exceptions, uncaught exceptions,<br/>
        /// or caught exceptions, no exceptions. Initial pause on exceptions state is `none`.
        /// </summary>
        public record SetPauseOnExceptionsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Changes return value in top frame. Available only at return break position.
        /// </summary>
        /// <param name="NewValue">New return value.</param>
        public static Debugger.SetReturnValueRequest SetReturnValue(Runtime.CallArgument NewValue)
        {
            return new Debugger.SetReturnValueRequest(NewValue);
        }
        /// <summary>
        /// Changes return value in top frame. Available only at return break position.
        /// </summary>
        /// <param name="NewValue">New return value.</param>
        [Core.MethodName("Debugger.setReturnValue")]
        public record SetReturnValueRequest(
            Runtime.CallArgument NewValue
        ) : Core.ICommand<SetReturnValueRequestResult>
        {
        }
        /// <summary>
        /// Changes return value in top frame. Available only at return break position.
        /// </summary>
        public record SetReturnValueRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Edits JavaScript source live.<br/>
        /// <br/>
        /// In general, functions that are currently on the stack can not be edited with<br/>
        /// a single exception: If the edited function is the top-most stack frame and<br/>
        /// that is the only activation of that function on the stack. In this case<br/>
        /// the live edit will be successful and a `Debugger.restartFrame` for the<br/>
        /// top-most function is automatically triggered.
        /// </summary>
        /// <param name="ScriptId">Id of the script to edit.</param>
        /// <param name="ScriptSource">New content of the script.</param>
        /// <param name="DryRun">If true the change will not actually be applied. Dry run may be used to get result<br/>
        /// description without actually modifying the code.</param>
        /// <param name="AllowTopFrameEditing">If true, then `scriptSource` is allowed to change the function on top of the stack<br/>
        /// as long as the top-most stack frame is the only activation of that function.</param>
        public static Debugger.SetScriptSourceRequest SetScriptSource(Runtime.ScriptId ScriptId, string ScriptSource, bool? DryRun = default, bool? AllowTopFrameEditing = default)
        {
            return new Debugger.SetScriptSourceRequest(ScriptId, ScriptSource, DryRun, AllowTopFrameEditing);
        }
        /// <summary>
        /// Edits JavaScript source live.<br/>
        /// <br/>
        /// In general, functions that are currently on the stack can not be edited with<br/>
        /// a single exception: If the edited function is the top-most stack frame and<br/>
        /// that is the only activation of that function on the stack. In this case<br/>
        /// the live edit will be successful and a `Debugger.restartFrame` for the<br/>
        /// top-most function is automatically triggered.
        /// </summary>
        /// <param name="ScriptId">Id of the script to edit.</param>
        /// <param name="ScriptSource">New content of the script.</param>
        /// <param name="DryRun">If true the change will not actually be applied. Dry run may be used to get result<br/>
        /// description without actually modifying the code.</param>
        /// <param name="AllowTopFrameEditing">If true, then `scriptSource` is allowed to change the function on top of the stack<br/>
        /// as long as the top-most stack frame is the only activation of that function.</param>
        [Core.MethodName("Debugger.setScriptSource")]
        public record SetScriptSourceRequest(
            Runtime.ScriptId ScriptId,
            string ScriptSource,
            bool? DryRun = default,
            bool? AllowTopFrameEditing = default
        ) : Core.ICommand<SetScriptSourceRequestResult>
        {
        }
        /// <summary>
        /// Edits JavaScript source live.<br/>
        /// <br/>
        /// In general, functions that are currently on the stack can not be edited with<br/>
        /// a single exception: If the edited function is the top-most stack frame and<br/>
        /// that is the only activation of that function on the stack. In this case<br/>
        /// the live edit will be successful and a `Debugger.restartFrame` for the<br/>
        /// top-most function is automatically triggered.
        /// </summary>
        /// <param name="Status">Whether the operation was successful or not. Only `Ok` denotes a<br/>
        /// successful live edit while the other enum variants denote why<br/>
        /// the live edit failed.</param>
        /// <param name="CallFrames">New stack trace in case editing has happened while VM was stopped.</param>
        /// <param name="StackChanged">Whether current call stack  was modified after applying the changes.</param>
        /// <param name="AsyncStackTrace">Async stack trace, if any.</param>
        /// <param name="AsyncStackTraceId">Async stack trace, if any.</param>
        /// <param name="ExceptionDetails">Exception details if any. Only present when `status` is `CompileError`.</param>
        public record SetScriptSourceRequestResult(
            string Status,
            IReadOnlyList<Debugger.CallFrame>? CallFrames = default,
            bool? StackChanged = default,
            Runtime.StackTrace? AsyncStackTrace = default,
            Runtime.StackTraceId? AsyncStackTraceId = default,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Makes page not interrupt on any pauses (breakpoint, exception, dom exception etc).
        /// </summary>
        /// <param name="Skip">New value for skip pauses state.</param>
        public static Debugger.SetSkipAllPausesRequest SetSkipAllPauses(bool Skip)
        {
            return new Debugger.SetSkipAllPausesRequest(Skip);
        }
        /// <summary>
        /// Makes page not interrupt on any pauses (breakpoint, exception, dom exception etc).
        /// </summary>
        /// <param name="Skip">New value for skip pauses state.</param>
        [Core.MethodName("Debugger.setSkipAllPauses")]
        public record SetSkipAllPausesRequest(
            bool Skip
        ) : Core.ICommand<SetSkipAllPausesRequestResult>
        {
        }
        /// <summary>
        /// Makes page not interrupt on any pauses (breakpoint, exception, dom exception etc).
        /// </summary>
        public record SetSkipAllPausesRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Changes value of variable in a callframe. Object-based scopes are not supported and must be<br/>
        /// mutated manually.
        /// </summary>
        /// <param name="ScopeNumber">0-based number of scope as was listed in scope chain. Only &apos;local&apos;, &apos;closure&apos; and &apos;catch&apos;<br/>
        /// scope types are allowed. Other scopes could be manipulated manually.</param>
        /// <param name="VariableName">Variable name.</param>
        /// <param name="NewValue">New variable value.</param>
        /// <param name="CallFrameId">Id of callframe that holds variable.</param>
        public static Debugger.SetVariableValueRequest SetVariableValue(int ScopeNumber, string VariableName, Runtime.CallArgument NewValue, Debugger.CallFrameId CallFrameId)
        {
            return new Debugger.SetVariableValueRequest(ScopeNumber, VariableName, NewValue, CallFrameId);
        }
        /// <summary>
        /// Changes value of variable in a callframe. Object-based scopes are not supported and must be<br/>
        /// mutated manually.
        /// </summary>
        /// <param name="ScopeNumber">0-based number of scope as was listed in scope chain. Only &apos;local&apos;, &apos;closure&apos; and &apos;catch&apos;<br/>
        /// scope types are allowed. Other scopes could be manipulated manually.</param>
        /// <param name="VariableName">Variable name.</param>
        /// <param name="NewValue">New variable value.</param>
        /// <param name="CallFrameId">Id of callframe that holds variable.</param>
        [Core.MethodName("Debugger.setVariableValue")]
        public record SetVariableValueRequest(
            int ScopeNumber,
            string VariableName,
            Runtime.CallArgument NewValue,
            Debugger.CallFrameId CallFrameId
        ) : Core.ICommand<SetVariableValueRequestResult>
        {
        }
        /// <summary>
        /// Changes value of variable in a callframe. Object-based scopes are not supported and must be<br/>
        /// mutated manually.
        /// </summary>
        public record SetVariableValueRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Steps into the function call.
        /// </summary>
        /// <param name="BreakOnAsyncCall">Debugger will pause on the execution of the first async task which was scheduled<br/>
        /// before next pause.</param>
        /// <param name="SkipList">The skipList specifies location ranges that should be skipped on step into.</param>
        public static Debugger.StepIntoRequest StepInto(bool? BreakOnAsyncCall = default, IReadOnlyList<Debugger.LocationRange>? SkipList = default)
        {
            return new Debugger.StepIntoRequest(BreakOnAsyncCall, SkipList);
        }
        /// <summary>
        /// Steps into the function call.
        /// </summary>
        /// <param name="BreakOnAsyncCall">Debugger will pause on the execution of the first async task which was scheduled<br/>
        /// before next pause.</param>
        /// <param name="SkipList">The skipList specifies location ranges that should be skipped on step into.</param>
        [Core.MethodName("Debugger.stepInto")]
        public record StepIntoRequest(
            bool? BreakOnAsyncCall = default,
            IReadOnlyList<Debugger.LocationRange>? SkipList = default
        ) : Core.ICommand<StepIntoRequestResult>
        {
        }
        /// <summary>
        /// Steps into the function call.
        /// </summary>
        public record StepIntoRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Steps out of the function call.
        /// </summary>
        public static Debugger.StepOutRequest StepOut()
        {
            return new Debugger.StepOutRequest();
        }
        /// <summary>
        /// Steps out of the function call.
        /// </summary>
        [Core.MethodName("Debugger.stepOut")]
        public record StepOutRequest() : Core.ICommand<StepOutRequestResult>
        {
        }
        /// <summary>
        /// Steps out of the function call.
        /// </summary>
        public record StepOutRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Steps over the statement.
        /// </summary>
        /// <param name="SkipList">The skipList specifies location ranges that should be skipped on step over.</param>
        public static Debugger.StepOverRequest StepOver(IReadOnlyList<Debugger.LocationRange>? SkipList = default)
        {
            return new Debugger.StepOverRequest(SkipList);
        }
        /// <summary>
        /// Steps over the statement.
        /// </summary>
        /// <param name="SkipList">The skipList specifies location ranges that should be skipped on step over.</param>
        [Core.MethodName("Debugger.stepOver")]
        public record StepOverRequest(
            IReadOnlyList<Debugger.LocationRange>? SkipList = default
        ) : Core.ICommand<StepOverRequestResult>
        {
        }
        /// <summary>
        /// Steps over the statement.
        /// </summary>
        public record StepOverRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Fired when breakpoint is resolved to an actual script and location.<br/>
        /// Deprecated in favor of `resolvedBreakpoints` in the `scriptParsed` event.
        /// </summary>
        /// <param name="BreakpointId">Breakpoint unique identifier.</param>
        /// <param name="Location">Actual breakpoint location.</param>
        [Obsolete]
        [Core.MethodName("Debugger.breakpointResolved")]
        public record BreakpointResolved(
            Debugger.BreakpointId BreakpointId,
            Debugger.Location Location
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when the virtual machine stopped on breakpoint or exception or any other stop criteria.
        /// </summary>
        /// <param name="CallFrames">Call stack the virtual machine stopped on.</param>
        /// <param name="Reason">Pause reason.</param>
        /// <param name="Data">Object containing break-specific auxiliary properties.</param>
        /// <param name="HitBreakpoints">Hit breakpoints IDs</param>
        /// <param name="AsyncStackTrace">Async stack trace, if any.</param>
        /// <param name="AsyncStackTraceId">Async stack trace, if any.</param>
        /// <param name="AsyncCallStackTraceId">Never present, will be removed.</param>
        [Core.MethodName("Debugger.paused")]
        public record Paused(
            IReadOnlyList<Debugger.CallFrame> CallFrames,
            string Reason,
            JsonObject? Data = default,
            IReadOnlyList<string>? HitBreakpoints = default,
            Runtime.StackTrace? AsyncStackTrace = default,
            Runtime.StackTraceId? AsyncStackTraceId = default,
            Runtime.StackTraceId? AsyncCallStackTraceId = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when the virtual machine resumed execution.
        /// </summary>
        [Core.MethodName("Debugger.resumed")]
        public record Resumed(
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when virtual machine fails to parse the script.
        /// </summary>
        /// <param name="ScriptId">Identifier of the script parsed.</param>
        /// <param name="Url">URL or name of the script parsed (if any).</param>
        /// <param name="StartLine">Line offset of the script within the resource with given URL (for script tags).</param>
        /// <param name="StartColumn">Column offset of the script within the resource with given URL.</param>
        /// <param name="EndLine">Last line of the script.</param>
        /// <param name="EndColumn">Length of the last line of the script.</param>
        /// <param name="ExecutionContextId">Specifies script creation context.</param>
        /// <param name="Hash">Content hash of the script, SHA-256.</param>
        /// <param name="BuildId">For Wasm modules, the content of the `build_id` custom section. For JavaScript the `debugId` magic comment.</param>
        /// <param name="ExecutionContextAuxData">Embedder-specific auxiliary data likely matching {isDefault: boolean, type: &apos;default&apos;|&apos;isolated&apos;|&apos;worker&apos;, frameId: string}</param>
        /// <param name="SourceMapURL">URL of source map associated with script (if any).</param>
        /// <param name="HasSourceURL">True, if this script has sourceURL.</param>
        /// <param name="IsModule">True, if this script is ES6 module.</param>
        /// <param name="Length">This script length.</param>
        /// <param name="StackTrace">JavaScript top stack frame of where the script parsed event was triggered if available.</param>
        /// <param name="CodeOffset">If the scriptLanguage is WebAssembly, the code section offset in the module.</param>
        /// <param name="ScriptLanguage">The language of the script.</param>
        /// <param name="EmbedderName">The name the embedder supplied for this script.</param>
        [Core.MethodName("Debugger.scriptFailedToParse")]
        public record ScriptFailedToParse(
            Runtime.ScriptId ScriptId,
            string Url,
            int StartLine,
            int StartColumn,
            int EndLine,
            int EndColumn,
            Runtime.ExecutionContextId ExecutionContextId,
            string Hash,
            string BuildId,
            JsonObject? ExecutionContextAuxData = default,
            string? SourceMapURL = default,
            bool? HasSourceURL = default,
            bool? IsModule = default,
            int? Length = default,
            Runtime.StackTrace? StackTrace = default,
            int? CodeOffset = default,
            Debugger.ScriptLanguage? ScriptLanguage = default,
            string? EmbedderName = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when virtual machine parses script. This event is also fired for all known and uncollected<br/>
        /// scripts upon enabling debugger.
        /// </summary>
        /// <param name="ScriptId">Identifier of the script parsed.</param>
        /// <param name="Url">URL or name of the script parsed (if any).</param>
        /// <param name="StartLine">Line offset of the script within the resource with given URL (for script tags).</param>
        /// <param name="StartColumn">Column offset of the script within the resource with given URL.</param>
        /// <param name="EndLine">Last line of the script.</param>
        /// <param name="EndColumn">Length of the last line of the script.</param>
        /// <param name="ExecutionContextId">Specifies script creation context.</param>
        /// <param name="Hash">Content hash of the script, SHA-256.</param>
        /// <param name="BuildId">For Wasm modules, the content of the `build_id` custom section. For JavaScript the `debugId` magic comment.</param>
        /// <param name="ExecutionContextAuxData">Embedder-specific auxiliary data likely matching {isDefault: boolean, type: &apos;default&apos;|&apos;isolated&apos;|&apos;worker&apos;, frameId: string}</param>
        /// <param name="IsLiveEdit">True, if this script is generated as a result of the live edit operation.</param>
        /// <param name="SourceMapURL">URL of source map associated with script (if any).</param>
        /// <param name="HasSourceURL">True, if this script has sourceURL.</param>
        /// <param name="IsModule">True, if this script is ES6 module.</param>
        /// <param name="Length">This script length.</param>
        /// <param name="StackTrace">JavaScript top stack frame of where the script parsed event was triggered if available.</param>
        /// <param name="CodeOffset">If the scriptLanguage is WebAssembly, the code section offset in the module.</param>
        /// <param name="ScriptLanguage">The language of the script.</param>
        /// <param name="DebugSymbols">If the scriptLanguage is WebAssembly, the source of debug symbols for the module.</param>
        /// <param name="EmbedderName">The name the embedder supplied for this script.</param>
        /// <param name="ResolvedBreakpoints">The list of set breakpoints in this script if calls to `setBreakpointByUrl`<br/>
        /// matches this script&apos;s URL or hash. Clients that use this list can ignore the<br/>
        /// `breakpointResolved` event. They are equivalent.</param>
        [Core.MethodName("Debugger.scriptParsed")]
        public record ScriptParsed(
            Runtime.ScriptId ScriptId,
            string Url,
            int StartLine,
            int StartColumn,
            int EndLine,
            int EndColumn,
            Runtime.ExecutionContextId ExecutionContextId,
            string Hash,
            string BuildId,
            JsonObject? ExecutionContextAuxData = default,
            bool? IsLiveEdit = default,
            string? SourceMapURL = default,
            bool? HasSourceURL = default,
            bool? IsModule = default,
            int? Length = default,
            Runtime.StackTrace? StackTrace = default,
            int? CodeOffset = default,
            Debugger.ScriptLanguage? ScriptLanguage = default,
            IReadOnlyList<Debugger.DebugSymbols>? DebugSymbols = default,
            string? EmbedderName = default,
            IReadOnlyList<Debugger.ResolvedBreakpoint>? ResolvedBreakpoints = default
        ) : Core.IEvent
        {
        }
    }
}
