// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class DeviceOrientation
    {
        /// <summary>
        /// Clears the overridden Device Orientation.
        /// </summary>
        public static DeviceOrientation.ClearDeviceOrientationOverrideRequest ClearDeviceOrientationOverride()
        {
            return new DeviceOrientation.ClearDeviceOrientationOverrideRequest();
        }
        /// <summary>
        /// Clears the overridden Device Orientation.
        /// </summary>
        [Core.MethodName("DeviceOrientation.clearDeviceOrientationOverride")]
        public record ClearDeviceOrientationOverrideRequest() : Core.ICommand<ClearDeviceOrientationOverrideRequestResult>
        {
        }
        /// <summary>
        /// Clears the overridden Device Orientation.
        /// </summary>
        public record ClearDeviceOrientationOverrideRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Overrides the Device Orientation.
        /// </summary>
        /// <param name="Alpha">Mock alpha</param>
        /// <param name="Beta">Mock beta</param>
        /// <param name="Gamma">Mock gamma</param>
        public static DeviceOrientation.SetDeviceOrientationOverrideRequest SetDeviceOrientationOverride(double Alpha, double Beta, double Gamma)
        {
            return new DeviceOrientation.SetDeviceOrientationOverrideRequest(Alpha, Beta, Gamma);
        }
        /// <summary>
        /// Overrides the Device Orientation.
        /// </summary>
        /// <param name="Alpha">Mock alpha</param>
        /// <param name="Beta">Mock beta</param>
        /// <param name="Gamma">Mock gamma</param>
        [Core.MethodName("DeviceOrientation.setDeviceOrientationOverride")]
        public record SetDeviceOrientationOverrideRequest(
            double Alpha,
            double Beta,
            double Gamma
        ) : Core.ICommand<SetDeviceOrientationOverrideRequestResult>
        {
        }
        /// <summary>
        /// Overrides the Device Orientation.
        /// </summary>
        public record SetDeviceOrientationOverrideRequestResult() : Core.IType
        {
        }
    }
}
