// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class DOM
    {
        /// <summary>
        /// Unique DOM node identifier.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record NodeId(
            int Value
        ) : Core.PrimitiveType<int>(Value)
        {
        }
        /// <summary>
        /// Unique DOM node identifier used to reference a node that may not have been pushed to the<br/>
        /// front-end.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record BackendNodeId(
            int Value
        ) : Core.PrimitiveType<int>(Value)
        {
        }
        /// <summary>
        /// Unique identifier for a CSS stylesheet.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record StyleSheetId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Backend node with a friendly name.
        /// </summary>
        /// <param name="NodeType">`Node`&apos;s nodeType.</param>
        /// <param name="NodeName">`Node`&apos;s nodeName.</param>
        public record BackendNode(
            int NodeType,
            string NodeName,
            DOM.BackendNodeId BackendNodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Pseudo element type.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record PseudoType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly PseudoType FIRST_LINE = new("first-line");
            public static readonly PseudoType FIRST_LETTER = new("first-letter");
            public static readonly PseudoType CHECKMARK = new("checkmark");
            public static readonly PseudoType BEFORE = new("before");
            public static readonly PseudoType AFTER = new("after");
            public static readonly PseudoType PICKER_ICON = new("picker-icon");
            public static readonly PseudoType INTEREST_HINT = new("interest-hint");
            public static readonly PseudoType MARKER = new("marker");
            public static readonly PseudoType BACKDROP = new("backdrop");
            public static readonly PseudoType COLUMN = new("column");
            public static readonly PseudoType SELECTION = new("selection");
            public static readonly PseudoType SEARCH_TEXT = new("search-text");
            public static readonly PseudoType TARGET_TEXT = new("target-text");
            public static readonly PseudoType SPELLING_ERROR = new("spelling-error");
            public static readonly PseudoType GRAMMAR_ERROR = new("grammar-error");
            public static readonly PseudoType HIGHLIGHT = new("highlight");
            public static readonly PseudoType FIRST_LINE_INHERITED = new("first-line-inherited");
            public static readonly PseudoType SCROLL_MARKER = new("scroll-marker");
            public static readonly PseudoType SCROLL_MARKER_GROUP = new("scroll-marker-group");
            public static readonly PseudoType SCROLL_BUTTON = new("scroll-button");
            public static readonly PseudoType SCROLLBAR = new("scrollbar");
            public static readonly PseudoType SCROLLBAR_THUMB = new("scrollbar-thumb");
            public static readonly PseudoType SCROLLBAR_BUTTON = new("scrollbar-button");
            public static readonly PseudoType SCROLLBAR_TRACK = new("scrollbar-track");
            public static readonly PseudoType SCROLLBAR_TRACK_PIECE = new("scrollbar-track-piece");
            public static readonly PseudoType SCROLLBAR_CORNER = new("scrollbar-corner");
            public static readonly PseudoType RESIZER = new("resizer");
            public static readonly PseudoType INPUT_LIST_BUTTON = new("input-list-button");
            public static readonly PseudoType VIEW_TRANSITION = new("view-transition");
            public static readonly PseudoType VIEW_TRANSITION_GROUP = new("view-transition-group");
            public static readonly PseudoType VIEW_TRANSITION_IMAGE_PAIR = new("view-transition-image-pair");
            public static readonly PseudoType VIEW_TRANSITION_GROUP_CHILDREN = new("view-transition-group-children");
            public static readonly PseudoType VIEW_TRANSITION_OLD = new("view-transition-old");
            public static readonly PseudoType VIEW_TRANSITION_NEW = new("view-transition-new");
            public static readonly PseudoType PLACEHOLDER = new("placeholder");
            public static readonly PseudoType FILE_SELECTOR_BUTTON = new("file-selector-button");
            public static readonly PseudoType DETAILS_CONTENT = new("details-content");
            public static readonly PseudoType PICKER = new("picker");
            public static readonly PseudoType PERMISSION_ICON = new("permission-icon");
            public static readonly PseudoType OVERSCROLL_AREA_PARENT = new("overscroll-area-parent");
        }
        /// <summary>
        /// Shadow root type.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ShadowRootType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly ShadowRootType USER_AGENT = new("user-agent");
            public static readonly ShadowRootType OPEN = new("open");
            public static readonly ShadowRootType CLOSED = new("closed");
        }
        /// <summary>
        /// Document compatibility mode.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record CompatibilityMode(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly CompatibilityMode QUIRKS_MODE = new("QuirksMode");
            public static readonly CompatibilityMode LIMITED_QUIRKS_MODE = new("LimitedQuirksMode");
            public static readonly CompatibilityMode NO_QUIRKS_MODE = new("NoQuirksMode");
        }
        /// <summary>
        /// ContainerSelector physical axes
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record PhysicalAxes(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly PhysicalAxes HORIZONTAL = new("Horizontal");
            public static readonly PhysicalAxes VERTICAL = new("Vertical");
            public static readonly PhysicalAxes BOTH = new("Both");
        }
        /// <summary>
        /// ContainerSelector logical axes
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record LogicalAxes(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly LogicalAxes INLINE = new("Inline");
            public static readonly LogicalAxes BLOCK = new("Block");
            public static readonly LogicalAxes BOTH = new("Both");
        }
        /// <summary>
        /// Physical scroll orientation
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ScrollOrientation(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly ScrollOrientation HORIZONTAL = new("horizontal");
            public static readonly ScrollOrientation VERTICAL = new("vertical");
        }
        /// <summary>
        /// DOM interaction is implemented in terms of mirror objects that represent the actual DOM nodes.<br/>
        /// DOMNode is a base node mirror type.
        /// </summary>
        /// <param name="NodeId">Node identifier that is passed into the rest of the DOM messages as the `nodeId`. Backend<br/>
        /// will only push node with given `id` once. It is aware of all requested nodes and will only<br/>
        /// fire DOM events for nodes known to the client.</param>
        /// <param name="BackendNodeId">The BackendNodeId for this node.</param>
        /// <param name="NodeType">`Node`&apos;s nodeType.</param>
        /// <param name="NodeName">`Node`&apos;s nodeName.</param>
        /// <param name="LocalName">`Node`&apos;s localName.</param>
        /// <param name="NodeValue">`Node`&apos;s nodeValue.</param>
        /// <param name="ParentId">The id of the parent node if any.</param>
        /// <param name="ChildNodeCount">Child count for `Container` nodes.</param>
        /// <param name="Children">Child nodes of this node when requested with children.</param>
        /// <param name="Attributes">Attributes of the `Element` node in the form of flat array `[name1, value1, name2, value2]`.</param>
        /// <param name="DocumentURL">Document URL that `Document` or `FrameOwner` node points to.</param>
        /// <param name="BaseURL">Base URL that `Document` or `FrameOwner` node uses for URL completion.</param>
        /// <param name="PublicId">`DocumentType`&apos;s publicId.</param>
        /// <param name="SystemId">`DocumentType`&apos;s systemId.</param>
        /// <param name="InternalSubset">`DocumentType`&apos;s internalSubset.</param>
        /// <param name="XmlVersion">`Document`&apos;s XML version in case of XML documents.</param>
        /// <param name="Name">`Attr`&apos;s name.</param>
        /// <param name="Value">`Attr`&apos;s value.</param>
        /// <param name="PseudoType">Pseudo element type for this node.</param>
        /// <param name="PseudoIdentifier">Pseudo element identifier for this node. Only present if there is a<br/>
        /// valid pseudoType.</param>
        /// <param name="ShadowRootType">Shadow root type.</param>
        /// <param name="FrameId">Frame ID for frame owner elements.</param>
        /// <param name="ContentDocument">Content document for frame owner elements.</param>
        /// <param name="ShadowRoots">Shadow root list for given element host.</param>
        /// <param name="TemplateContent">Content document fragment for template elements.</param>
        /// <param name="PseudoElements">Pseudo elements associated with this node.</param>
        /// <param name="ImportedDocument">Deprecated, as the HTML Imports API has been removed (crbug.com/937746).<br/>
        /// This property used to return the imported document for the HTMLImport links.<br/>
        /// The property is always undefined now.</param>
        /// <param name="DistributedNodes">Distributed nodes for given insertion point.</param>
        /// <param name="IsSVG">Whether the node is SVG.</param>
        public record Node(
            DOM.NodeId NodeId,
            DOM.BackendNodeId BackendNodeId,
            int NodeType,
            string NodeName,
            string LocalName,
            string NodeValue,
            DOM.NodeId? ParentId = default,
            int? ChildNodeCount = default,
            IReadOnlyList<DOM.Node>? Children = default,
            IReadOnlyList<string>? Attributes = default,
            string? DocumentURL = default,
            string? BaseURL = default,
            string? PublicId = default,
            string? SystemId = default,
            string? InternalSubset = default,
            string? XmlVersion = default,
            string? Name = default,
            string? Value = default,
            DOM.PseudoType? PseudoType = default,
            string? PseudoIdentifier = default,
            DOM.ShadowRootType? ShadowRootType = default,
            Page.FrameId? FrameId = default,
            DOM.Node? ContentDocument = default,
            IReadOnlyList<DOM.Node>? ShadowRoots = default,
            DOM.Node? TemplateContent = default,
            IReadOnlyList<DOM.Node>? PseudoElements = default,
            DOM.Node? ImportedDocument = default,
            IReadOnlyList<DOM.BackendNode>? DistributedNodes = default,
            bool? IsSVG = default,
            DOM.CompatibilityMode? CompatibilityMode = default,
            DOM.BackendNode? AssignedSlot = default,
            bool? IsScrollable = default,
            bool? AffectedByStartingStyles = default,
            IReadOnlyList<DOM.StyleSheetId>? AdoptedStyleSheets = default,
            bool? IsAdRelated = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// A structure to hold the top-level node of a detached tree and an array of its retained descendants.
        /// </summary>
        public record DetachedElementInfo(
            DOM.Node TreeNode,
            IReadOnlyList<DOM.NodeId> RetainedNodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// A structure holding an RGBA color.
        /// </summary>
        /// <param name="R">The red component, in the [0-255] range.</param>
        /// <param name="G">The green component, in the [0-255] range.</param>
        /// <param name="B">The blue component, in the [0-255] range.</param>
        /// <param name="A">The alpha component, in the [0-1] range (default: 1).</param>
        public record RGBA(
            int R,
            int G,
            int B,
            double? A = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// An array of quad vertices, x immediately followed by y for each point, points clock-wise.
        /// </summary>
        [JsonConverter(typeof(Core.ArrayTypeConverter))]
        public record Quad(
            IReadOnlyList<double> Items
        ) : Core.ArrayType<double>(Items)
        {
        }
        /// <summary>
        /// Box model.
        /// </summary>
        /// <param name="Content">Content box</param>
        /// <param name="Padding">Padding box</param>
        /// <param name="Border">Border box</param>
        /// <param name="Margin">Margin box</param>
        /// <param name="Width">Node width</param>
        /// <param name="Height">Node height</param>
        /// <param name="ShapeOutside">Shape outside coordinates</param>
        public record BoxModel(
            DOM.Quad Content,
            DOM.Quad Padding,
            DOM.Quad Border,
            DOM.Quad Margin,
            int Width,
            int Height,
            DOM.ShapeOutsideInfo? ShapeOutside = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// CSS Shape Outside details.
        /// </summary>
        /// <param name="Bounds">Shape bounds</param>
        /// <param name="Shape">Shape coordinate details</param>
        /// <param name="MarginShape">Margin shape bounds</param>
        public record ShapeOutsideInfo(
            DOM.Quad Bounds,
            IReadOnlyList<JsonNode> Shape,
            IReadOnlyList<JsonNode> MarginShape
        ) : Core.IType
        {
        }
        /// <summary>
        /// Rectangle.
        /// </summary>
        /// <param name="X">X coordinate</param>
        /// <param name="Y">Y coordinate</param>
        /// <param name="Width">Rectangle width</param>
        /// <param name="Height">Rectangle height</param>
        public record Rect(
            double X,
            double Y,
            double Width,
            double Height
        ) : Core.IType
        {
        }
        /// <param name="Name">Computed style property name.</param>
        /// <param name="Value">Computed style property value.</param>
        public record CSSComputedStyleProperty(
            string Name,
            string Value
        ) : Core.IType
        {
        }
        /// <summary>
        /// Collects class names for the node with given id and all of it&apos;s child nodes.
        /// </summary>
        /// <param name="NodeId">Id of the node to collect class names.</param>
        public static DOM.CollectClassNamesFromSubtreeRequest CollectClassNamesFromSubtree(DOM.NodeId NodeId)
        {
            return new DOM.CollectClassNamesFromSubtreeRequest(NodeId);
        }
        /// <summary>
        /// Collects class names for the node with given id and all of it&apos;s child nodes.
        /// </summary>
        /// <param name="NodeId">Id of the node to collect class names.</param>
        [Core.MethodName("DOM.collectClassNamesFromSubtree")]
        public record CollectClassNamesFromSubtreeRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<CollectClassNamesFromSubtreeRequestResult>
        {
        }
        /// <summary>
        /// Collects class names for the node with given id and all of it&apos;s child nodes.
        /// </summary>
        /// <param name="ClassNames">Class name list.</param>
        public record CollectClassNamesFromSubtreeRequestResult(
            IReadOnlyList<string> ClassNames
        ) : Core.IType
        {
        }
        /// <summary>
        /// Creates a deep copy of the specified node and places it into the target container before the<br/>
        /// given anchor.
        /// </summary>
        /// <param name="NodeId">Id of the node to copy.</param>
        /// <param name="TargetNodeId">Id of the element to drop the copy into.</param>
        /// <param name="InsertBeforeNodeId">Drop the copy before this node (if absent, the copy becomes the last child of<br/>
        /// `targetNodeId`).</param>
        public static DOM.CopyToRequest CopyTo(DOM.NodeId NodeId, DOM.NodeId TargetNodeId, DOM.NodeId? InsertBeforeNodeId = default)
        {
            return new DOM.CopyToRequest(NodeId, TargetNodeId, InsertBeforeNodeId);
        }
        /// <summary>
        /// Creates a deep copy of the specified node and places it into the target container before the<br/>
        /// given anchor.
        /// </summary>
        /// <param name="NodeId">Id of the node to copy.</param>
        /// <param name="TargetNodeId">Id of the element to drop the copy into.</param>
        /// <param name="InsertBeforeNodeId">Drop the copy before this node (if absent, the copy becomes the last child of<br/>
        /// `targetNodeId`).</param>
        [Core.MethodName("DOM.copyTo")]
        public record CopyToRequest(
            DOM.NodeId NodeId,
            DOM.NodeId TargetNodeId,
            DOM.NodeId? InsertBeforeNodeId = default
        ) : Core.ICommand<CopyToRequestResult>
        {
        }
        /// <summary>
        /// Creates a deep copy of the specified node and places it into the target container before the<br/>
        /// given anchor.
        /// </summary>
        /// <param name="NodeId">Id of the node clone.</param>
        public record CopyToRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Describes node given its id, does not require domain to be enabled. Does not start tracking any<br/>
        /// objects, can be used for automation.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false).</param>
        public static DOM.DescribeNodeRequest DescribeNode(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default, int? Depth = default, bool? Pierce = default)
        {
            return new DOM.DescribeNodeRequest(NodeId, BackendNodeId, ObjectId, Depth, Pierce);
        }
        /// <summary>
        /// Describes node given its id, does not require domain to be enabled. Does not start tracking any<br/>
        /// objects, can be used for automation.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false).</param>
        [Core.MethodName("DOM.describeNode")]
        public record DescribeNodeRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default,
            int? Depth = default,
            bool? Pierce = default
        ) : Core.ICommand<DescribeNodeRequestResult>
        {
        }
        /// <summary>
        /// Describes node given its id, does not require domain to be enabled. Does not start tracking any<br/>
        /// objects, can be used for automation.
        /// </summary>
        /// <param name="Node">Node description.</param>
        public record DescribeNodeRequestResult(
            DOM.Node Node
        ) : Core.IType
        {
        }
        /// <summary>
        /// Scrolls the specified rect of the given node into view if not already visible.<br/>
        /// Note: exactly one between nodeId, backendNodeId and objectId should be passed<br/>
        /// to identify the node.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        /// <param name="Rect">The rect to be scrolled into view, relative to the node&apos;s border box, in CSS pixels.<br/>
        /// When omitted, center of the node will be used, similar to Element.scrollIntoView.</param>
        public static DOM.ScrollIntoViewIfNeededRequest ScrollIntoViewIfNeeded(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default, DOM.Rect? Rect = default)
        {
            return new DOM.ScrollIntoViewIfNeededRequest(NodeId, BackendNodeId, ObjectId, Rect);
        }
        /// <summary>
        /// Scrolls the specified rect of the given node into view if not already visible.<br/>
        /// Note: exactly one between nodeId, backendNodeId and objectId should be passed<br/>
        /// to identify the node.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        /// <param name="Rect">The rect to be scrolled into view, relative to the node&apos;s border box, in CSS pixels.<br/>
        /// When omitted, center of the node will be used, similar to Element.scrollIntoView.</param>
        [Core.MethodName("DOM.scrollIntoViewIfNeeded")]
        public record ScrollIntoViewIfNeededRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default,
            DOM.Rect? Rect = default
        ) : Core.ICommand<ScrollIntoViewIfNeededRequestResult>
        {
        }
        /// <summary>
        /// Scrolls the specified rect of the given node into view if not already visible.<br/>
        /// Note: exactly one between nodeId, backendNodeId and objectId should be passed<br/>
        /// to identify the node.
        /// </summary>
        public record ScrollIntoViewIfNeededRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Disables DOM agent for the given page.
        /// </summary>
        public static DOM.DisableRequest Disable()
        {
            return new DOM.DisableRequest();
        }
        /// <summary>
        /// Disables DOM agent for the given page.
        /// </summary>
        [Core.MethodName("DOM.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Disables DOM agent for the given page.
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Discards search results from the session with the given id. `getSearchResults` should no longer<br/>
        /// be called for that search.
        /// </summary>
        /// <param name="SearchId">Unique search session identifier.</param>
        public static DOM.DiscardSearchResultsRequest DiscardSearchResults(string SearchId)
        {
            return new DOM.DiscardSearchResultsRequest(SearchId);
        }
        /// <summary>
        /// Discards search results from the session with the given id. `getSearchResults` should no longer<br/>
        /// be called for that search.
        /// </summary>
        /// <param name="SearchId">Unique search session identifier.</param>
        [Core.MethodName("DOM.discardSearchResults")]
        public record DiscardSearchResultsRequest(
            string SearchId
        ) : Core.ICommand<DiscardSearchResultsRequestResult>
        {
        }
        /// <summary>
        /// Discards search results from the session with the given id. `getSearchResults` should no longer<br/>
        /// be called for that search.
        /// </summary>
        public record DiscardSearchResultsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables DOM agent for the given page.
        /// </summary>
        /// <param name="IncludeWhitespace">Whether to include whitespaces in the children array of returned Nodes.</param>
        public static DOM.EnableRequest Enable(string? IncludeWhitespace = default)
        {
            return new DOM.EnableRequest(IncludeWhitespace);
        }
        /// <summary>
        /// Enables DOM agent for the given page.
        /// </summary>
        /// <param name="IncludeWhitespace">Whether to include whitespaces in the children array of returned Nodes.</param>
        [Core.MethodName("DOM.enable")]
        public record EnableRequest(
            string? IncludeWhitespace = default
        ) : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables DOM agent for the given page.
        /// </summary>
        public record EnableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Focuses the given element.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        public static DOM.FocusRequest Focus(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default)
        {
            return new DOM.FocusRequest(NodeId, BackendNodeId, ObjectId);
        }
        /// <summary>
        /// Focuses the given element.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        [Core.MethodName("DOM.focus")]
        public record FocusRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default
        ) : Core.ICommand<FocusRequestResult>
        {
        }
        /// <summary>
        /// Focuses the given element.
        /// </summary>
        public record FocusRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Returns attributes for the specified node.
        /// </summary>
        /// <param name="NodeId">Id of the node to retrieve attributes for.</param>
        public static DOM.GetAttributesRequest GetAttributes(DOM.NodeId NodeId)
        {
            return new DOM.GetAttributesRequest(NodeId);
        }
        /// <summary>
        /// Returns attributes for the specified node.
        /// </summary>
        /// <param name="NodeId">Id of the node to retrieve attributes for.</param>
        [Core.MethodName("DOM.getAttributes")]
        public record GetAttributesRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<GetAttributesRequestResult>
        {
        }
        /// <summary>
        /// Returns attributes for the specified node.
        /// </summary>
        /// <param name="Attributes">An interleaved array of node attribute names and values.</param>
        public record GetAttributesRequestResult(
            IReadOnlyList<string> Attributes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns boxes for the given node.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        public static DOM.GetBoxModelRequest GetBoxModel(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default)
        {
            return new DOM.GetBoxModelRequest(NodeId, BackendNodeId, ObjectId);
        }
        /// <summary>
        /// Returns boxes for the given node.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        [Core.MethodName("DOM.getBoxModel")]
        public record GetBoxModelRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default
        ) : Core.ICommand<GetBoxModelRequestResult>
        {
        }
        /// <summary>
        /// Returns boxes for the given node.
        /// </summary>
        /// <param name="Model">Box model for the node.</param>
        public record GetBoxModelRequestResult(
            DOM.BoxModel Model
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns quads that describe node position on the page. This method<br/>
        /// might return multiple quads for inline nodes.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        public static DOM.GetContentQuadsRequest GetContentQuads(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default)
        {
            return new DOM.GetContentQuadsRequest(NodeId, BackendNodeId, ObjectId);
        }
        /// <summary>
        /// Returns quads that describe node position on the page. This method<br/>
        /// might return multiple quads for inline nodes.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        [Core.MethodName("DOM.getContentQuads")]
        public record GetContentQuadsRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default
        ) : Core.ICommand<GetContentQuadsRequestResult>
        {
        }
        /// <summary>
        /// Returns quads that describe node position on the page. This method<br/>
        /// might return multiple quads for inline nodes.
        /// </summary>
        /// <param name="Quads">Quads that describe node layout relative to viewport.</param>
        public record GetContentQuadsRequestResult(
            IReadOnlyList<DOM.Quad> Quads
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the root DOM node (and optionally the subtree) to the caller.<br/>
        /// Implicitly enables the DOM domain events for the current target.
        /// </summary>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false).</param>
        public static DOM.GetDocumentRequest GetDocument(int? Depth = default, bool? Pierce = default)
        {
            return new DOM.GetDocumentRequest(Depth, Pierce);
        }
        /// <summary>
        /// Returns the root DOM node (and optionally the subtree) to the caller.<br/>
        /// Implicitly enables the DOM domain events for the current target.
        /// </summary>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false).</param>
        [Core.MethodName("DOM.getDocument")]
        public record GetDocumentRequest(
            int? Depth = default,
            bool? Pierce = default
        ) : Core.ICommand<GetDocumentRequestResult>
        {
        }
        /// <summary>
        /// Returns the root DOM node (and optionally the subtree) to the caller.<br/>
        /// Implicitly enables the DOM domain events for the current target.
        /// </summary>
        /// <param name="Root">Resulting node.</param>
        public record GetDocumentRequestResult(
            DOM.Node Root
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the root DOM node (and optionally the subtree) to the caller.<br/>
        /// Deprecated, as it is not designed to work well with the rest of the DOM agent.<br/>
        /// Use DOMSnapshot.captureSnapshot instead.
        /// </summary>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false).</param>
        [Obsolete]
        public static DOM.GetFlattenedDocumentRequest GetFlattenedDocument(int? Depth = default, bool? Pierce = default)
        {
            return new DOM.GetFlattenedDocumentRequest(Depth, Pierce);
        }
        /// <summary>
        /// Returns the root DOM node (and optionally the subtree) to the caller.<br/>
        /// Deprecated, as it is not designed to work well with the rest of the DOM agent.<br/>
        /// Use DOMSnapshot.captureSnapshot instead.
        /// </summary>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false).</param>
        [Obsolete]
        [Core.MethodName("DOM.getFlattenedDocument")]
        public record GetFlattenedDocumentRequest(
            int? Depth = default,
            bool? Pierce = default
        ) : Core.ICommand<GetFlattenedDocumentRequestResult>
        {
        }
        /// <summary>
        /// Returns the root DOM node (and optionally the subtree) to the caller.<br/>
        /// Deprecated, as it is not designed to work well with the rest of the DOM agent.<br/>
        /// Use DOMSnapshot.captureSnapshot instead.
        /// </summary>
        /// <param name="Nodes">Resulting node.</param>
        [Obsolete]
        public record GetFlattenedDocumentRequestResult(
            IReadOnlyList<DOM.Node> Nodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Finds nodes with a given computed style in a subtree.
        /// </summary>
        /// <param name="NodeId">Node ID pointing to the root of a subtree.</param>
        /// <param name="ComputedStyles">The style to filter nodes by (includes nodes if any of properties matches).</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots in the same target should be traversed when returning the<br/>
        /// results (default is false).</param>
        public static DOM.GetNodesForSubtreeByStyleRequest GetNodesForSubtreeByStyle(DOM.NodeId NodeId, IReadOnlyList<DOM.CSSComputedStyleProperty> ComputedStyles, bool? Pierce = default)
        {
            return new DOM.GetNodesForSubtreeByStyleRequest(NodeId, ComputedStyles, Pierce);
        }
        /// <summary>
        /// Finds nodes with a given computed style in a subtree.
        /// </summary>
        /// <param name="NodeId">Node ID pointing to the root of a subtree.</param>
        /// <param name="ComputedStyles">The style to filter nodes by (includes nodes if any of properties matches).</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots in the same target should be traversed when returning the<br/>
        /// results (default is false).</param>
        [Core.MethodName("DOM.getNodesForSubtreeByStyle")]
        public record GetNodesForSubtreeByStyleRequest(
            DOM.NodeId NodeId,
            IReadOnlyList<DOM.CSSComputedStyleProperty> ComputedStyles,
            bool? Pierce = default
        ) : Core.ICommand<GetNodesForSubtreeByStyleRequestResult>
        {
        }
        /// <summary>
        /// Finds nodes with a given computed style in a subtree.
        /// </summary>
        /// <param name="NodeIds">Resulting nodes.</param>
        public record GetNodesForSubtreeByStyleRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is<br/>
        /// either returned or not.
        /// </summary>
        /// <param name="X">X coordinate.</param>
        /// <param name="Y">Y coordinate.</param>
        /// <param name="IncludeUserAgentShadowDOM">False to skip to the nearest non-UA shadow root ancestor (default: false).</param>
        /// <param name="IgnorePointerEventsNone">Whether to ignore pointer-events: none on elements and hit test them.</param>
        public static DOM.GetNodeForLocationRequest GetNodeForLocation(int X, int Y, bool? IncludeUserAgentShadowDOM = default, bool? IgnorePointerEventsNone = default)
        {
            return new DOM.GetNodeForLocationRequest(X, Y, IncludeUserAgentShadowDOM, IgnorePointerEventsNone);
        }
        /// <summary>
        /// Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is<br/>
        /// either returned or not.
        /// </summary>
        /// <param name="X">X coordinate.</param>
        /// <param name="Y">Y coordinate.</param>
        /// <param name="IncludeUserAgentShadowDOM">False to skip to the nearest non-UA shadow root ancestor (default: false).</param>
        /// <param name="IgnorePointerEventsNone">Whether to ignore pointer-events: none on elements and hit test them.</param>
        [Core.MethodName("DOM.getNodeForLocation")]
        public record GetNodeForLocationRequest(
            int X,
            int Y,
            bool? IncludeUserAgentShadowDOM = default,
            bool? IgnorePointerEventsNone = default
        ) : Core.ICommand<GetNodeForLocationRequestResult>
        {
        }
        /// <summary>
        /// Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is<br/>
        /// either returned or not.
        /// </summary>
        /// <param name="BackendNodeId">Resulting node.</param>
        /// <param name="FrameId">Frame this node belongs to.</param>
        /// <param name="NodeId">Id of the node at given coordinates, only when enabled and requested document.</param>
        public record GetNodeForLocationRequestResult(
            DOM.BackendNodeId BackendNodeId,
            Page.FrameId FrameId,
            DOM.NodeId? NodeId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns node&apos;s HTML markup.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        /// <param name="IncludeShadowDOM">Include all shadow roots. Equals to false if not specified.</param>
        public static DOM.GetOuterHTMLRequest GetOuterHTML(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default, bool? IncludeShadowDOM = default)
        {
            return new DOM.GetOuterHTMLRequest(NodeId, BackendNodeId, ObjectId, IncludeShadowDOM);
        }
        /// <summary>
        /// Returns node&apos;s HTML markup.
        /// </summary>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        /// <param name="IncludeShadowDOM">Include all shadow roots. Equals to false if not specified.</param>
        [Core.MethodName("DOM.getOuterHTML")]
        public record GetOuterHTMLRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default,
            bool? IncludeShadowDOM = default
        ) : Core.ICommand<GetOuterHTMLRequestResult>
        {
        }
        /// <summary>
        /// Returns node&apos;s HTML markup.
        /// </summary>
        /// <param name="OuterHTML">Outer HTML markup.</param>
        public record GetOuterHTMLRequestResult(
            string OuterHTML
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the id of the nearest ancestor that is a relayout boundary.
        /// </summary>
        /// <param name="NodeId">Id of the node.</param>
        public static DOM.GetRelayoutBoundaryRequest GetRelayoutBoundary(DOM.NodeId NodeId)
        {
            return new DOM.GetRelayoutBoundaryRequest(NodeId);
        }
        /// <summary>
        /// Returns the id of the nearest ancestor that is a relayout boundary.
        /// </summary>
        /// <param name="NodeId">Id of the node.</param>
        [Core.MethodName("DOM.getRelayoutBoundary")]
        public record GetRelayoutBoundaryRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<GetRelayoutBoundaryRequestResult>
        {
        }
        /// <summary>
        /// Returns the id of the nearest ancestor that is a relayout boundary.
        /// </summary>
        /// <param name="NodeId">Relayout boundary node id for the given node.</param>
        public record GetRelayoutBoundaryRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns search results from given `fromIndex` to given `toIndex` from the search with the given<br/>
        /// identifier.
        /// </summary>
        /// <param name="SearchId">Unique search session identifier.</param>
        /// <param name="FromIndex">Start index of the search result to be returned.</param>
        /// <param name="ToIndex">End index of the search result to be returned.</param>
        public static DOM.GetSearchResultsRequest GetSearchResults(string SearchId, int FromIndex, int ToIndex)
        {
            return new DOM.GetSearchResultsRequest(SearchId, FromIndex, ToIndex);
        }
        /// <summary>
        /// Returns search results from given `fromIndex` to given `toIndex` from the search with the given<br/>
        /// identifier.
        /// </summary>
        /// <param name="SearchId">Unique search session identifier.</param>
        /// <param name="FromIndex">Start index of the search result to be returned.</param>
        /// <param name="ToIndex">End index of the search result to be returned.</param>
        [Core.MethodName("DOM.getSearchResults")]
        public record GetSearchResultsRequest(
            string SearchId,
            int FromIndex,
            int ToIndex
        ) : Core.ICommand<GetSearchResultsRequestResult>
        {
        }
        /// <summary>
        /// Returns search results from given `fromIndex` to given `toIndex` from the search with the given<br/>
        /// identifier.
        /// </summary>
        /// <param name="NodeIds">Ids of the search result nodes.</param>
        public record GetSearchResultsRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Hides any highlight.
        /// </summary>
        public static DOM.HideHighlightRequest HideHighlight()
        {
            return new DOM.HideHighlightRequest();
        }
        /// <summary>
        /// Hides any highlight.
        /// </summary>
        [Core.MethodName("DOM.hideHighlight")]
        public record HideHighlightRequest() : Core.ICommand<HideHighlightRequestResult>
        {
        }
        /// <summary>
        /// Hides any highlight.
        /// </summary>
        public record HideHighlightRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Highlights DOM node.
        /// </summary>
        public static DOM.HighlightNodeRequest HighlightNode()
        {
            return new DOM.HighlightNodeRequest();
        }
        /// <summary>
        /// Highlights DOM node.
        /// </summary>
        [Core.MethodName("DOM.highlightNode")]
        public record HighlightNodeRequest() : Core.ICommand<HighlightNodeRequestResult>
        {
        }
        /// <summary>
        /// Highlights DOM node.
        /// </summary>
        public record HighlightNodeRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Highlights given rectangle.
        /// </summary>
        public static DOM.HighlightRectRequest HighlightRect()
        {
            return new DOM.HighlightRectRequest();
        }
        /// <summary>
        /// Highlights given rectangle.
        /// </summary>
        [Core.MethodName("DOM.highlightRect")]
        public record HighlightRectRequest() : Core.ICommand<HighlightRectRequestResult>
        {
        }
        /// <summary>
        /// Highlights given rectangle.
        /// </summary>
        public record HighlightRectRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Marks last undoable state.
        /// </summary>
        public static DOM.MarkUndoableStateRequest MarkUndoableState()
        {
            return new DOM.MarkUndoableStateRequest();
        }
        /// <summary>
        /// Marks last undoable state.
        /// </summary>
        [Core.MethodName("DOM.markUndoableState")]
        public record MarkUndoableStateRequest() : Core.ICommand<MarkUndoableStateRequestResult>
        {
        }
        /// <summary>
        /// Marks last undoable state.
        /// </summary>
        public record MarkUndoableStateRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Moves node into the new container, places it before the given anchor.
        /// </summary>
        /// <param name="NodeId">Id of the node to move.</param>
        /// <param name="TargetNodeId">Id of the element to drop the moved node into.</param>
        /// <param name="InsertBeforeNodeId">Drop node before this one (if absent, the moved node becomes the last child of<br/>
        /// `targetNodeId`).</param>
        public static DOM.MoveToRequest MoveTo(DOM.NodeId NodeId, DOM.NodeId TargetNodeId, DOM.NodeId? InsertBeforeNodeId = default)
        {
            return new DOM.MoveToRequest(NodeId, TargetNodeId, InsertBeforeNodeId);
        }
        /// <summary>
        /// Moves node into the new container, places it before the given anchor.
        /// </summary>
        /// <param name="NodeId">Id of the node to move.</param>
        /// <param name="TargetNodeId">Id of the element to drop the moved node into.</param>
        /// <param name="InsertBeforeNodeId">Drop node before this one (if absent, the moved node becomes the last child of<br/>
        /// `targetNodeId`).</param>
        [Core.MethodName("DOM.moveTo")]
        public record MoveToRequest(
            DOM.NodeId NodeId,
            DOM.NodeId TargetNodeId,
            DOM.NodeId? InsertBeforeNodeId = default
        ) : Core.ICommand<MoveToRequestResult>
        {
        }
        /// <summary>
        /// Moves node into the new container, places it before the given anchor.
        /// </summary>
        /// <param name="NodeId">New id of the moved node.</param>
        public record MoveToRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or<br/>
        /// `cancelSearch` to end this search session.
        /// </summary>
        /// <param name="Query">Plain text or query selector or XPath search query.</param>
        /// <param name="IncludeUserAgentShadowDOM">True to search in user agent shadow DOM.</param>
        public static DOM.PerformSearchRequest PerformSearch(string Query, bool? IncludeUserAgentShadowDOM = default)
        {
            return new DOM.PerformSearchRequest(Query, IncludeUserAgentShadowDOM);
        }
        /// <summary>
        /// Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or<br/>
        /// `cancelSearch` to end this search session.
        /// </summary>
        /// <param name="Query">Plain text or query selector or XPath search query.</param>
        /// <param name="IncludeUserAgentShadowDOM">True to search in user agent shadow DOM.</param>
        [Core.MethodName("DOM.performSearch")]
        public record PerformSearchRequest(
            string Query,
            bool? IncludeUserAgentShadowDOM = default
        ) : Core.ICommand<PerformSearchRequestResult>
        {
        }
        /// <summary>
        /// Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or<br/>
        /// `cancelSearch` to end this search session.
        /// </summary>
        /// <param name="SearchId">Unique search session identifier.</param>
        /// <param name="ResultCount">Number of search results.</param>
        public record PerformSearchRequestResult(
            string SearchId,
            int ResultCount
        ) : Core.IType
        {
        }
        /// <summary>
        /// Requests that the node is sent to the caller given its path. // FIXME, use XPath
        /// </summary>
        /// <param name="Path">Path to node in the proprietary format.</param>
        public static DOM.PushNodeByPathToFrontendRequest PushNodeByPathToFrontend(string Path)
        {
            return new DOM.PushNodeByPathToFrontendRequest(Path);
        }
        /// <summary>
        /// Requests that the node is sent to the caller given its path. // FIXME, use XPath
        /// </summary>
        /// <param name="Path">Path to node in the proprietary format.</param>
        [Core.MethodName("DOM.pushNodeByPathToFrontend")]
        public record PushNodeByPathToFrontendRequest(
            string Path
        ) : Core.ICommand<PushNodeByPathToFrontendRequestResult>
        {
        }
        /// <summary>
        /// Requests that the node is sent to the caller given its path. // FIXME, use XPath
        /// </summary>
        /// <param name="NodeId">Id of the node for given path.</param>
        public record PushNodeByPathToFrontendRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Requests that a batch of nodes is sent to the caller given their backend node ids.
        /// </summary>
        /// <param name="BackendNodeIds">The array of backend node ids.</param>
        public static DOM.PushNodesByBackendIdsToFrontendRequest PushNodesByBackendIdsToFrontend(IReadOnlyList<DOM.BackendNodeId> BackendNodeIds)
        {
            return new DOM.PushNodesByBackendIdsToFrontendRequest(BackendNodeIds);
        }
        /// <summary>
        /// Requests that a batch of nodes is sent to the caller given their backend node ids.
        /// </summary>
        /// <param name="BackendNodeIds">The array of backend node ids.</param>
        [Core.MethodName("DOM.pushNodesByBackendIdsToFrontend")]
        public record PushNodesByBackendIdsToFrontendRequest(
            IReadOnlyList<DOM.BackendNodeId> BackendNodeIds
        ) : Core.ICommand<PushNodesByBackendIdsToFrontendRequestResult>
        {
        }
        /// <summary>
        /// Requests that a batch of nodes is sent to the caller given their backend node ids.
        /// </summary>
        /// <param name="NodeIds">The array of ids of pushed nodes that correspond to the backend ids specified in<br/>
        /// backendNodeIds.</param>
        public record PushNodesByBackendIdsToFrontendRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Executes `querySelector` on a given node.
        /// </summary>
        /// <param name="NodeId">Id of the node to query upon.</param>
        /// <param name="Selector">Selector string.</param>
        public static DOM.QuerySelectorRequest QuerySelector(DOM.NodeId NodeId, string Selector)
        {
            return new DOM.QuerySelectorRequest(NodeId, Selector);
        }
        /// <summary>
        /// Executes `querySelector` on a given node.
        /// </summary>
        /// <param name="NodeId">Id of the node to query upon.</param>
        /// <param name="Selector">Selector string.</param>
        [Core.MethodName("DOM.querySelector")]
        public record QuerySelectorRequest(
            DOM.NodeId NodeId,
            string Selector
        ) : Core.ICommand<QuerySelectorRequestResult>
        {
        }
        /// <summary>
        /// Executes `querySelector` on a given node.
        /// </summary>
        /// <param name="NodeId">Query selector result.</param>
        public record QuerySelectorRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Executes `querySelectorAll` on a given node.
        /// </summary>
        /// <param name="NodeId">Id of the node to query upon.</param>
        /// <param name="Selector">Selector string.</param>
        public static DOM.QuerySelectorAllRequest QuerySelectorAll(DOM.NodeId NodeId, string Selector)
        {
            return new DOM.QuerySelectorAllRequest(NodeId, Selector);
        }
        /// <summary>
        /// Executes `querySelectorAll` on a given node.
        /// </summary>
        /// <param name="NodeId">Id of the node to query upon.</param>
        /// <param name="Selector">Selector string.</param>
        [Core.MethodName("DOM.querySelectorAll")]
        public record QuerySelectorAllRequest(
            DOM.NodeId NodeId,
            string Selector
        ) : Core.ICommand<QuerySelectorAllRequestResult>
        {
        }
        /// <summary>
        /// Executes `querySelectorAll` on a given node.
        /// </summary>
        /// <param name="NodeIds">Query selector result.</param>
        public record QuerySelectorAllRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns NodeIds of current top layer elements.<br/>
        /// Top layer is rendered closest to the user within a viewport, therefore its elements always<br/>
        /// appear on top of all other content.
        /// </summary>
        public static DOM.GetTopLayerElementsRequest GetTopLayerElements()
        {
            return new DOM.GetTopLayerElementsRequest();
        }
        /// <summary>
        /// Returns NodeIds of current top layer elements.<br/>
        /// Top layer is rendered closest to the user within a viewport, therefore its elements always<br/>
        /// appear on top of all other content.
        /// </summary>
        [Core.MethodName("DOM.getTopLayerElements")]
        public record GetTopLayerElementsRequest() : Core.ICommand<GetTopLayerElementsRequestResult>
        {
        }
        /// <summary>
        /// Returns NodeIds of current top layer elements.<br/>
        /// Top layer is rendered closest to the user within a viewport, therefore its elements always<br/>
        /// appear on top of all other content.
        /// </summary>
        /// <param name="NodeIds">NodeIds of top layer elements</param>
        public record GetTopLayerElementsRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the NodeId of the matched element according to certain relations.
        /// </summary>
        /// <param name="NodeId">Id of the node from which to query the relation.</param>
        /// <param name="Relation">Type of relation to get.</param>
        public static DOM.GetElementByRelationRequest GetElementByRelation(DOM.NodeId NodeId, string Relation)
        {
            return new DOM.GetElementByRelationRequest(NodeId, Relation);
        }
        /// <summary>
        /// Returns the NodeId of the matched element according to certain relations.
        /// </summary>
        /// <param name="NodeId">Id of the node from which to query the relation.</param>
        /// <param name="Relation">Type of relation to get.</param>
        [Core.MethodName("DOM.getElementByRelation")]
        public record GetElementByRelationRequest(
            DOM.NodeId NodeId,
            string Relation
        ) : Core.ICommand<GetElementByRelationRequestResult>
        {
        }
        /// <summary>
        /// Returns the NodeId of the matched element according to certain relations.
        /// </summary>
        /// <param name="NodeId">NodeId of the element matching the queried relation.</param>
        public record GetElementByRelationRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Re-does the last undone action.
        /// </summary>
        public static DOM.RedoRequest Redo()
        {
            return new DOM.RedoRequest();
        }
        /// <summary>
        /// Re-does the last undone action.
        /// </summary>
        [Core.MethodName("DOM.redo")]
        public record RedoRequest() : Core.ICommand<RedoRequestResult>
        {
        }
        /// <summary>
        /// Re-does the last undone action.
        /// </summary>
        public record RedoRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes attribute with given name from an element with given id.
        /// </summary>
        /// <param name="NodeId">Id of the element to remove attribute from.</param>
        /// <param name="Name">Name of the attribute to remove.</param>
        public static DOM.RemoveAttributeRequest RemoveAttribute(DOM.NodeId NodeId, string Name)
        {
            return new DOM.RemoveAttributeRequest(NodeId, Name);
        }
        /// <summary>
        /// Removes attribute with given name from an element with given id.
        /// </summary>
        /// <param name="NodeId">Id of the element to remove attribute from.</param>
        /// <param name="Name">Name of the attribute to remove.</param>
        [Core.MethodName("DOM.removeAttribute")]
        public record RemoveAttributeRequest(
            DOM.NodeId NodeId,
            string Name
        ) : Core.ICommand<RemoveAttributeRequestResult>
        {
        }
        /// <summary>
        /// Removes attribute with given name from an element with given id.
        /// </summary>
        public record RemoveAttributeRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes node with given id.
        /// </summary>
        /// <param name="NodeId">Id of the node to remove.</param>
        public static DOM.RemoveNodeRequest RemoveNode(DOM.NodeId NodeId)
        {
            return new DOM.RemoveNodeRequest(NodeId);
        }
        /// <summary>
        /// Removes node with given id.
        /// </summary>
        /// <param name="NodeId">Id of the node to remove.</param>
        [Core.MethodName("DOM.removeNode")]
        public record RemoveNodeRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<RemoveNodeRequestResult>
        {
        }
        /// <summary>
        /// Removes node with given id.
        /// </summary>
        public record RemoveNodeRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Requests that children of the node with given id are returned to the caller in form of<br/>
        /// `setChildNodes` events where not only immediate children are retrieved, but all children down to<br/>
        /// the specified depth.
        /// </summary>
        /// <param name="NodeId">Id of the node to get children for.</param>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the sub-tree<br/>
        /// (default is false).</param>
        public static DOM.RequestChildNodesRequest RequestChildNodes(DOM.NodeId NodeId, int? Depth = default, bool? Pierce = default)
        {
            return new DOM.RequestChildNodesRequest(NodeId, Depth, Pierce);
        }
        /// <summary>
        /// Requests that children of the node with given id are returned to the caller in form of<br/>
        /// `setChildNodes` events where not only immediate children are retrieved, but all children down to<br/>
        /// the specified depth.
        /// </summary>
        /// <param name="NodeId">Id of the node to get children for.</param>
        /// <param name="Depth">The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the sub-tree<br/>
        /// (default is false).</param>
        [Core.MethodName("DOM.requestChildNodes")]
        public record RequestChildNodesRequest(
            DOM.NodeId NodeId,
            int? Depth = default,
            bool? Pierce = default
        ) : Core.ICommand<RequestChildNodesRequestResult>
        {
        }
        /// <summary>
        /// Requests that children of the node with given id are returned to the caller in form of<br/>
        /// `setChildNodes` events where not only immediate children are retrieved, but all children down to<br/>
        /// the specified depth.
        /// </summary>
        public record RequestChildNodesRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Requests that the node is sent to the caller given the JavaScript node object reference. All<br/>
        /// nodes that form the path from the node to the root are also sent to the client as a series of<br/>
        /// `setChildNodes` notifications.
        /// </summary>
        /// <param name="ObjectId">JavaScript object id to convert into node.</param>
        public static DOM.RequestNodeRequest RequestNode(Runtime.RemoteObjectId ObjectId)
        {
            return new DOM.RequestNodeRequest(ObjectId);
        }
        /// <summary>
        /// Requests that the node is sent to the caller given the JavaScript node object reference. All<br/>
        /// nodes that form the path from the node to the root are also sent to the client as a series of<br/>
        /// `setChildNodes` notifications.
        /// </summary>
        /// <param name="ObjectId">JavaScript object id to convert into node.</param>
        [Core.MethodName("DOM.requestNode")]
        public record RequestNodeRequest(
            Runtime.RemoteObjectId ObjectId
        ) : Core.ICommand<RequestNodeRequestResult>
        {
        }
        /// <summary>
        /// Requests that the node is sent to the caller given the JavaScript node object reference. All<br/>
        /// nodes that form the path from the node to the root are also sent to the client as a series of<br/>
        /// `setChildNodes` notifications.
        /// </summary>
        /// <param name="NodeId">Node id for given object.</param>
        public record RequestNodeRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Resolves the JavaScript node object for a given NodeId or BackendNodeId.
        /// </summary>
        /// <param name="NodeId">Id of the node to resolve.</param>
        /// <param name="BackendNodeId">Backend identifier of the node to resolve.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects.</param>
        /// <param name="ExecutionContextId">Execution context in which to resolve the node.</param>
        public static DOM.ResolveNodeRequest ResolveNode(DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, string? ObjectGroup = default, Runtime.ExecutionContextId? ExecutionContextId = default)
        {
            return new DOM.ResolveNodeRequest(NodeId, BackendNodeId, ObjectGroup, ExecutionContextId);
        }
        /// <summary>
        /// Resolves the JavaScript node object for a given NodeId or BackendNodeId.
        /// </summary>
        /// <param name="NodeId">Id of the node to resolve.</param>
        /// <param name="BackendNodeId">Backend identifier of the node to resolve.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects.</param>
        /// <param name="ExecutionContextId">Execution context in which to resolve the node.</param>
        [Core.MethodName("DOM.resolveNode")]
        public record ResolveNodeRequest(
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            string? ObjectGroup = default,
            Runtime.ExecutionContextId? ExecutionContextId = default
        ) : Core.ICommand<ResolveNodeRequestResult>
        {
        }
        /// <summary>
        /// Resolves the JavaScript node object for a given NodeId or BackendNodeId.
        /// </summary>
        /// <param name="Object">JavaScript object wrapper for given node.</param>
        public record ResolveNodeRequestResult(
            Runtime.RemoteObject Object
        ) : Core.IType
        {
        }
        /// <summary>
        /// Sets attribute for an element with given id.
        /// </summary>
        /// <param name="NodeId">Id of the element to set attribute for.</param>
        /// <param name="Name">Attribute name.</param>
        /// <param name="Value">Attribute value.</param>
        public static DOM.SetAttributeValueRequest SetAttributeValue(DOM.NodeId NodeId, string Name, string Value)
        {
            return new DOM.SetAttributeValueRequest(NodeId, Name, Value);
        }
        /// <summary>
        /// Sets attribute for an element with given id.
        /// </summary>
        /// <param name="NodeId">Id of the element to set attribute for.</param>
        /// <param name="Name">Attribute name.</param>
        /// <param name="Value">Attribute value.</param>
        [Core.MethodName("DOM.setAttributeValue")]
        public record SetAttributeValueRequest(
            DOM.NodeId NodeId,
            string Name,
            string Value
        ) : Core.ICommand<SetAttributeValueRequestResult>
        {
        }
        /// <summary>
        /// Sets attribute for an element with given id.
        /// </summary>
        public record SetAttributeValueRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets attributes on element with given id. This method is useful when user edits some existing<br/>
        /// attribute value and types in several attribute name/value pairs.
        /// </summary>
        /// <param name="NodeId">Id of the element to set attributes for.</param>
        /// <param name="Text">Text with a number of attributes. Will parse this text using HTML parser.</param>
        /// <param name="Name">Attribute name to replace with new attributes derived from text in case text parsed<br/>
        /// successfully.</param>
        public static DOM.SetAttributesAsTextRequest SetAttributesAsText(DOM.NodeId NodeId, string Text, string? Name = default)
        {
            return new DOM.SetAttributesAsTextRequest(NodeId, Text, Name);
        }
        /// <summary>
        /// Sets attributes on element with given id. This method is useful when user edits some existing<br/>
        /// attribute value and types in several attribute name/value pairs.
        /// </summary>
        /// <param name="NodeId">Id of the element to set attributes for.</param>
        /// <param name="Text">Text with a number of attributes. Will parse this text using HTML parser.</param>
        /// <param name="Name">Attribute name to replace with new attributes derived from text in case text parsed<br/>
        /// successfully.</param>
        [Core.MethodName("DOM.setAttributesAsText")]
        public record SetAttributesAsTextRequest(
            DOM.NodeId NodeId,
            string Text,
            string? Name = default
        ) : Core.ICommand<SetAttributesAsTextRequestResult>
        {
        }
        /// <summary>
        /// Sets attributes on element with given id. This method is useful when user edits some existing<br/>
        /// attribute value and types in several attribute name/value pairs.
        /// </summary>
        public record SetAttributesAsTextRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets files for the given file input element.
        /// </summary>
        /// <param name="Files">Array of file paths to set.</param>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        public static DOM.SetFileInputFilesRequest SetFileInputFiles(IReadOnlyList<string> Files, DOM.NodeId? NodeId = default, DOM.BackendNodeId? BackendNodeId = default, Runtime.RemoteObjectId? ObjectId = default)
        {
            return new DOM.SetFileInputFilesRequest(Files, NodeId, BackendNodeId, ObjectId);
        }
        /// <summary>
        /// Sets files for the given file input element.
        /// </summary>
        /// <param name="Files">Array of file paths to set.</param>
        /// <param name="NodeId">Identifier of the node.</param>
        /// <param name="BackendNodeId">Identifier of the backend node.</param>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        [Core.MethodName("DOM.setFileInputFiles")]
        public record SetFileInputFilesRequest(
            IReadOnlyList<string> Files,
            DOM.NodeId? NodeId = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.RemoteObjectId? ObjectId = default
        ) : Core.ICommand<SetFileInputFilesRequestResult>
        {
        }
        /// <summary>
        /// Sets files for the given file input element.
        /// </summary>
        public record SetFileInputFilesRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled.
        /// </summary>
        /// <param name="Enable">Enable or disable.</param>
        public static DOM.SetNodeStackTracesEnabledRequest SetNodeStackTracesEnabled(bool Enable)
        {
            return new DOM.SetNodeStackTracesEnabledRequest(Enable);
        }
        /// <summary>
        /// Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled.
        /// </summary>
        /// <param name="Enable">Enable or disable.</param>
        [Core.MethodName("DOM.setNodeStackTracesEnabled")]
        public record SetNodeStackTracesEnabledRequest(
            bool Enable
        ) : Core.ICommand<SetNodeStackTracesEnabledRequestResult>
        {
        }
        /// <summary>
        /// Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled.
        /// </summary>
        public record SetNodeStackTracesEnabledRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation.
        /// </summary>
        /// <param name="NodeId">Id of the node to get stack traces for.</param>
        public static DOM.GetNodeStackTracesRequest GetNodeStackTraces(DOM.NodeId NodeId)
        {
            return new DOM.GetNodeStackTracesRequest(NodeId);
        }
        /// <summary>
        /// Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation.
        /// </summary>
        /// <param name="NodeId">Id of the node to get stack traces for.</param>
        [Core.MethodName("DOM.getNodeStackTraces")]
        public record GetNodeStackTracesRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<GetNodeStackTracesRequestResult>
        {
        }
        /// <summary>
        /// Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation.
        /// </summary>
        /// <param name="Creation">Creation stack trace, if available.</param>
        public record GetNodeStackTracesRequestResult(
            Runtime.StackTrace? Creation = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns file information for the given<br/>
        /// File wrapper.
        /// </summary>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        public static DOM.GetFileInfoRequest GetFileInfo(Runtime.RemoteObjectId ObjectId)
        {
            return new DOM.GetFileInfoRequest(ObjectId);
        }
        /// <summary>
        /// Returns file information for the given<br/>
        /// File wrapper.
        /// </summary>
        /// <param name="ObjectId">JavaScript object id of the node wrapper.</param>
        [Core.MethodName("DOM.getFileInfo")]
        public record GetFileInfoRequest(
            Runtime.RemoteObjectId ObjectId
        ) : Core.ICommand<GetFileInfoRequestResult>
        {
        }
        /// <summary>
        /// Returns file information for the given<br/>
        /// File wrapper.
        /// </summary>
        public record GetFileInfoRequestResult(
            string Path
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns list of detached nodes
        /// </summary>
        public static DOM.GetDetachedDomNodesRequest GetDetachedDomNodes()
        {
            return new DOM.GetDetachedDomNodesRequest();
        }
        /// <summary>
        /// Returns list of detached nodes
        /// </summary>
        [Core.MethodName("DOM.getDetachedDomNodes")]
        public record GetDetachedDomNodesRequest() : Core.ICommand<GetDetachedDomNodesRequestResult>
        {
        }
        /// <summary>
        /// Returns list of detached nodes
        /// </summary>
        /// <param name="DetachedNodes">The list of detached nodes</param>
        public record GetDetachedDomNodesRequestResult(
            IReadOnlyList<DOM.DetachedElementInfo> DetachedNodes
        ) : Core.IType
        {
        }
        /// <summary>
        /// Enables console to refer to the node with given id via $x (see Command Line API for more details<br/>
        /// $x functions).
        /// </summary>
        /// <param name="NodeId">DOM node id to be accessible by means of $x command line API.</param>
        public static DOM.SetInspectedNodeRequest SetInspectedNode(DOM.NodeId NodeId)
        {
            return new DOM.SetInspectedNodeRequest(NodeId);
        }
        /// <summary>
        /// Enables console to refer to the node with given id via $x (see Command Line API for more details<br/>
        /// $x functions).
        /// </summary>
        /// <param name="NodeId">DOM node id to be accessible by means of $x command line API.</param>
        [Core.MethodName("DOM.setInspectedNode")]
        public record SetInspectedNodeRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<SetInspectedNodeRequestResult>
        {
        }
        /// <summary>
        /// Enables console to refer to the node with given id via $x (see Command Line API for more details<br/>
        /// $x functions).
        /// </summary>
        public record SetInspectedNodeRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets node name for a node with given id.
        /// </summary>
        /// <param name="NodeId">Id of the node to set name for.</param>
        /// <param name="Name">New node&apos;s name.</param>
        public static DOM.SetNodeNameRequest SetNodeName(DOM.NodeId NodeId, string Name)
        {
            return new DOM.SetNodeNameRequest(NodeId, Name);
        }
        /// <summary>
        /// Sets node name for a node with given id.
        /// </summary>
        /// <param name="NodeId">Id of the node to set name for.</param>
        /// <param name="Name">New node&apos;s name.</param>
        [Core.MethodName("DOM.setNodeName")]
        public record SetNodeNameRequest(
            DOM.NodeId NodeId,
            string Name
        ) : Core.ICommand<SetNodeNameRequestResult>
        {
        }
        /// <summary>
        /// Sets node name for a node with given id.
        /// </summary>
        /// <param name="NodeId">New node&apos;s id.</param>
        public record SetNodeNameRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Sets node value for a node with given id.
        /// </summary>
        /// <param name="NodeId">Id of the node to set value for.</param>
        /// <param name="Value">New node&apos;s value.</param>
        public static DOM.SetNodeValueRequest SetNodeValue(DOM.NodeId NodeId, string Value)
        {
            return new DOM.SetNodeValueRequest(NodeId, Value);
        }
        /// <summary>
        /// Sets node value for a node with given id.
        /// </summary>
        /// <param name="NodeId">Id of the node to set value for.</param>
        /// <param name="Value">New node&apos;s value.</param>
        [Core.MethodName("DOM.setNodeValue")]
        public record SetNodeValueRequest(
            DOM.NodeId NodeId,
            string Value
        ) : Core.ICommand<SetNodeValueRequestResult>
        {
        }
        /// <summary>
        /// Sets node value for a node with given id.
        /// </summary>
        public record SetNodeValueRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets node HTML markup, returns new node id.
        /// </summary>
        /// <param name="NodeId">Id of the node to set markup for.</param>
        /// <param name="OuterHTML">Outer HTML markup to set.</param>
        public static DOM.SetOuterHTMLRequest SetOuterHTML(DOM.NodeId NodeId, string OuterHTML)
        {
            return new DOM.SetOuterHTMLRequest(NodeId, OuterHTML);
        }
        /// <summary>
        /// Sets node HTML markup, returns new node id.
        /// </summary>
        /// <param name="NodeId">Id of the node to set markup for.</param>
        /// <param name="OuterHTML">Outer HTML markup to set.</param>
        [Core.MethodName("DOM.setOuterHTML")]
        public record SetOuterHTMLRequest(
            DOM.NodeId NodeId,
            string OuterHTML
        ) : Core.ICommand<SetOuterHTMLRequestResult>
        {
        }
        /// <summary>
        /// Sets node HTML markup, returns new node id.
        /// </summary>
        public record SetOuterHTMLRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Undoes the last performed action.
        /// </summary>
        public static DOM.UndoRequest Undo()
        {
            return new DOM.UndoRequest();
        }
        /// <summary>
        /// Undoes the last performed action.
        /// </summary>
        [Core.MethodName("DOM.undo")]
        public record UndoRequest() : Core.ICommand<UndoRequestResult>
        {
        }
        /// <summary>
        /// Undoes the last performed action.
        /// </summary>
        public record UndoRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Returns iframe node that owns iframe with the given domain.
        /// </summary>
        public static DOM.GetFrameOwnerRequest GetFrameOwner(Page.FrameId FrameId)
        {
            return new DOM.GetFrameOwnerRequest(FrameId);
        }
        /// <summary>
        /// Returns iframe node that owns iframe with the given domain.
        /// </summary>
        [Core.MethodName("DOM.getFrameOwner")]
        public record GetFrameOwnerRequest(
            Page.FrameId FrameId
        ) : Core.ICommand<GetFrameOwnerRequestResult>
        {
        }
        /// <summary>
        /// Returns iframe node that owns iframe with the given domain.
        /// </summary>
        /// <param name="BackendNodeId">Resulting node.</param>
        /// <param name="NodeId">Id of the node at given coordinates, only when enabled and requested document.</param>
        public record GetFrameOwnerRequestResult(
            DOM.BackendNodeId BackendNodeId,
            DOM.NodeId? NodeId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the query container of the given node based on container query<br/>
        /// conditions: containerName, physical and logical axes, and whether it queries<br/>
        /// scroll-state or anchored elements. If no axes are provided and<br/>
        /// queriesScrollState is false, the style container is returned, which is the<br/>
        /// direct parent or the closest element with a matching container-name.
        /// </summary>
        public static DOM.GetContainerForNodeRequest GetContainerForNode(DOM.NodeId NodeId, string? ContainerName = default, DOM.PhysicalAxes? PhysicalAxes = default, DOM.LogicalAxes? LogicalAxes = default, bool? QueriesScrollState = default, bool? QueriesAnchored = default)
        {
            return new DOM.GetContainerForNodeRequest(NodeId, ContainerName, PhysicalAxes, LogicalAxes, QueriesScrollState, QueriesAnchored);
        }
        /// <summary>
        /// Returns the query container of the given node based on container query<br/>
        /// conditions: containerName, physical and logical axes, and whether it queries<br/>
        /// scroll-state or anchored elements. If no axes are provided and<br/>
        /// queriesScrollState is false, the style container is returned, which is the<br/>
        /// direct parent or the closest element with a matching container-name.
        /// </summary>
        [Core.MethodName("DOM.getContainerForNode")]
        public record GetContainerForNodeRequest(
            DOM.NodeId NodeId,
            string? ContainerName = default,
            DOM.PhysicalAxes? PhysicalAxes = default,
            DOM.LogicalAxes? LogicalAxes = default,
            bool? QueriesScrollState = default,
            bool? QueriesAnchored = default
        ) : Core.ICommand<GetContainerForNodeRequestResult>
        {
        }
        /// <summary>
        /// Returns the query container of the given node based on container query<br/>
        /// conditions: containerName, physical and logical axes, and whether it queries<br/>
        /// scroll-state or anchored elements. If no axes are provided and<br/>
        /// queriesScrollState is false, the style container is returned, which is the<br/>
        /// direct parent or the closest element with a matching container-name.
        /// </summary>
        /// <param name="NodeId">The container node for the given node, or null if not found.</param>
        public record GetContainerForNodeRequestResult(
            DOM.NodeId? NodeId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the descendants of a container query container that have<br/>
        /// container queries against this container.
        /// </summary>
        /// <param name="NodeId">Id of the container node to find querying descendants from.</param>
        public static DOM.GetQueryingDescendantsForContainerRequest GetQueryingDescendantsForContainer(DOM.NodeId NodeId)
        {
            return new DOM.GetQueryingDescendantsForContainerRequest(NodeId);
        }
        /// <summary>
        /// Returns the descendants of a container query container that have<br/>
        /// container queries against this container.
        /// </summary>
        /// <param name="NodeId">Id of the container node to find querying descendants from.</param>
        [Core.MethodName("DOM.getQueryingDescendantsForContainer")]
        public record GetQueryingDescendantsForContainerRequest(
            DOM.NodeId NodeId
        ) : Core.ICommand<GetQueryingDescendantsForContainerRequestResult>
        {
        }
        /// <summary>
        /// Returns the descendants of a container query container that have<br/>
        /// container queries against this container.
        /// </summary>
        /// <param name="NodeIds">Descendant nodes with container queries against the given container.</param>
        public record GetQueryingDescendantsForContainerRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the target anchor element of the given anchor query according to<br/>
        /// https://www.w3.org/TR/css-anchor-position-1/#target.
        /// </summary>
        /// <param name="NodeId">Id of the positioned element from which to find the anchor.</param>
        /// <param name="AnchorSpecifier">An optional anchor specifier, as defined in<br/>
        /// https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier.<br/>
        /// If not provided, it will return the implicit anchor element for<br/>
        /// the given positioned element.</param>
        public static DOM.GetAnchorElementRequest GetAnchorElement(DOM.NodeId NodeId, string? AnchorSpecifier = default)
        {
            return new DOM.GetAnchorElementRequest(NodeId, AnchorSpecifier);
        }
        /// <summary>
        /// Returns the target anchor element of the given anchor query according to<br/>
        /// https://www.w3.org/TR/css-anchor-position-1/#target.
        /// </summary>
        /// <param name="NodeId">Id of the positioned element from which to find the anchor.</param>
        /// <param name="AnchorSpecifier">An optional anchor specifier, as defined in<br/>
        /// https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier.<br/>
        /// If not provided, it will return the implicit anchor element for<br/>
        /// the given positioned element.</param>
        [Core.MethodName("DOM.getAnchorElement")]
        public record GetAnchorElementRequest(
            DOM.NodeId NodeId,
            string? AnchorSpecifier = default
        ) : Core.ICommand<GetAnchorElementRequestResult>
        {
        }
        /// <summary>
        /// Returns the target anchor element of the given anchor query according to<br/>
        /// https://www.w3.org/TR/css-anchor-position-1/#target.
        /// </summary>
        /// <param name="NodeId">The anchor element of the given anchor query.</param>
        public record GetAnchorElementRequestResult(
            DOM.NodeId NodeId
        ) : Core.IType
        {
        }
        /// <summary>
        /// When enabling, this API force-opens the popover identified by nodeId<br/>
        /// and keeps it open until disabled.
        /// </summary>
        /// <param name="NodeId">Id of the popover HTMLElement</param>
        /// <param name="Enable">If true, opens the popover and keeps it open. If false, closes the<br/>
        /// popover if it was previously force-opened.</param>
        public static DOM.ForceShowPopoverRequest ForceShowPopover(DOM.NodeId NodeId, bool Enable)
        {
            return new DOM.ForceShowPopoverRequest(NodeId, Enable);
        }
        /// <summary>
        /// When enabling, this API force-opens the popover identified by nodeId<br/>
        /// and keeps it open until disabled.
        /// </summary>
        /// <param name="NodeId">Id of the popover HTMLElement</param>
        /// <param name="Enable">If true, opens the popover and keeps it open. If false, closes the<br/>
        /// popover if it was previously force-opened.</param>
        [Core.MethodName("DOM.forceShowPopover")]
        public record ForceShowPopoverRequest(
            DOM.NodeId NodeId,
            bool Enable
        ) : Core.ICommand<ForceShowPopoverRequestResult>
        {
        }
        /// <summary>
        /// When enabling, this API force-opens the popover identified by nodeId<br/>
        /// and keeps it open until disabled.
        /// </summary>
        /// <param name="NodeIds">List of popovers that were closed in order to respect popover stacking order.</param>
        public record ForceShowPopoverRequestResult(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IType
        {
        }
        /// <summary>
        /// Fired when `Element`&apos;s attribute is modified.
        /// </summary>
        /// <param name="NodeId">Id of the node that has changed.</param>
        /// <param name="Name">Attribute name.</param>
        /// <param name="Value">Attribute value.</param>
        [Core.MethodName("DOM.attributeModified")]
        public record AttributeModified(
            DOM.NodeId NodeId,
            string Name,
            string Value
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when `Element`&apos;s adoptedStyleSheets are modified.
        /// </summary>
        /// <param name="NodeId">Id of the node that has changed.</param>
        /// <param name="AdoptedStyleSheets">New adoptedStyleSheets array.</param>
        [Core.MethodName("DOM.adoptedStyleSheetsModified")]
        public record AdoptedStyleSheetsModified(
            DOM.NodeId NodeId,
            IReadOnlyList<DOM.StyleSheetId> AdoptedStyleSheets
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when `Element`&apos;s attribute is removed.
        /// </summary>
        /// <param name="NodeId">Id of the node that has changed.</param>
        /// <param name="Name">A ttribute name.</param>
        [Core.MethodName("DOM.attributeRemoved")]
        public record AttributeRemoved(
            DOM.NodeId NodeId,
            string Name
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Mirrors `DOMCharacterDataModified` event.
        /// </summary>
        /// <param name="NodeId">Id of the node that has changed.</param>
        /// <param name="CharacterData">New text value.</param>
        [Core.MethodName("DOM.characterDataModified")]
        public record CharacterDataModified(
            DOM.NodeId NodeId,
            string CharacterData
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when `Container`&apos;s child node count has changed.
        /// </summary>
        /// <param name="NodeId">Id of the node that has changed.</param>
        /// <param name="ChildNodeCount">New node count.</param>
        [Core.MethodName("DOM.childNodeCountUpdated")]
        public record ChildNodeCountUpdated(
            DOM.NodeId NodeId,
            int ChildNodeCount
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Mirrors `DOMNodeInserted` event.
        /// </summary>
        /// <param name="ParentNodeId">Id of the node that has changed.</param>
        /// <param name="PreviousNodeId">Id of the previous sibling.</param>
        /// <param name="Node">Inserted node data.</param>
        [Core.MethodName("DOM.childNodeInserted")]
        public record ChildNodeInserted(
            DOM.NodeId ParentNodeId,
            DOM.NodeId PreviousNodeId,
            DOM.Node Node
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Mirrors `DOMNodeRemoved` event.
        /// </summary>
        /// <param name="ParentNodeId">Parent id.</param>
        /// <param name="NodeId">Id of the node that has been removed.</param>
        [Core.MethodName("DOM.childNodeRemoved")]
        public record ChildNodeRemoved(
            DOM.NodeId ParentNodeId,
            DOM.NodeId NodeId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Called when distribution is changed.
        /// </summary>
        /// <param name="InsertionPointId">Insertion point where distributed nodes were updated.</param>
        /// <param name="DistributedNodes">Distributed nodes for given insertion point.</param>
        [Core.MethodName("DOM.distributedNodesUpdated")]
        public record DistributedNodesUpdated(
            DOM.NodeId InsertionPointId,
            IReadOnlyList<DOM.BackendNode> DistributedNodes
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when `Document` has been totally updated. Node ids are no longer valid.
        /// </summary>
        [Core.MethodName("DOM.documentUpdated")]
        public record DocumentUpdated(
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when `Element`&apos;s inline style is modified via a CSS property modification.
        /// </summary>
        /// <param name="NodeIds">Ids of the nodes for which the inline styles have been invalidated.</param>
        [Core.MethodName("DOM.inlineStyleInvalidated")]
        public record InlineStyleInvalidated(
            IReadOnlyList<DOM.NodeId> NodeIds
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Called when a pseudo element is added to an element.
        /// </summary>
        /// <param name="ParentId">Pseudo element&apos;s parent element id.</param>
        /// <param name="PseudoElement">The added pseudo element.</param>
        [Core.MethodName("DOM.pseudoElementAdded")]
        public record PseudoElementAdded(
            DOM.NodeId ParentId,
            DOM.Node PseudoElement
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Called when top layer elements are changed.
        /// </summary>
        [Core.MethodName("DOM.topLayerElementsUpdated")]
        public record TopLayerElementsUpdated(
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when a node&apos;s scrollability state changes.
        /// </summary>
        /// <param name="NodeId">The id of the node.</param>
        /// <param name="IsScrollable">If the node is scrollable.</param>
        [Core.MethodName("DOM.scrollableFlagUpdated")]
        public record ScrollableFlagUpdated(
            DOM.NodeId NodeId,
            bool IsScrollable
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when a node&apos;s ad related state changes.
        /// </summary>
        /// <param name="NodeId">The id of the node.</param>
        /// <param name="IsAdRelated">If the node is ad related.</param>
        [Core.MethodName("DOM.adRelatedStateUpdated")]
        public record AdRelatedStateUpdated(
            DOM.NodeId NodeId,
            bool IsAdRelated
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when a node&apos;s starting styles changes.
        /// </summary>
        /// <param name="NodeId">The id of the node.</param>
        /// <param name="AffectedByStartingStyles">If the node has starting styles.</param>
        [Core.MethodName("DOM.affectedByStartingStylesFlagUpdated")]
        public record AffectedByStartingStylesFlagUpdated(
            DOM.NodeId NodeId,
            bool AffectedByStartingStyles
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Called when a pseudo element is removed from an element.
        /// </summary>
        /// <param name="ParentId">Pseudo element&apos;s parent element id.</param>
        /// <param name="PseudoElementId">The removed pseudo element id.</param>
        [Core.MethodName("DOM.pseudoElementRemoved")]
        public record PseudoElementRemoved(
            DOM.NodeId ParentId,
            DOM.NodeId PseudoElementId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Fired when backend wants to provide client with the missing DOM structure. This happens upon<br/>
        /// most of the calls requesting node ids.
        /// </summary>
        /// <param name="ParentId">Parent node id to populate with children.</param>
        /// <param name="Nodes">Child nodes array.</param>
        [Core.MethodName("DOM.setChildNodes")]
        public record SetChildNodes(
            DOM.NodeId ParentId,
            IReadOnlyList<DOM.Node> Nodes
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Called when shadow root is popped from the element.
        /// </summary>
        /// <param name="HostId">Host element id.</param>
        /// <param name="RootId">Shadow root id.</param>
        [Core.MethodName("DOM.shadowRootPopped")]
        public record ShadowRootPopped(
            DOM.NodeId HostId,
            DOM.NodeId RootId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Called when shadow root is pushed into the element.
        /// </summary>
        /// <param name="HostId">Host element id.</param>
        /// <param name="Root">Shadow root.</param>
        [Core.MethodName("DOM.shadowRootPushed")]
        public record ShadowRootPushed(
            DOM.NodeId HostId,
            DOM.Node Root
        ) : Core.IEvent
        {
        }
    }
}
