// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class DOMDebugger
    {
        /// <summary>
        /// DOM breakpoint type.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record DOMBreakpointType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly DOMBreakpointType SUBTREE_MODIFIED = new("subtree-modified");
            public static readonly DOMBreakpointType ATTRIBUTE_MODIFIED = new("attribute-modified");
            public static readonly DOMBreakpointType NODE_REMOVED = new("node-removed");
        }
        /// <summary>
        /// CSP Violation type.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record CSPViolationType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly CSPViolationType TRUSTEDTYPE_SINK_VIOLATION = new("trustedtype-sink-violation");
            public static readonly CSPViolationType TRUSTEDTYPE_POLICY_VIOLATION = new("trustedtype-policy-violation");
        }
        /// <summary>
        /// Object event listener.
        /// </summary>
        /// <param name="Type">`EventListener`&apos;s type.</param>
        /// <param name="UseCapture">`EventListener`&apos;s useCapture.</param>
        /// <param name="Passive">`EventListener`&apos;s passive flag.</param>
        /// <param name="Once">`EventListener`&apos;s once flag.</param>
        /// <param name="ScriptId">Script id of the handler code.</param>
        /// <param name="LineNumber">Line number in the script (0-based).</param>
        /// <param name="ColumnNumber">Column number in the script (0-based).</param>
        /// <param name="Handler">Event handler function value.</param>
        /// <param name="OriginalHandler">Event original handler function value.</param>
        /// <param name="BackendNodeId">Node the listener is added to (if any).</param>
        public record EventListener(
            string Type,
            bool UseCapture,
            bool Passive,
            bool Once,
            Runtime.ScriptId ScriptId,
            int LineNumber,
            int ColumnNumber,
            Runtime.RemoteObject? Handler = default,
            Runtime.RemoteObject? OriginalHandler = default,
            DOM.BackendNodeId? BackendNodeId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns event listeners of the given object.
        /// </summary>
        /// <param name="ObjectId">Identifier of the object to return listeners for.</param>
        /// <param name="Depth">The maximum depth at which Node children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false). Reports listeners for all contexts if pierce is enabled.</param>
        public static DOMDebugger.GetEventListenersRequest GetEventListeners(Runtime.RemoteObjectId ObjectId, int? Depth = default, bool? Pierce = default)
        {
            return new DOMDebugger.GetEventListenersRequest(ObjectId, Depth, Pierce);
        }
        /// <summary>
        /// Returns event listeners of the given object.
        /// </summary>
        /// <param name="ObjectId">Identifier of the object to return listeners for.</param>
        /// <param name="Depth">The maximum depth at which Node children should be retrieved, defaults to 1. Use -1 for the<br/>
        /// entire subtree or provide an integer larger than 0.</param>
        /// <param name="Pierce">Whether or not iframes and shadow roots should be traversed when returning the subtree<br/>
        /// (default is false). Reports listeners for all contexts if pierce is enabled.</param>
        [Core.MethodName("DOMDebugger.getEventListeners")]
        public record GetEventListenersRequest(
            Runtime.RemoteObjectId ObjectId,
            int? Depth = default,
            bool? Pierce = default
        ) : Core.ICommand<GetEventListenersRequestResult>
        {
        }
        /// <summary>
        /// Returns event listeners of the given object.
        /// </summary>
        /// <param name="Listeners">Array of relevant listeners.</param>
        public record GetEventListenersRequestResult(
            IReadOnlyList<DOMDebugger.EventListener> Listeners
        ) : Core.IType
        {
        }
        /// <summary>
        /// Removes DOM breakpoint that was set using `setDOMBreakpoint`.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to remove breakpoint from.</param>
        /// <param name="Type">Type of the breakpoint to remove.</param>
        public static DOMDebugger.RemoveDOMBreakpointRequest RemoveDOMBreakpoint(DOM.NodeId NodeId, DOMDebugger.DOMBreakpointType Type)
        {
            return new DOMDebugger.RemoveDOMBreakpointRequest(NodeId, Type);
        }
        /// <summary>
        /// Removes DOM breakpoint that was set using `setDOMBreakpoint`.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to remove breakpoint from.</param>
        /// <param name="Type">Type of the breakpoint to remove.</param>
        [Core.MethodName("DOMDebugger.removeDOMBreakpoint")]
        public record RemoveDOMBreakpointRequest(
            DOM.NodeId NodeId,
            DOMDebugger.DOMBreakpointType Type
        ) : Core.ICommand<RemoveDOMBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Removes DOM breakpoint that was set using `setDOMBreakpoint`.
        /// </summary>
        public record RemoveDOMBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes breakpoint on particular DOM event.
        /// </summary>
        /// <param name="EventName">Event name.</param>
        /// <param name="TargetName">EventTarget interface name.</param>
        public static DOMDebugger.RemoveEventListenerBreakpointRequest RemoveEventListenerBreakpoint(string EventName, string? TargetName = default)
        {
            return new DOMDebugger.RemoveEventListenerBreakpointRequest(EventName, TargetName);
        }
        /// <summary>
        /// Removes breakpoint on particular DOM event.
        /// </summary>
        /// <param name="EventName">Event name.</param>
        /// <param name="TargetName">EventTarget interface name.</param>
        [Core.MethodName("DOMDebugger.removeEventListenerBreakpoint")]
        public record RemoveEventListenerBreakpointRequest(
            string EventName,
            string? TargetName = default
        ) : Core.ICommand<RemoveEventListenerBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Removes breakpoint on particular DOM event.
        /// </summary>
        public record RemoveEventListenerBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        [Obsolete]
        public static DOMDebugger.RemoveInstrumentationBreakpointRequest RemoveInstrumentationBreakpoint(string EventName)
        {
            return new DOMDebugger.RemoveInstrumentationBreakpointRequest(EventName);
        }
        /// <summary>
        /// Removes breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        [Obsolete]
        [Core.MethodName("DOMDebugger.removeInstrumentationBreakpoint")]
        public record RemoveInstrumentationBreakpointRequest(
            string EventName
        ) : Core.ICommand<RemoveInstrumentationBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Removes breakpoint on particular native event.
        /// </summary>
        [Obsolete]
        public record RemoveInstrumentationBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes breakpoint from XMLHttpRequest.
        /// </summary>
        /// <param name="Url">Resource URL substring.</param>
        public static DOMDebugger.RemoveXHRBreakpointRequest RemoveXHRBreakpoint(string Url)
        {
            return new DOMDebugger.RemoveXHRBreakpointRequest(Url);
        }
        /// <summary>
        /// Removes breakpoint from XMLHttpRequest.
        /// </summary>
        /// <param name="Url">Resource URL substring.</param>
        [Core.MethodName("DOMDebugger.removeXHRBreakpoint")]
        public record RemoveXHRBreakpointRequest(
            string Url
        ) : Core.ICommand<RemoveXHRBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Removes breakpoint from XMLHttpRequest.
        /// </summary>
        public record RemoveXHRBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets breakpoint on particular CSP violations.
        /// </summary>
        /// <param name="ViolationTypes">CSP Violations to stop upon.</param>
        public static DOMDebugger.SetBreakOnCSPViolationRequest SetBreakOnCSPViolation(IReadOnlyList<DOMDebugger.CSPViolationType> ViolationTypes)
        {
            return new DOMDebugger.SetBreakOnCSPViolationRequest(ViolationTypes);
        }
        /// <summary>
        /// Sets breakpoint on particular CSP violations.
        /// </summary>
        /// <param name="ViolationTypes">CSP Violations to stop upon.</param>
        [Core.MethodName("DOMDebugger.setBreakOnCSPViolation")]
        public record SetBreakOnCSPViolationRequest(
            IReadOnlyList<DOMDebugger.CSPViolationType> ViolationTypes
        ) : Core.ICommand<SetBreakOnCSPViolationRequestResult>
        {
        }
        /// <summary>
        /// Sets breakpoint on particular CSP violations.
        /// </summary>
        public record SetBreakOnCSPViolationRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets breakpoint on particular operation with DOM.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to set breakpoint on.</param>
        /// <param name="Type">Type of the operation to stop upon.</param>
        public static DOMDebugger.SetDOMBreakpointRequest SetDOMBreakpoint(DOM.NodeId NodeId, DOMDebugger.DOMBreakpointType Type)
        {
            return new DOMDebugger.SetDOMBreakpointRequest(NodeId, Type);
        }
        /// <summary>
        /// Sets breakpoint on particular operation with DOM.
        /// </summary>
        /// <param name="NodeId">Identifier of the node to set breakpoint on.</param>
        /// <param name="Type">Type of the operation to stop upon.</param>
        [Core.MethodName("DOMDebugger.setDOMBreakpoint")]
        public record SetDOMBreakpointRequest(
            DOM.NodeId NodeId,
            DOMDebugger.DOMBreakpointType Type
        ) : Core.ICommand<SetDOMBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets breakpoint on particular operation with DOM.
        /// </summary>
        public record SetDOMBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets breakpoint on particular DOM event.
        /// </summary>
        /// <param name="EventName">DOM Event name to stop on (any DOM event will do).</param>
        /// <param name="TargetName">EventTarget interface name to stop on. If equal to `&quot;*&quot;` or not provided, will stop on any<br/>
        /// EventTarget.</param>
        public static DOMDebugger.SetEventListenerBreakpointRequest SetEventListenerBreakpoint(string EventName, string? TargetName = default)
        {
            return new DOMDebugger.SetEventListenerBreakpointRequest(EventName, TargetName);
        }
        /// <summary>
        /// Sets breakpoint on particular DOM event.
        /// </summary>
        /// <param name="EventName">DOM Event name to stop on (any DOM event will do).</param>
        /// <param name="TargetName">EventTarget interface name to stop on. If equal to `&quot;*&quot;` or not provided, will stop on any<br/>
        /// EventTarget.</param>
        [Core.MethodName("DOMDebugger.setEventListenerBreakpoint")]
        public record SetEventListenerBreakpointRequest(
            string EventName,
            string? TargetName = default
        ) : Core.ICommand<SetEventListenerBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets breakpoint on particular DOM event.
        /// </summary>
        public record SetEventListenerBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        [Obsolete]
        public static DOMDebugger.SetInstrumentationBreakpointRequest SetInstrumentationBreakpoint(string EventName)
        {
            return new DOMDebugger.SetInstrumentationBreakpointRequest(EventName);
        }
        /// <summary>
        /// Sets breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        [Obsolete]
        [Core.MethodName("DOMDebugger.setInstrumentationBreakpoint")]
        public record SetInstrumentationBreakpointRequest(
            string EventName
        ) : Core.ICommand<SetInstrumentationBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets breakpoint on particular native event.
        /// </summary>
        [Obsolete]
        public record SetInstrumentationBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Sets breakpoint on XMLHttpRequest.
        /// </summary>
        /// <param name="Url">Resource URL substring. All XHRs having this substring in the URL will get stopped upon.</param>
        public static DOMDebugger.SetXHRBreakpointRequest SetXHRBreakpoint(string Url)
        {
            return new DOMDebugger.SetXHRBreakpointRequest(Url);
        }
        /// <summary>
        /// Sets breakpoint on XMLHttpRequest.
        /// </summary>
        /// <param name="Url">Resource URL substring. All XHRs having this substring in the URL will get stopped upon.</param>
        [Core.MethodName("DOMDebugger.setXHRBreakpoint")]
        public record SetXHRBreakpointRequest(
            string Url
        ) : Core.ICommand<SetXHRBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets breakpoint on XMLHttpRequest.
        /// </summary>
        public record SetXHRBreakpointRequestResult() : Core.IType
        {
        }
    }
}
