// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class EventBreakpoints
    {
        /// <summary>
        /// Sets breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        public static EventBreakpoints.SetInstrumentationBreakpointRequest SetInstrumentationBreakpoint(string EventName)
        {
            return new EventBreakpoints.SetInstrumentationBreakpointRequest(EventName);
        }
        /// <summary>
        /// Sets breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        [Core.MethodName("EventBreakpoints.setInstrumentationBreakpoint")]
        public record SetInstrumentationBreakpointRequest(
            string EventName
        ) : Core.ICommand<SetInstrumentationBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Sets breakpoint on particular native event.
        /// </summary>
        public record SetInstrumentationBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        public static EventBreakpoints.RemoveInstrumentationBreakpointRequest RemoveInstrumentationBreakpoint(string EventName)
        {
            return new EventBreakpoints.RemoveInstrumentationBreakpointRequest(EventName);
        }
        /// <summary>
        /// Removes breakpoint on particular native event.
        /// </summary>
        /// <param name="EventName">Instrumentation name to stop on.</param>
        [Core.MethodName("EventBreakpoints.removeInstrumentationBreakpoint")]
        public record RemoveInstrumentationBreakpointRequest(
            string EventName
        ) : Core.ICommand<RemoveInstrumentationBreakpointRequestResult>
        {
        }
        /// <summary>
        /// Removes breakpoint on particular native event.
        /// </summary>
        public record RemoveInstrumentationBreakpointRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Removes all breakpoints
        /// </summary>
        public static EventBreakpoints.DisableRequest Disable()
        {
            return new EventBreakpoints.DisableRequest();
        }
        /// <summary>
        /// Removes all breakpoints
        /// </summary>
        [Core.MethodName("EventBreakpoints.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Removes all breakpoints
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
    }
}
