// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class FedCm
    {
        /// <summary>
        /// Whether this is a sign-up or sign-in action for this account, i.e.<br/>
        /// whether this account has ever been used to sign in to this RP before.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record LoginState(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly LoginState SIGN_IN = new("SignIn");
            public static readonly LoginState SIGN_UP = new("SignUp");
        }
        /// <summary>
        /// The types of FedCM dialogs.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record DialogType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly DialogType ACCOUNT_CHOOSER = new("AccountChooser");
            public static readonly DialogType AUTO_REAUTHN = new("AutoReauthn");
            public static readonly DialogType CONFIRM_IDP_LOGIN = new("ConfirmIdpLogin");
            public static readonly DialogType ERROR = new("Error");
        }
        /// <summary>
        /// The buttons on the FedCM dialog.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record DialogButton(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly DialogButton CONFIRM_IDP_LOGIN_CONTINUE = new("ConfirmIdpLoginContinue");
            public static readonly DialogButton ERROR_GOT_IT = new("ErrorGotIt");
            public static readonly DialogButton ERROR_MORE_DETAILS = new("ErrorMoreDetails");
        }
        /// <summary>
        /// The URLs that each account has
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record AccountUrlType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly AccountUrlType TERMS_OF_SERVICE = new("TermsOfService");
            public static readonly AccountUrlType PRIVACY_POLICY = new("PrivacyPolicy");
        }
        /// <summary>
        /// Corresponds to IdentityRequestAccount
        /// </summary>
        /// <param name="TermsOfServiceUrl">These two are only set if the loginState is signUp</param>
        public record Account(
            string AccountId,
            string Email,
            string Name,
            string GivenName,
            string PictureUrl,
            string IdpConfigUrl,
            string IdpLoginUrl,
            FedCm.LoginState LoginState,
            string? TermsOfServiceUrl = default,
            string? PrivacyPolicyUrl = default
        ) : Core.IType
        {
        }
        /// <param name="DisableRejectionDelay">Allows callers to disable the promise rejection delay that would<br/>
        /// normally happen, if this is unimportant to what&apos;s being tested.<br/>
        /// (step 4 of https://fedidcg.github.io/FedCM/#browser-api-rp-sign-in)</param>
        public static FedCm.EnableRequest Enable(bool? DisableRejectionDelay = default)
        {
            return new FedCm.EnableRequest(DisableRejectionDelay);
        }
        /// <param name="DisableRejectionDelay">Allows callers to disable the promise rejection delay that would<br/>
        /// normally happen, if this is unimportant to what&apos;s being tested.<br/>
        /// (step 4 of https://fedidcg.github.io/FedCM/#browser-api-rp-sign-in)</param>
        [Core.MethodName("FedCm.enable")]
        public record EnableRequest(
            bool? DisableRejectionDelay = default
        ) : Core.ICommand<EnableRequestResult>
        {
        }
        public record EnableRequestResult() : Core.IType
        {
        }
        public static FedCm.DisableRequest Disable()
        {
            return new FedCm.DisableRequest();
        }
        [Core.MethodName("FedCm.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        public record DisableRequestResult() : Core.IType
        {
        }
        public static FedCm.SelectAccountRequest SelectAccount(string DialogId, int AccountIndex)
        {
            return new FedCm.SelectAccountRequest(DialogId, AccountIndex);
        }
        [Core.MethodName("FedCm.selectAccount")]
        public record SelectAccountRequest(
            string DialogId,
            int AccountIndex
        ) : Core.ICommand<SelectAccountRequestResult>
        {
        }
        public record SelectAccountRequestResult() : Core.IType
        {
        }
        public static FedCm.ClickDialogButtonRequest ClickDialogButton(string DialogId, FedCm.DialogButton DialogButton)
        {
            return new FedCm.ClickDialogButtonRequest(DialogId, DialogButton);
        }
        [Core.MethodName("FedCm.clickDialogButton")]
        public record ClickDialogButtonRequest(
            string DialogId,
            FedCm.DialogButton DialogButton
        ) : Core.ICommand<ClickDialogButtonRequestResult>
        {
        }
        public record ClickDialogButtonRequestResult() : Core.IType
        {
        }
        public static FedCm.OpenUrlRequest OpenUrl(string DialogId, int AccountIndex, FedCm.AccountUrlType AccountUrlType)
        {
            return new FedCm.OpenUrlRequest(DialogId, AccountIndex, AccountUrlType);
        }
        [Core.MethodName("FedCm.openUrl")]
        public record OpenUrlRequest(
            string DialogId,
            int AccountIndex,
            FedCm.AccountUrlType AccountUrlType
        ) : Core.ICommand<OpenUrlRequestResult>
        {
        }
        public record OpenUrlRequestResult() : Core.IType
        {
        }
        public static FedCm.DismissDialogRequest DismissDialog(string DialogId, bool? TriggerCooldown = default)
        {
            return new FedCm.DismissDialogRequest(DialogId, TriggerCooldown);
        }
        [Core.MethodName("FedCm.dismissDialog")]
        public record DismissDialogRequest(
            string DialogId,
            bool? TriggerCooldown = default
        ) : Core.ICommand<DismissDialogRequestResult>
        {
        }
        public record DismissDialogRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Resets the cooldown time, if any, to allow the next FedCM call to show<br/>
        /// a dialog even if one was recently dismissed by the user.
        /// </summary>
        public static FedCm.ResetCooldownRequest ResetCooldown()
        {
            return new FedCm.ResetCooldownRequest();
        }
        /// <summary>
        /// Resets the cooldown time, if any, to allow the next FedCM call to show<br/>
        /// a dialog even if one was recently dismissed by the user.
        /// </summary>
        [Core.MethodName("FedCm.resetCooldown")]
        public record ResetCooldownRequest() : Core.ICommand<ResetCooldownRequestResult>
        {
        }
        /// <summary>
        /// Resets the cooldown time, if any, to allow the next FedCM call to show<br/>
        /// a dialog even if one was recently dismissed by the user.
        /// </summary>
        public record ResetCooldownRequestResult() : Core.IType
        {
        }
        /// <param name="Title">These exist primarily so that the caller can verify the<br/>
        /// RP context was used appropriately.</param>
        [Core.MethodName("FedCm.dialogShown")]
        public record DialogShown(
            string DialogId,
            FedCm.DialogType DialogType,
            IReadOnlyList<FedCm.Account> Accounts,
            string Title,
            string? Subtitle = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Triggered when a dialog is closed, either by user action, JS abort,<br/>
        /// or a command below.
        /// </summary>
        [Core.MethodName("FedCm.dialogClosed")]
        public record DialogClosed(
            string DialogId
        ) : Core.IEvent
        {
        }
    }
}
