// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Fetch
    {
        /// <summary>
        /// Unique request identifier.<br/>
        /// Note that this does not identify individual HTTP requests that are part of<br/>
        /// a network request.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record RequestId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Stages of the request to handle. Request will intercept before the request is<br/>
        /// sent. Response will intercept after the response is received (but before response<br/>
        /// body is received).
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record RequestStage(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly RequestStage REQUEST = new("Request");
            public static readonly RequestStage RESPONSE = new("Response");
        }
        /// <param name="UrlPattern">Wildcards (`&apos;*&apos;` -&gt; zero or more, `&apos;?&apos;` -&gt; exactly one) are allowed. Escape character is<br/>
        /// backslash. Omitting is equivalent to `&quot;*&quot;`.</param>
        /// <param name="ResourceType">If set, only requests for matching resource types will be intercepted.</param>
        /// <param name="RequestStage">Stage at which to begin intercepting requests. Default is Request.</param>
        public record RequestPattern(
            string? UrlPattern = default,
            Network.ResourceType? ResourceType = default,
            Fetch.RequestStage? RequestStage = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Response HTTP header entry
        /// </summary>
        public record HeaderEntry(
            string Name,
            string Value
        ) : Core.IType
        {
        }
        /// <summary>
        /// Authorization challenge for HTTP status code 401 or 407.
        /// </summary>
        /// <param name="Origin">Origin of the challenger.</param>
        /// <param name="Scheme">The authentication scheme used, such as basic or digest</param>
        /// <param name="Realm">The realm of the challenge. May be empty.</param>
        /// <param name="Source">Source of the authentication challenge.</param>
        public record AuthChallenge(
            string Origin,
            string Scheme,
            string Realm,
            string? Source = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Response to an AuthChallenge.
        /// </summary>
        /// <param name="Response">The decision on what to do in response to the authorization challenge.  Default means<br/>
        /// deferring to the default behavior of the net stack, which will likely either the Cancel<br/>
        /// authentication or display a popup dialog box.</param>
        /// <param name="Username">The username to provide, possibly empty. Should only be set if response is<br/>
        /// ProvideCredentials.</param>
        /// <param name="Password">The password to provide, possibly empty. Should only be set if response is<br/>
        /// ProvideCredentials.</param>
        public record AuthChallengeResponse(
            string Response,
            string? Username = default,
            string? Password = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Disables the fetch domain.
        /// </summary>
        public static Fetch.DisableRequest Disable()
        {
            return new Fetch.DisableRequest();
        }
        /// <summary>
        /// Disables the fetch domain.
        /// </summary>
        [Core.MethodName("Fetch.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Disables the fetch domain.
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables issuing of requestPaused events. A request will be paused until client<br/>
        /// calls one of failRequest, fulfillRequest or continueRequest/continueWithAuth.
        /// </summary>
        /// <param name="Patterns">If specified, only requests matching any of these patterns will produce<br/>
        /// fetchRequested event and will be paused until clients response. If not set,<br/>
        /// all requests will be affected.</param>
        /// <param name="HandleAuthRequests">If true, authRequired events will be issued and requests will be paused<br/>
        /// expecting a call to continueWithAuth.</param>
        public static Fetch.EnableRequest Enable(IReadOnlyList<Fetch.RequestPattern>? Patterns = default, bool? HandleAuthRequests = default)
        {
            return new Fetch.EnableRequest(Patterns, HandleAuthRequests);
        }
        /// <summary>
        /// Enables issuing of requestPaused events. A request will be paused until client<br/>
        /// calls one of failRequest, fulfillRequest or continueRequest/continueWithAuth.
        /// </summary>
        /// <param name="Patterns">If specified, only requests matching any of these patterns will produce<br/>
        /// fetchRequested event and will be paused until clients response. If not set,<br/>
        /// all requests will be affected.</param>
        /// <param name="HandleAuthRequests">If true, authRequired events will be issued and requests will be paused<br/>
        /// expecting a call to continueWithAuth.</param>
        [Core.MethodName("Fetch.enable")]
        public record EnableRequest(
            IReadOnlyList<Fetch.RequestPattern>? Patterns = default,
            bool? HandleAuthRequests = default
        ) : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables issuing of requestPaused events. A request will be paused until client<br/>
        /// calls one of failRequest, fulfillRequest or continueRequest/continueWithAuth.
        /// </summary>
        public record EnableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Causes the request to fail with specified reason.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="ErrorReason">Causes the request to fail with the given reason.</param>
        public static Fetch.FailRequestRequest FailRequest(Fetch.RequestId RequestId, Network.ErrorReason ErrorReason)
        {
            return new Fetch.FailRequestRequest(RequestId, ErrorReason);
        }
        /// <summary>
        /// Causes the request to fail with specified reason.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="ErrorReason">Causes the request to fail with the given reason.</param>
        [Core.MethodName("Fetch.failRequest")]
        public record FailRequestRequest(
            Fetch.RequestId RequestId,
            Network.ErrorReason ErrorReason
        ) : Core.ICommand<FailRequestRequestResult>
        {
        }
        /// <summary>
        /// Causes the request to fail with specified reason.
        /// </summary>
        public record FailRequestRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Provides response to the request.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="ResponseCode">An HTTP response code.</param>
        /// <param name="ResponseHeaders">Response headers.</param>
        /// <param name="BinaryResponseHeaders">Alternative way of specifying response headers as a \0-separated<br/>
        /// series of name: value pairs. Prefer the above method unless you<br/>
        /// need to represent some non-UTF8 values that can&apos;t be transmitted<br/>
        /// over the protocol as text. (Encoded as a base64 string when passed over JSON)</param>
        /// <param name="Body">A response body. If absent, original response body will be used if<br/>
        /// the request is intercepted at the response stage and empty body<br/>
        /// will be used if the request is intercepted at the request stage. (Encoded as a base64 string when passed over JSON)</param>
        /// <param name="ResponsePhrase">A textual representation of responseCode.<br/>
        /// If absent, a standard phrase matching responseCode is used.</param>
        public static Fetch.FulfillRequestRequest FulfillRequest(Fetch.RequestId RequestId, int ResponseCode, IReadOnlyList<Fetch.HeaderEntry>? ResponseHeaders = default, string? BinaryResponseHeaders = default, string? Body = default, string? ResponsePhrase = default)
        {
            return new Fetch.FulfillRequestRequest(RequestId, ResponseCode, ResponseHeaders, BinaryResponseHeaders, Body, ResponsePhrase);
        }
        /// <summary>
        /// Provides response to the request.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="ResponseCode">An HTTP response code.</param>
        /// <param name="ResponseHeaders">Response headers.</param>
        /// <param name="BinaryResponseHeaders">Alternative way of specifying response headers as a \0-separated<br/>
        /// series of name: value pairs. Prefer the above method unless you<br/>
        /// need to represent some non-UTF8 values that can&apos;t be transmitted<br/>
        /// over the protocol as text. (Encoded as a base64 string when passed over JSON)</param>
        /// <param name="Body">A response body. If absent, original response body will be used if<br/>
        /// the request is intercepted at the response stage and empty body<br/>
        /// will be used if the request is intercepted at the request stage. (Encoded as a base64 string when passed over JSON)</param>
        /// <param name="ResponsePhrase">A textual representation of responseCode.<br/>
        /// If absent, a standard phrase matching responseCode is used.</param>
        [Core.MethodName("Fetch.fulfillRequest")]
        public record FulfillRequestRequest(
            Fetch.RequestId RequestId,
            int ResponseCode,
            IReadOnlyList<Fetch.HeaderEntry>? ResponseHeaders = default,
            string? BinaryResponseHeaders = default,
            string? Body = default,
            string? ResponsePhrase = default
        ) : Core.ICommand<FulfillRequestRequestResult>
        {
        }
        /// <summary>
        /// Provides response to the request.
        /// </summary>
        public record FulfillRequestRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Continues the request, optionally modifying some of its parameters.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="Url">If set, the request url will be modified in a way that&apos;s not observable by page.</param>
        /// <param name="Method">If set, the request method is overridden.</param>
        /// <param name="PostData">If set, overrides the post data in the request. (Encoded as a base64 string when passed over JSON)</param>
        /// <param name="Headers">If set, overrides the request headers. Note that the overrides do not<br/>
        /// extend to subsequent redirect hops, if a redirect happens. Another override<br/>
        /// may be applied to a different request produced by a redirect.</param>
        /// <param name="InterceptResponse">If set, overrides response interception behavior for this request.</param>
        public static Fetch.ContinueRequestRequest ContinueRequest(Fetch.RequestId RequestId, string? Url = default, string? Method = default, string? PostData = default, IReadOnlyList<Fetch.HeaderEntry>? Headers = default, bool? InterceptResponse = default)
        {
            return new Fetch.ContinueRequestRequest(RequestId, Url, Method, PostData, Headers, InterceptResponse);
        }
        /// <summary>
        /// Continues the request, optionally modifying some of its parameters.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="Url">If set, the request url will be modified in a way that&apos;s not observable by page.</param>
        /// <param name="Method">If set, the request method is overridden.</param>
        /// <param name="PostData">If set, overrides the post data in the request. (Encoded as a base64 string when passed over JSON)</param>
        /// <param name="Headers">If set, overrides the request headers. Note that the overrides do not<br/>
        /// extend to subsequent redirect hops, if a redirect happens. Another override<br/>
        /// may be applied to a different request produced by a redirect.</param>
        /// <param name="InterceptResponse">If set, overrides response interception behavior for this request.</param>
        [Core.MethodName("Fetch.continueRequest")]
        public record ContinueRequestRequest(
            Fetch.RequestId RequestId,
            string? Url = default,
            string? Method = default,
            string? PostData = default,
            IReadOnlyList<Fetch.HeaderEntry>? Headers = default,
            bool? InterceptResponse = default
        ) : Core.ICommand<ContinueRequestRequestResult>
        {
        }
        /// <summary>
        /// Continues the request, optionally modifying some of its parameters.
        /// </summary>
        public record ContinueRequestRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Continues a request supplying authChallengeResponse following authRequired event.
        /// </summary>
        /// <param name="RequestId">An id the client received in authRequired event.</param>
        /// <param name="AuthChallengeResponse">Response to  with an authChallenge.</param>
        public static Fetch.ContinueWithAuthRequest ContinueWithAuth(Fetch.RequestId RequestId, Fetch.AuthChallengeResponse AuthChallengeResponse)
        {
            return new Fetch.ContinueWithAuthRequest(RequestId, AuthChallengeResponse);
        }
        /// <summary>
        /// Continues a request supplying authChallengeResponse following authRequired event.
        /// </summary>
        /// <param name="RequestId">An id the client received in authRequired event.</param>
        /// <param name="AuthChallengeResponse">Response to  with an authChallenge.</param>
        [Core.MethodName("Fetch.continueWithAuth")]
        public record ContinueWithAuthRequest(
            Fetch.RequestId RequestId,
            Fetch.AuthChallengeResponse AuthChallengeResponse
        ) : Core.ICommand<ContinueWithAuthRequestResult>
        {
        }
        /// <summary>
        /// Continues a request supplying authChallengeResponse following authRequired event.
        /// </summary>
        public record ContinueWithAuthRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Continues loading of the paused response, optionally modifying the<br/>
        /// response headers. If either responseCode or headers are modified, all of them<br/>
        /// must be present.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="ResponseCode">An HTTP response code. If absent, original response code will be used.</param>
        /// <param name="ResponsePhrase">A textual representation of responseCode.<br/>
        /// If absent, a standard phrase matching responseCode is used.</param>
        /// <param name="ResponseHeaders">Response headers. If absent, original response headers will be used.</param>
        /// <param name="BinaryResponseHeaders">Alternative way of specifying response headers as a \0-separated<br/>
        /// series of name: value pairs. Prefer the above method unless you<br/>
        /// need to represent some non-UTF8 values that can&apos;t be transmitted<br/>
        /// over the protocol as text. (Encoded as a base64 string when passed over JSON)</param>
        public static Fetch.ContinueResponseRequest ContinueResponse(Fetch.RequestId RequestId, int? ResponseCode = default, string? ResponsePhrase = default, IReadOnlyList<Fetch.HeaderEntry>? ResponseHeaders = default, string? BinaryResponseHeaders = default)
        {
            return new Fetch.ContinueResponseRequest(RequestId, ResponseCode, ResponsePhrase, ResponseHeaders, BinaryResponseHeaders);
        }
        /// <summary>
        /// Continues loading of the paused response, optionally modifying the<br/>
        /// response headers. If either responseCode or headers are modified, all of them<br/>
        /// must be present.
        /// </summary>
        /// <param name="RequestId">An id the client received in requestPaused event.</param>
        /// <param name="ResponseCode">An HTTP response code. If absent, original response code will be used.</param>
        /// <param name="ResponsePhrase">A textual representation of responseCode.<br/>
        /// If absent, a standard phrase matching responseCode is used.</param>
        /// <param name="ResponseHeaders">Response headers. If absent, original response headers will be used.</param>
        /// <param name="BinaryResponseHeaders">Alternative way of specifying response headers as a \0-separated<br/>
        /// series of name: value pairs. Prefer the above method unless you<br/>
        /// need to represent some non-UTF8 values that can&apos;t be transmitted<br/>
        /// over the protocol as text. (Encoded as a base64 string when passed over JSON)</param>
        [Core.MethodName("Fetch.continueResponse")]
        public record ContinueResponseRequest(
            Fetch.RequestId RequestId,
            int? ResponseCode = default,
            string? ResponsePhrase = default,
            IReadOnlyList<Fetch.HeaderEntry>? ResponseHeaders = default,
            string? BinaryResponseHeaders = default
        ) : Core.ICommand<ContinueResponseRequestResult>
        {
        }
        /// <summary>
        /// Continues loading of the paused response, optionally modifying the<br/>
        /// response headers. If either responseCode or headers are modified, all of them<br/>
        /// must be present.
        /// </summary>
        public record ContinueResponseRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Causes the body of the response to be received from the server and<br/>
        /// returned as a single string. May only be issued for a request that<br/>
        /// is paused in the Response stage and is mutually exclusive with<br/>
        /// takeResponseBodyForInterceptionAsStream. Calling other methods that<br/>
        /// affect the request or disabling fetch domain before body is received<br/>
        /// results in an undefined behavior.<br/>
        /// Note that the response body is not available for redirects. Requests<br/>
        /// paused in the _redirect received_ state may be differentiated by<br/>
        /// `responseCode` and presence of `location` response header, see<br/>
        /// comments to `requestPaused` for details.
        /// </summary>
        /// <param name="RequestId">Identifier for the intercepted request to get body for.</param>
        public static Fetch.GetResponseBodyRequest GetResponseBody(Fetch.RequestId RequestId)
        {
            return new Fetch.GetResponseBodyRequest(RequestId);
        }
        /// <summary>
        /// Causes the body of the response to be received from the server and<br/>
        /// returned as a single string. May only be issued for a request that<br/>
        /// is paused in the Response stage and is mutually exclusive with<br/>
        /// takeResponseBodyForInterceptionAsStream. Calling other methods that<br/>
        /// affect the request or disabling fetch domain before body is received<br/>
        /// results in an undefined behavior.<br/>
        /// Note that the response body is not available for redirects. Requests<br/>
        /// paused in the _redirect received_ state may be differentiated by<br/>
        /// `responseCode` and presence of `location` response header, see<br/>
        /// comments to `requestPaused` for details.
        /// </summary>
        /// <param name="RequestId">Identifier for the intercepted request to get body for.</param>
        [Core.MethodName("Fetch.getResponseBody")]
        public record GetResponseBodyRequest(
            Fetch.RequestId RequestId
        ) : Core.ICommand<GetResponseBodyRequestResult>
        {
        }
        /// <summary>
        /// Causes the body of the response to be received from the server and<br/>
        /// returned as a single string. May only be issued for a request that<br/>
        /// is paused in the Response stage and is mutually exclusive with<br/>
        /// takeResponseBodyForInterceptionAsStream. Calling other methods that<br/>
        /// affect the request or disabling fetch domain before body is received<br/>
        /// results in an undefined behavior.<br/>
        /// Note that the response body is not available for redirects. Requests<br/>
        /// paused in the _redirect received_ state may be differentiated by<br/>
        /// `responseCode` and presence of `location` response header, see<br/>
        /// comments to `requestPaused` for details.
        /// </summary>
        /// <param name="Body">Response body.</param>
        /// <param name="Base64Encoded">True, if content was sent as base64.</param>
        public record GetResponseBodyRequestResult(
            string Body,
            bool Base64Encoded
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns a handle to the stream representing the response body.<br/>
        /// The request must be paused in the HeadersReceived stage.<br/>
        /// Note that after this command the request can&apos;t be continued<br/>
        /// as is -- client either needs to cancel it or to provide the<br/>
        /// response body.<br/>
        /// The stream only supports sequential read, IO.read will fail if the position<br/>
        /// is specified.<br/>
        /// This method is mutually exclusive with getResponseBody.<br/>
        /// Calling other methods that affect the request or disabling fetch<br/>
        /// domain before body is received results in an undefined behavior.
        /// </summary>
        public static Fetch.TakeResponseBodyAsStreamRequest TakeResponseBodyAsStream(Fetch.RequestId RequestId)
        {
            return new Fetch.TakeResponseBodyAsStreamRequest(RequestId);
        }
        /// <summary>
        /// Returns a handle to the stream representing the response body.<br/>
        /// The request must be paused in the HeadersReceived stage.<br/>
        /// Note that after this command the request can&apos;t be continued<br/>
        /// as is -- client either needs to cancel it or to provide the<br/>
        /// response body.<br/>
        /// The stream only supports sequential read, IO.read will fail if the position<br/>
        /// is specified.<br/>
        /// This method is mutually exclusive with getResponseBody.<br/>
        /// Calling other methods that affect the request or disabling fetch<br/>
        /// domain before body is received results in an undefined behavior.
        /// </summary>
        [Core.MethodName("Fetch.takeResponseBodyAsStream")]
        public record TakeResponseBodyAsStreamRequest(
            Fetch.RequestId RequestId
        ) : Core.ICommand<TakeResponseBodyAsStreamRequestResult>
        {
        }
        /// <summary>
        /// Returns a handle to the stream representing the response body.<br/>
        /// The request must be paused in the HeadersReceived stage.<br/>
        /// Note that after this command the request can&apos;t be continued<br/>
        /// as is -- client either needs to cancel it or to provide the<br/>
        /// response body.<br/>
        /// The stream only supports sequential read, IO.read will fail if the position<br/>
        /// is specified.<br/>
        /// This method is mutually exclusive with getResponseBody.<br/>
        /// Calling other methods that affect the request or disabling fetch<br/>
        /// domain before body is received results in an undefined behavior.
        /// </summary>
        public record TakeResponseBodyAsStreamRequestResult(
            IO.StreamHandle Stream
        ) : Core.IType
        {
        }
        /// <summary>
        /// Issued when the domain is enabled and the request URL matches the<br/>
        /// specified filter. The request is paused until the client responds<br/>
        /// with one of continueRequest, failRequest or fulfillRequest.<br/>
        /// The stage of the request can be determined by presence of responseErrorReason<br/>
        /// and responseStatusCode -- the request is at the response stage if either<br/>
        /// of these fields is present and in the request stage otherwise.<br/>
        /// Redirect responses and subsequent requests are reported similarly to regular<br/>
        /// responses and requests. Redirect responses may be distinguished by the value<br/>
        /// of `responseStatusCode` (which is one of 301, 302, 303, 307, 308) along with<br/>
        /// presence of the `location` header. Requests resulting from a redirect will<br/>
        /// have `redirectedRequestId` field set.
        /// </summary>
        /// <param name="RequestId">Each request the page makes will have a unique id.</param>
        /// <param name="Request">The details of the request.</param>
        /// <param name="FrameId">The id of the frame that initiated the request.</param>
        /// <param name="ResourceType">How the requested resource will be used.</param>
        /// <param name="ResponseErrorReason">Response error if intercepted at response stage.</param>
        /// <param name="ResponseStatusCode">Response code if intercepted at response stage.</param>
        /// <param name="ResponseStatusText">Response status text if intercepted at response stage.</param>
        /// <param name="ResponseHeaders">Response headers if intercepted at the response stage.</param>
        /// <param name="NetworkId">If the intercepted request had a corresponding Network.requestWillBeSent event fired for it,<br/>
        /// then this networkId will be the same as the requestId present in the requestWillBeSent event.</param>
        /// <param name="RedirectedRequestId">If the request is due to a redirect response from the server, the id of the request that<br/>
        /// has caused the redirect.</param>
        [Core.MethodName("Fetch.requestPaused")]
        public record RequestPaused(
            Fetch.RequestId RequestId,
            Network.Request Request,
            Page.FrameId FrameId,
            Network.ResourceType ResourceType,
            Network.ErrorReason? ResponseErrorReason = default,
            int? ResponseStatusCode = default,
            string? ResponseStatusText = default,
            IReadOnlyList<Fetch.HeaderEntry>? ResponseHeaders = default,
            Network.RequestId? NetworkId = default,
            Fetch.RequestId? RedirectedRequestId = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when the domain is enabled with handleAuthRequests set to true.<br/>
        /// The request is paused until client responds with continueWithAuth.
        /// </summary>
        /// <param name="RequestId">Each request the page makes will have a unique id.</param>
        /// <param name="Request">The details of the request.</param>
        /// <param name="FrameId">The id of the frame that initiated the request.</param>
        /// <param name="ResourceType">How the requested resource will be used.</param>
        /// <param name="AuthChallenge">Details of the Authorization Challenge encountered.<br/>
        /// If this is set, client should respond with continueRequest that<br/>
        /// contains AuthChallengeResponse.</param>
        [Core.MethodName("Fetch.authRequired")]
        public record AuthRequired(
            Fetch.RequestId RequestId,
            Network.Request Request,
            Page.FrameId FrameId,
            Network.ResourceType ResourceType,
            Fetch.AuthChallenge AuthChallenge
        ) : Core.IEvent
        {
        }
    }
}
