// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class IO
    {
        /// <summary>
        /// This is either obtained from another method or specified as `blob:&lt;uuid&gt;` where<br/>
        /// `&lt;uuid&gt;` is an UUID of a Blob.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record StreamHandle(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Close the stream, discard any temporary backing storage.
        /// </summary>
        /// <param name="Handle">Handle of the stream to close.</param>
        public static IO.CloseRequest Close(IO.StreamHandle Handle)
        {
            return new IO.CloseRequest(Handle);
        }
        /// <summary>
        /// Close the stream, discard any temporary backing storage.
        /// </summary>
        /// <param name="Handle">Handle of the stream to close.</param>
        [Core.MethodName("IO.close")]
        public record CloseRequest(
            IO.StreamHandle Handle
        ) : Core.ICommand<CloseRequestResult>
        {
        }
        /// <summary>
        /// Close the stream, discard any temporary backing storage.
        /// </summary>
        public record CloseRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Read a chunk of the stream
        /// </summary>
        /// <param name="Handle">Handle of the stream to read.</param>
        /// <param name="Offset">Seek to the specified offset before reading (if not specified, proceed with offset<br/>
        /// following the last read). Some types of streams may only support sequential reads.</param>
        /// <param name="Size">Maximum number of bytes to read (left upon the agent discretion if not specified).</param>
        public static IO.ReadRequest Read(IO.StreamHandle Handle, int? Offset = default, int? Size = default)
        {
            return new IO.ReadRequest(Handle, Offset, Size);
        }
        /// <summary>
        /// Read a chunk of the stream
        /// </summary>
        /// <param name="Handle">Handle of the stream to read.</param>
        /// <param name="Offset">Seek to the specified offset before reading (if not specified, proceed with offset<br/>
        /// following the last read). Some types of streams may only support sequential reads.</param>
        /// <param name="Size">Maximum number of bytes to read (left upon the agent discretion if not specified).</param>
        [Core.MethodName("IO.read")]
        public record ReadRequest(
            IO.StreamHandle Handle,
            int? Offset = default,
            int? Size = default
        ) : Core.ICommand<ReadRequestResult>
        {
        }
        /// <summary>
        /// Read a chunk of the stream
        /// </summary>
        /// <param name="Data">Data that were read.</param>
        /// <param name="Eof">Set if the end-of-file condition occurred while reading.</param>
        /// <param name="Base64Encoded">Set if the data is base64-encoded</param>
        public record ReadRequestResult(
            string Data,
            bool Eof,
            bool? Base64Encoded = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Return UUID of Blob object specified by a remote object id.
        /// </summary>
        /// <param name="ObjectId">Object id of a Blob object wrapper.</param>
        public static IO.ResolveBlobRequest ResolveBlob(Runtime.RemoteObjectId ObjectId)
        {
            return new IO.ResolveBlobRequest(ObjectId);
        }
        /// <summary>
        /// Return UUID of Blob object specified by a remote object id.
        /// </summary>
        /// <param name="ObjectId">Object id of a Blob object wrapper.</param>
        [Core.MethodName("IO.resolveBlob")]
        public record ResolveBlobRequest(
            Runtime.RemoteObjectId ObjectId
        ) : Core.ICommand<ResolveBlobRequestResult>
        {
        }
        /// <summary>
        /// Return UUID of Blob object specified by a remote object id.
        /// </summary>
        /// <param name="Uuid">UUID of the specified Blob.</param>
        public record ResolveBlobRequestResult(
            string Uuid
        ) : Core.IType
        {
        }
    }
}
