// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Memory
    {
        /// <summary>
        /// Memory pressure level.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record PressureLevel(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly PressureLevel MODERATE = new("moderate");
            public static readonly PressureLevel CRITICAL = new("critical");
        }
        /// <summary>
        /// Heap profile sample.
        /// </summary>
        /// <param name="Size">Size of the sampled allocation.</param>
        /// <param name="Total">Total bytes attributed to this sample.</param>
        /// <param name="Stack">Execution stack at the point of allocation.</param>
        public record SamplingProfileNode(
            double Size,
            double Total,
            IReadOnlyList<string> Stack
        ) : Core.IType
        {
        }
        /// <summary>
        /// Array of heap profile samples.
        /// </summary>
        public record SamplingProfile(
            IReadOnlyList<Memory.SamplingProfileNode> Samples,
            IReadOnlyList<Memory.Module> Modules
        ) : Core.IType
        {
        }
        /// <summary>
        /// Executable module information
        /// </summary>
        /// <param name="Name">Name of the module.</param>
        /// <param name="Uuid">UUID of the module.</param>
        /// <param name="BaseAddress">Base address where the module is loaded into memory. Encoded as a decimal<br/>
        /// or hexadecimal (0x prefixed) string.</param>
        /// <param name="Size">Size of the module in bytes.</param>
        public record Module(
            string Name,
            string Uuid,
            string BaseAddress,
            double Size
        ) : Core.IType
        {
        }
        /// <summary>
        /// DOM object counter data.
        /// </summary>
        /// <param name="Name">Object name. Note: object names should be presumed volatile and clients should not expect<br/>
        /// the returned names to be consistent across runs.</param>
        /// <param name="Count">Object count.</param>
        public record DOMCounter(
            string Name,
            int Count
        ) : Core.IType
        {
        }
        /// <summary>
        /// Retruns current DOM object counters.
        /// </summary>
        public static Memory.GetDOMCountersRequest GetDOMCounters()
        {
            return new Memory.GetDOMCountersRequest();
        }
        /// <summary>
        /// Retruns current DOM object counters.
        /// </summary>
        [Core.MethodName("Memory.getDOMCounters")]
        public record GetDOMCountersRequest() : Core.ICommand<GetDOMCountersRequestResult>
        {
        }
        /// <summary>
        /// Retruns current DOM object counters.
        /// </summary>
        public record GetDOMCountersRequestResult(
            int Documents,
            int Nodes,
            int JsEventListeners
        ) : Core.IType
        {
        }
        /// <summary>
        /// Retruns DOM object counters after preparing renderer for leak detection.
        /// </summary>
        public static Memory.GetDOMCountersForLeakDetectionRequest GetDOMCountersForLeakDetection()
        {
            return new Memory.GetDOMCountersForLeakDetectionRequest();
        }
        /// <summary>
        /// Retruns DOM object counters after preparing renderer for leak detection.
        /// </summary>
        [Core.MethodName("Memory.getDOMCountersForLeakDetection")]
        public record GetDOMCountersForLeakDetectionRequest() : Core.ICommand<GetDOMCountersForLeakDetectionRequestResult>
        {
        }
        /// <summary>
        /// Retruns DOM object counters after preparing renderer for leak detection.
        /// </summary>
        /// <param name="Counters">DOM object counters.</param>
        public record GetDOMCountersForLeakDetectionRequestResult(
            IReadOnlyList<Memory.DOMCounter> Counters
        ) : Core.IType
        {
        }
        /// <summary>
        /// Prepares for leak detection by terminating workers, stopping spellcheckers,<br/>
        /// dropping non-essential internal caches, running garbage collections, etc.
        /// </summary>
        public static Memory.PrepareForLeakDetectionRequest PrepareForLeakDetection()
        {
            return new Memory.PrepareForLeakDetectionRequest();
        }
        /// <summary>
        /// Prepares for leak detection by terminating workers, stopping spellcheckers,<br/>
        /// dropping non-essential internal caches, running garbage collections, etc.
        /// </summary>
        [Core.MethodName("Memory.prepareForLeakDetection")]
        public record PrepareForLeakDetectionRequest() : Core.ICommand<PrepareForLeakDetectionRequestResult>
        {
        }
        /// <summary>
        /// Prepares for leak detection by terminating workers, stopping spellcheckers,<br/>
        /// dropping non-essential internal caches, running garbage collections, etc.
        /// </summary>
        public record PrepareForLeakDetectionRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Simulate OomIntervention by purging V8 memory.
        /// </summary>
        public static Memory.ForciblyPurgeJavaScriptMemoryRequest ForciblyPurgeJavaScriptMemory()
        {
            return new Memory.ForciblyPurgeJavaScriptMemoryRequest();
        }
        /// <summary>
        /// Simulate OomIntervention by purging V8 memory.
        /// </summary>
        [Core.MethodName("Memory.forciblyPurgeJavaScriptMemory")]
        public record ForciblyPurgeJavaScriptMemoryRequest() : Core.ICommand<ForciblyPurgeJavaScriptMemoryRequestResult>
        {
        }
        /// <summary>
        /// Simulate OomIntervention by purging V8 memory.
        /// </summary>
        public record ForciblyPurgeJavaScriptMemoryRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enable/disable suppressing memory pressure notifications in all processes.
        /// </summary>
        /// <param name="Suppressed">If true, memory pressure notifications will be suppressed.</param>
        public static Memory.SetPressureNotificationsSuppressedRequest SetPressureNotificationsSuppressed(bool Suppressed)
        {
            return new Memory.SetPressureNotificationsSuppressedRequest(Suppressed);
        }
        /// <summary>
        /// Enable/disable suppressing memory pressure notifications in all processes.
        /// </summary>
        /// <param name="Suppressed">If true, memory pressure notifications will be suppressed.</param>
        [Core.MethodName("Memory.setPressureNotificationsSuppressed")]
        public record SetPressureNotificationsSuppressedRequest(
            bool Suppressed
        ) : Core.ICommand<SetPressureNotificationsSuppressedRequestResult>
        {
        }
        /// <summary>
        /// Enable/disable suppressing memory pressure notifications in all processes.
        /// </summary>
        public record SetPressureNotificationsSuppressedRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Simulate a memory pressure notification in all processes.
        /// </summary>
        /// <param name="Level">Memory pressure level of the notification.</param>
        public static Memory.SimulatePressureNotificationRequest SimulatePressureNotification(Memory.PressureLevel Level)
        {
            return new Memory.SimulatePressureNotificationRequest(Level);
        }
        /// <summary>
        /// Simulate a memory pressure notification in all processes.
        /// </summary>
        /// <param name="Level">Memory pressure level of the notification.</param>
        [Core.MethodName("Memory.simulatePressureNotification")]
        public record SimulatePressureNotificationRequest(
            Memory.PressureLevel Level
        ) : Core.ICommand<SimulatePressureNotificationRequestResult>
        {
        }
        /// <summary>
        /// Simulate a memory pressure notification in all processes.
        /// </summary>
        public record SimulatePressureNotificationRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Start collecting native memory profile.
        /// </summary>
        /// <param name="SamplingInterval">Average number of bytes between samples.</param>
        /// <param name="SuppressRandomness">Do not randomize intervals between samples.</param>
        public static Memory.StartSamplingRequest StartSampling(int? SamplingInterval = default, bool? SuppressRandomness = default)
        {
            return new Memory.StartSamplingRequest(SamplingInterval, SuppressRandomness);
        }
        /// <summary>
        /// Start collecting native memory profile.
        /// </summary>
        /// <param name="SamplingInterval">Average number of bytes between samples.</param>
        /// <param name="SuppressRandomness">Do not randomize intervals between samples.</param>
        [Core.MethodName("Memory.startSampling")]
        public record StartSamplingRequest(
            int? SamplingInterval = default,
            bool? SuppressRandomness = default
        ) : Core.ICommand<StartSamplingRequestResult>
        {
        }
        /// <summary>
        /// Start collecting native memory profile.
        /// </summary>
        public record StartSamplingRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Stop collecting native memory profile.
        /// </summary>
        public static Memory.StopSamplingRequest StopSampling()
        {
            return new Memory.StopSamplingRequest();
        }
        /// <summary>
        /// Stop collecting native memory profile.
        /// </summary>
        [Core.MethodName("Memory.stopSampling")]
        public record StopSamplingRequest() : Core.ICommand<StopSamplingRequestResult>
        {
        }
        /// <summary>
        /// Stop collecting native memory profile.
        /// </summary>
        public record StopSamplingRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Retrieve native memory allocations profile<br/>
        /// collected since renderer process startup.
        /// </summary>
        public static Memory.GetAllTimeSamplingProfileRequest GetAllTimeSamplingProfile()
        {
            return new Memory.GetAllTimeSamplingProfileRequest();
        }
        /// <summary>
        /// Retrieve native memory allocations profile<br/>
        /// collected since renderer process startup.
        /// </summary>
        [Core.MethodName("Memory.getAllTimeSamplingProfile")]
        public record GetAllTimeSamplingProfileRequest() : Core.ICommand<GetAllTimeSamplingProfileRequestResult>
        {
        }
        /// <summary>
        /// Retrieve native memory allocations profile<br/>
        /// collected since renderer process startup.
        /// </summary>
        public record GetAllTimeSamplingProfileRequestResult(
            Memory.SamplingProfile Profile
        ) : Core.IType
        {
        }
        /// <summary>
        /// Retrieve native memory allocations profile<br/>
        /// collected since browser process startup.
        /// </summary>
        public static Memory.GetBrowserSamplingProfileRequest GetBrowserSamplingProfile()
        {
            return new Memory.GetBrowserSamplingProfileRequest();
        }
        /// <summary>
        /// Retrieve native memory allocations profile<br/>
        /// collected since browser process startup.
        /// </summary>
        [Core.MethodName("Memory.getBrowserSamplingProfile")]
        public record GetBrowserSamplingProfileRequest() : Core.ICommand<GetBrowserSamplingProfileRequestResult>
        {
        }
        /// <summary>
        /// Retrieve native memory allocations profile<br/>
        /// collected since browser process startup.
        /// </summary>
        public record GetBrowserSamplingProfileRequestResult(
            Memory.SamplingProfile Profile
        ) : Core.IType
        {
        }
        /// <summary>
        /// Retrieve native memory allocations profile collected since last<br/>
        /// `startSampling` call.
        /// </summary>
        public static Memory.GetSamplingProfileRequest GetSamplingProfile()
        {
            return new Memory.GetSamplingProfileRequest();
        }
        /// <summary>
        /// Retrieve native memory allocations profile collected since last<br/>
        /// `startSampling` call.
        /// </summary>
        [Core.MethodName("Memory.getSamplingProfile")]
        public record GetSamplingProfileRequest() : Core.ICommand<GetSamplingProfileRequestResult>
        {
        }
        /// <summary>
        /// Retrieve native memory allocations profile collected since last<br/>
        /// `startSampling` call.
        /// </summary>
        public record GetSamplingProfileRequestResult(
            Memory.SamplingProfile Profile
        ) : Core.IType
        {
        }
    }
}
