// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Runtime
    {
        /// <summary>
        /// Unique script identifier.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ScriptId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Represents options for serialization. Overrides `generatePreview` and `returnByValue`.
        /// </summary>
        /// <param name="MaxDepth">Deep serialization depth. Default is full depth. Respected only in `deep` serialization mode.</param>
        /// <param name="AdditionalParameters">Embedder-specific parameters. For example if connected to V8 in Chrome these control DOM<br/>
        /// serialization via `maxNodeDepth: integer` and `includeShadowTree: &quot;none&quot; | &quot;open&quot; | &quot;all&quot;`.<br/>
        /// Values can be only of type string or integer.</param>
        public record SerializationOptions(
            string Serialization,
            int? MaxDepth = default,
            JsonObject? AdditionalParameters = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Represents deep serialized value.
        /// </summary>
        /// <param name="WeakLocalObjectReference">Set if value reference met more then once during serialization. In such<br/>
        /// case, value is provided only to one of the serialized values. Unique<br/>
        /// per value in the scope of one CDP call.</param>
        public record DeepSerializedValue(
            string Type,
            JsonNode? Value = default,
            string? ObjectId = default,
            int? WeakLocalObjectReference = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Unique object identifier.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record RemoteObjectId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Primitive value which cannot be JSON-stringified. Includes values `-0`, `NaN`, `Infinity`,<br/>
        /// `-Infinity`, and bigint literals.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record UnserializableValue(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Mirror object referencing original JavaScript object.
        /// </summary>
        /// <param name="Type">Object type.</param>
        /// <param name="Subtype">Object subtype hint. Specified for `object` type values only.<br/>
        /// NOTE: If you change anything here, make sure to also update<br/>
        /// `subtype` in `ObjectPreview` and `PropertyPreview` below.</param>
        /// <param name="ClassName">Object class (constructor) name. Specified for `object` type values only.</param>
        /// <param name="Value">Remote object value in case of primitive values or JSON values (if it was requested).</param>
        /// <param name="UnserializableValue">Primitive value which can not be JSON-stringified does not have `value`, but gets this<br/>
        /// property.</param>
        /// <param name="Description">String representation of the object.</param>
        /// <param name="DeepSerializedValue">Deep serialized value.</param>
        /// <param name="ObjectId">Unique object identifier (for non-primitive values).</param>
        /// <param name="Preview">Preview containing abbreviated property values. Specified for `object` type values only.</param>
        public record RemoteObject(
            string Type,
            string? Subtype = default,
            string? ClassName = default,
            JsonNode? Value = default,
            Runtime.UnserializableValue? UnserializableValue = default,
            string? Description = default,
            Runtime.DeepSerializedValue? DeepSerializedValue = default,
            Runtime.RemoteObjectId? ObjectId = default,
            Runtime.ObjectPreview? Preview = default,
            Runtime.CustomPreview? CustomPreview = default
        ) : Core.IType
        {
        }
        /// <param name="Header">The JSON-stringified result of formatter.header(object, config) call.<br/>
        /// It contains json ML array that represents RemoteObject.</param>
        /// <param name="BodyGetterId">If formatter returns true as a result of formatter.hasBody call then bodyGetterId will<br/>
        /// contain RemoteObjectId for the function that returns result of formatter.body(object, config) call.<br/>
        /// The result value is json ML array.</param>
        public record CustomPreview(
            string Header,
            Runtime.RemoteObjectId? BodyGetterId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Object containing abbreviated remote object value.
        /// </summary>
        /// <param name="Type">Object type.</param>
        /// <param name="Overflow">True iff some of the properties or entries of the original object did not fit.</param>
        /// <param name="Properties">List of the properties.</param>
        /// <param name="Subtype">Object subtype hint. Specified for `object` type values only.</param>
        /// <param name="Description">String representation of the object.</param>
        /// <param name="Entries">List of the entries. Specified for `map` and `set` subtype values only.</param>
        public record ObjectPreview(
            string Type,
            bool Overflow,
            IReadOnlyList<Runtime.PropertyPreview> Properties,
            string? Subtype = default,
            string? Description = default,
            IReadOnlyList<Runtime.EntryPreview>? Entries = default
        ) : Core.IType
        {
        }
        /// <param name="Name">Property name.</param>
        /// <param name="Type">Object type. Accessor means that the property itself is an accessor property.</param>
        /// <param name="Value">User-friendly property value string.</param>
        /// <param name="ValuePreview">Nested value preview.</param>
        /// <param name="Subtype">Object subtype hint. Specified for `object` type values only.</param>
        public record PropertyPreview(
            string Name,
            string Type,
            string? Value = default,
            Runtime.ObjectPreview? ValuePreview = default,
            string? Subtype = default
        ) : Core.IType
        {
        }
        /// <param name="Value">Preview of the value.</param>
        /// <param name="Key">Preview of the key. Specified for map-like collection entries.</param>
        public record EntryPreview(
            Runtime.ObjectPreview Value,
            Runtime.ObjectPreview? Key = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Object property descriptor.
        /// </summary>
        /// <param name="Name">Property name or symbol description.</param>
        /// <param name="Configurable">True if the type of this property descriptor may be changed and if the property may be<br/>
        /// deleted from the corresponding object.</param>
        /// <param name="Enumerable">True if this property shows up during enumeration of the properties on the corresponding<br/>
        /// object.</param>
        /// <param name="Value">The value associated with the property.</param>
        /// <param name="Writable">True if the value associated with the property may be changed (data descriptors only).</param>
        /// <param name="Get">A function which serves as a getter for the property, or `undefined` if there is no getter<br/>
        /// (accessor descriptors only).</param>
        /// <param name="Set">A function which serves as a setter for the property, or `undefined` if there is no setter<br/>
        /// (accessor descriptors only).</param>
        /// <param name="WasThrown">True if the result was thrown during the evaluation.</param>
        /// <param name="IsOwn">True if the property is owned for the object.</param>
        /// <param name="Symbol">Property symbol object, if the property is of the `symbol` type.</param>
        public record PropertyDescriptor(
            string Name,
            bool Configurable,
            bool Enumerable,
            Runtime.RemoteObject? Value = default,
            bool? Writable = default,
            Runtime.RemoteObject? Get = default,
            Runtime.RemoteObject? Set = default,
            bool? WasThrown = default,
            bool? IsOwn = default,
            Runtime.RemoteObject? Symbol = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Object internal property descriptor. This property isn&apos;t normally visible in JavaScript code.
        /// </summary>
        /// <param name="Name">Conventional property name.</param>
        /// <param name="Value">The value associated with the property.</param>
        public record InternalPropertyDescriptor(
            string Name,
            Runtime.RemoteObject? Value = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Object private field descriptor.
        /// </summary>
        /// <param name="Name">Private property name.</param>
        /// <param name="Value">The value associated with the private property.</param>
        /// <param name="Get">A function which serves as a getter for the private property,<br/>
        /// or `undefined` if there is no getter (accessor descriptors only).</param>
        /// <param name="Set">A function which serves as a setter for the private property,<br/>
        /// or `undefined` if there is no setter (accessor descriptors only).</param>
        public record PrivatePropertyDescriptor(
            string Name,
            Runtime.RemoteObject? Value = default,
            Runtime.RemoteObject? Get = default,
            Runtime.RemoteObject? Set = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Represents function call argument. Either remote object id `objectId`, primitive `value`,<br/>
        /// unserializable primitive value or neither of (for undefined) them should be specified.
        /// </summary>
        /// <param name="Value">Primitive value or serializable javascript object.</param>
        /// <param name="UnserializableValue">Primitive value which can not be JSON-stringified.</param>
        /// <param name="ObjectId">Remote object handle.</param>
        public record CallArgument(
            JsonNode? Value = default,
            Runtime.UnserializableValue? UnserializableValue = default,
            Runtime.RemoteObjectId? ObjectId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Id of an execution context.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ExecutionContextId(
            int Value
        ) : Core.PrimitiveType<int>(Value)
        {
        }
        /// <summary>
        /// Description of an isolated world.
        /// </summary>
        /// <param name="Id">Unique id of the execution context. It can be used to specify in which execution context<br/>
        /// script evaluation should be performed.</param>
        /// <param name="Origin">Execution context origin.</param>
        /// <param name="Name">Human readable name describing given context.</param>
        /// <param name="UniqueId">A system-unique execution context identifier. Unlike the id, this is unique across<br/>
        /// multiple processes, so can be reliably used to identify specific context while backend<br/>
        /// performs a cross-process navigation.</param>
        /// <param name="AuxData">Embedder-specific auxiliary data likely matching {isDefault: boolean, type: &apos;default&apos;|&apos;isolated&apos;|&apos;worker&apos;, frameId: string}</param>
        public record ExecutionContextDescription(
            Runtime.ExecutionContextId Id,
            string Origin,
            string Name,
            string UniqueId,
            JsonObject? AuxData = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Detailed information about exception (or error) that was thrown during script compilation or<br/>
        /// execution.
        /// </summary>
        /// <param name="ExceptionId">Exception id.</param>
        /// <param name="Text">Exception text, which should be used together with exception object when available.</param>
        /// <param name="LineNumber">Line number of the exception location (0-based).</param>
        /// <param name="ColumnNumber">Column number of the exception location (0-based).</param>
        /// <param name="ScriptId">Script ID of the exception location.</param>
        /// <param name="Url">URL of the exception location, to be used when the script was not reported.</param>
        /// <param name="StackTrace">JavaScript stack trace if available.</param>
        /// <param name="Exception">Exception object if available.</param>
        /// <param name="ExecutionContextId">Identifier of the context where exception happened.</param>
        /// <param name="ExceptionMetaData">Dictionary with entries of meta data that the client associated<br/>
        /// with this exception, such as information about associated network<br/>
        /// requests, etc.</param>
        public record ExceptionDetails(
            int ExceptionId,
            string Text,
            int LineNumber,
            int ColumnNumber,
            Runtime.ScriptId? ScriptId = default,
            string? Url = default,
            Runtime.StackTrace? StackTrace = default,
            Runtime.RemoteObject? Exception = default,
            Runtime.ExecutionContextId? ExecutionContextId = default,
            JsonObject? ExceptionMetaData = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Number of milliseconds since epoch.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record Timestamp(
            double Value
        ) : Core.PrimitiveType<double>(Value)
        {
        }
        /// <summary>
        /// Number of milliseconds.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record TimeDelta(
            double Value
        ) : Core.PrimitiveType<double>(Value)
        {
        }
        /// <summary>
        /// Stack entry for runtime errors and assertions.
        /// </summary>
        /// <param name="FunctionName">JavaScript function name.</param>
        /// <param name="ScriptId">JavaScript script id.</param>
        /// <param name="Url">JavaScript script name or url.</param>
        /// <param name="LineNumber">JavaScript script line number (0-based).</param>
        /// <param name="ColumnNumber">JavaScript script column number (0-based).</param>
        public record CallFrame(
            string FunctionName,
            Runtime.ScriptId ScriptId,
            string Url,
            int LineNumber,
            int ColumnNumber
        ) : Core.IType
        {
        }
        /// <summary>
        /// Call frames for assertions or error messages.
        /// </summary>
        /// <param name="CallFrames">JavaScript function name.</param>
        /// <param name="Description">String label of this stack trace. For async traces this may be a name of the function that<br/>
        /// initiated the async call.</param>
        /// <param name="Parent">Asynchronous JavaScript stack trace that preceded this stack, if available.</param>
        /// <param name="ParentId">Asynchronous JavaScript stack trace that preceded this stack, if available.</param>
        public record StackTrace(
            IReadOnlyList<Runtime.CallFrame> CallFrames,
            string? Description = default,
            Runtime.StackTrace? Parent = default,
            Runtime.StackTraceId? ParentId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Unique identifier of current debugger.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record UniqueDebuggerId(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// If `debuggerId` is set stack trace comes from another debugger and can be resolved there. This<br/>
        /// allows to track cross-debugger calls. See `Runtime.StackTrace` and `Debugger.paused` for usages.
        /// </summary>
        public record StackTraceId(
            string Id,
            Runtime.UniqueDebuggerId? DebuggerId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Add handler to promise with given promise object id.
        /// </summary>
        /// <param name="PromiseObjectId">Identifier of the promise.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object that should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        public static Runtime.AwaitPromiseRequest AwaitPromise(Runtime.RemoteObjectId PromiseObjectId, bool? ReturnByValue = default, bool? GeneratePreview = default)
        {
            return new Runtime.AwaitPromiseRequest(PromiseObjectId, ReturnByValue, GeneratePreview);
        }
        /// <summary>
        /// Add handler to promise with given promise object id.
        /// </summary>
        /// <param name="PromiseObjectId">Identifier of the promise.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object that should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        [Core.MethodName("Runtime.awaitPromise")]
        public record AwaitPromiseRequest(
            Runtime.RemoteObjectId PromiseObjectId,
            bool? ReturnByValue = default,
            bool? GeneratePreview = default
        ) : Core.ICommand<AwaitPromiseRequestResult>
        {
        }
        /// <summary>
        /// Add handler to promise with given promise object id.
        /// </summary>
        /// <param name="Result">Promise result. Will contain rejected value if promise was rejected.</param>
        /// <param name="ExceptionDetails">Exception details if stack strace is available.</param>
        public record AwaitPromiseRequestResult(
            Runtime.RemoteObject Result,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Calls function with given declaration on the given object. Object group of the result is<br/>
        /// inherited from the target object.
        /// </summary>
        /// <param name="FunctionDeclaration">Declaration of the function to call.</param>
        /// <param name="ObjectId">Identifier of the object to call function on. Either objectId or executionContextId should<br/>
        /// be specified.</param>
        /// <param name="Arguments">Call arguments. All call arguments must belong to the same JavaScript world as the target<br/>
        /// object.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object which should be sent by value.<br/>
        /// Can be overriden by `serializationOptions`.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="UserGesture">Whether execution should be treated as initiated by user in the UI.</param>
        /// <param name="AwaitPromise">Whether execution should `await` for resulting value and return once awaited promise is<br/>
        /// resolved.</param>
        /// <param name="ExecutionContextId">Specifies execution context which global object will be used to call function on. Either<br/>
        /// executionContextId or objectId should be specified.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects. If objectGroup is not<br/>
        /// specified and objectId is, objectGroup will be inherited from object.</param>
        /// <param name="ThrowOnSideEffect">Whether to throw an exception if side effect cannot be ruled out during evaluation.</param>
        /// <param name="UniqueContextId">An alternative way to specify the execution context to call function on.<br/>
        /// Compared to contextId that may be reused across processes, this is guaranteed to be<br/>
        /// system-unique, so it can be used to prevent accidental function call<br/>
        /// in context different than intended (e.g. as a result of navigation across process<br/>
        /// boundaries).<br/>
        /// This is mutually exclusive with `executionContextId`.</param>
        /// <param name="SerializationOptions">Specifies the result serialization. If provided, overrides<br/>
        /// `generatePreview` and `returnByValue`.</param>
        public static Runtime.CallFunctionOnRequest CallFunctionOn(string FunctionDeclaration, Runtime.RemoteObjectId? ObjectId = default, IReadOnlyList<Runtime.CallArgument>? Arguments = default, bool? Silent = default, bool? ReturnByValue = default, bool? GeneratePreview = default, bool? UserGesture = default, bool? AwaitPromise = default, Runtime.ExecutionContextId? ExecutionContextId = default, string? ObjectGroup = default, bool? ThrowOnSideEffect = default, string? UniqueContextId = default, Runtime.SerializationOptions? SerializationOptions = default)
        {
            return new Runtime.CallFunctionOnRequest(FunctionDeclaration, ObjectId, Arguments, Silent, ReturnByValue, GeneratePreview, UserGesture, AwaitPromise, ExecutionContextId, ObjectGroup, ThrowOnSideEffect, UniqueContextId, SerializationOptions);
        }
        /// <summary>
        /// Calls function with given declaration on the given object. Object group of the result is<br/>
        /// inherited from the target object.
        /// </summary>
        /// <param name="FunctionDeclaration">Declaration of the function to call.</param>
        /// <param name="ObjectId">Identifier of the object to call function on. Either objectId or executionContextId should<br/>
        /// be specified.</param>
        /// <param name="Arguments">Call arguments. All call arguments must belong to the same JavaScript world as the target<br/>
        /// object.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object which should be sent by value.<br/>
        /// Can be overriden by `serializationOptions`.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="UserGesture">Whether execution should be treated as initiated by user in the UI.</param>
        /// <param name="AwaitPromise">Whether execution should `await` for resulting value and return once awaited promise is<br/>
        /// resolved.</param>
        /// <param name="ExecutionContextId">Specifies execution context which global object will be used to call function on. Either<br/>
        /// executionContextId or objectId should be specified.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects. If objectGroup is not<br/>
        /// specified and objectId is, objectGroup will be inherited from object.</param>
        /// <param name="ThrowOnSideEffect">Whether to throw an exception if side effect cannot be ruled out during evaluation.</param>
        /// <param name="UniqueContextId">An alternative way to specify the execution context to call function on.<br/>
        /// Compared to contextId that may be reused across processes, this is guaranteed to be<br/>
        /// system-unique, so it can be used to prevent accidental function call<br/>
        /// in context different than intended (e.g. as a result of navigation across process<br/>
        /// boundaries).<br/>
        /// This is mutually exclusive with `executionContextId`.</param>
        /// <param name="SerializationOptions">Specifies the result serialization. If provided, overrides<br/>
        /// `generatePreview` and `returnByValue`.</param>
        [Core.MethodName("Runtime.callFunctionOn")]
        public record CallFunctionOnRequest(
            string FunctionDeclaration,
            Runtime.RemoteObjectId? ObjectId = default,
            IReadOnlyList<Runtime.CallArgument>? Arguments = default,
            bool? Silent = default,
            bool? ReturnByValue = default,
            bool? GeneratePreview = default,
            bool? UserGesture = default,
            bool? AwaitPromise = default,
            Runtime.ExecutionContextId? ExecutionContextId = default,
            string? ObjectGroup = default,
            bool? ThrowOnSideEffect = default,
            string? UniqueContextId = default,
            Runtime.SerializationOptions? SerializationOptions = default
        ) : Core.ICommand<CallFunctionOnRequestResult>
        {
        }
        /// <summary>
        /// Calls function with given declaration on the given object. Object group of the result is<br/>
        /// inherited from the target object.
        /// </summary>
        /// <param name="Result">Call result.</param>
        /// <param name="ExceptionDetails">Exception details.</param>
        public record CallFunctionOnRequestResult(
            Runtime.RemoteObject Result,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Compiles expression.
        /// </summary>
        /// <param name="Expression">Expression to compile.</param>
        /// <param name="SourceURL">Source url to be set for the script.</param>
        /// <param name="PersistScript">Specifies whether the compiled script should be persisted.</param>
        /// <param name="ExecutionContextId">Specifies in which execution context to perform script run. If the parameter is omitted the<br/>
        /// evaluation will be performed in the context of the inspected page.</param>
        public static Runtime.CompileScriptRequest CompileScript(string Expression, string SourceURL, bool PersistScript, Runtime.ExecutionContextId? ExecutionContextId = default)
        {
            return new Runtime.CompileScriptRequest(Expression, SourceURL, PersistScript, ExecutionContextId);
        }
        /// <summary>
        /// Compiles expression.
        /// </summary>
        /// <param name="Expression">Expression to compile.</param>
        /// <param name="SourceURL">Source url to be set for the script.</param>
        /// <param name="PersistScript">Specifies whether the compiled script should be persisted.</param>
        /// <param name="ExecutionContextId">Specifies in which execution context to perform script run. If the parameter is omitted the<br/>
        /// evaluation will be performed in the context of the inspected page.</param>
        [Core.MethodName("Runtime.compileScript")]
        public record CompileScriptRequest(
            string Expression,
            string SourceURL,
            bool PersistScript,
            Runtime.ExecutionContextId? ExecutionContextId = default
        ) : Core.ICommand<CompileScriptRequestResult>
        {
        }
        /// <summary>
        /// Compiles expression.
        /// </summary>
        /// <param name="ScriptId">Id of the script.</param>
        /// <param name="ExceptionDetails">Exception details.</param>
        public record CompileScriptRequestResult(
            Runtime.ScriptId? ScriptId = default,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Disables reporting of execution contexts creation.
        /// </summary>
        public static Runtime.DisableRequest Disable()
        {
            return new Runtime.DisableRequest();
        }
        /// <summary>
        /// Disables reporting of execution contexts creation.
        /// </summary>
        [Core.MethodName("Runtime.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        /// <summary>
        /// Disables reporting of execution contexts creation.
        /// </summary>
        public record DisableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Discards collected exceptions and console API calls.
        /// </summary>
        public static Runtime.DiscardConsoleEntriesRequest DiscardConsoleEntries()
        {
            return new Runtime.DiscardConsoleEntriesRequest();
        }
        /// <summary>
        /// Discards collected exceptions and console API calls.
        /// </summary>
        [Core.MethodName("Runtime.discardConsoleEntries")]
        public record DiscardConsoleEntriesRequest() : Core.ICommand<DiscardConsoleEntriesRequestResult>
        {
        }
        /// <summary>
        /// Discards collected exceptions and console API calls.
        /// </summary>
        public record DiscardConsoleEntriesRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables reporting of execution contexts creation by means of `executionContextCreated` event.<br/>
        /// When the reporting gets enabled the event will be sent immediately for each existing execution<br/>
        /// context.
        /// </summary>
        public static Runtime.EnableRequest Enable()
        {
            return new Runtime.EnableRequest();
        }
        /// <summary>
        /// Enables reporting of execution contexts creation by means of `executionContextCreated` event.<br/>
        /// When the reporting gets enabled the event will be sent immediately for each existing execution<br/>
        /// context.
        /// </summary>
        [Core.MethodName("Runtime.enable")]
        public record EnableRequest() : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables reporting of execution contexts creation by means of `executionContextCreated` event.<br/>
        /// When the reporting gets enabled the event will be sent immediately for each existing execution<br/>
        /// context.
        /// </summary>
        public record EnableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Evaluates expression on global object.
        /// </summary>
        /// <param name="Expression">Expression to evaluate.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects.</param>
        /// <param name="IncludeCommandLineAPI">Determines whether Command Line API should be available during the evaluation.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="ContextId">Specifies in which execution context to perform evaluation. If the parameter is omitted the<br/>
        /// evaluation will be performed in the context of the inspected page.<br/>
        /// This is mutually exclusive with `uniqueContextId`, which offers an<br/>
        /// alternative way to identify the execution context that is more reliable<br/>
        /// in a multi-process environment.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object that should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="UserGesture">Whether execution should be treated as initiated by user in the UI.</param>
        /// <param name="AwaitPromise">Whether execution should `await` for resulting value and return once awaited promise is<br/>
        /// resolved.</param>
        /// <param name="ThrowOnSideEffect">Whether to throw an exception if side effect cannot be ruled out during evaluation.<br/>
        /// This implies `disableBreaks` below.</param>
        /// <param name="Timeout">Terminate execution after timing out (number of milliseconds).</param>
        /// <param name="DisableBreaks">Disable breakpoints during execution.</param>
        /// <param name="ReplMode">Setting this flag to true enables `let` re-declaration and top-level `await`.<br/>
        /// Note that `let` variables can only be re-declared if they originate from<br/>
        /// `replMode` themselves.</param>
        /// <param name="AllowUnsafeEvalBlockedByCSP">The Content Security Policy (CSP) for the target might block &apos;unsafe-eval&apos;<br/>
        /// which includes eval(), Function(), setTimeout() and setInterval()<br/>
        /// when called with non-callable arguments. This flag bypasses CSP for this<br/>
        /// evaluation and allows unsafe-eval. Defaults to true.</param>
        /// <param name="UniqueContextId">An alternative way to specify the execution context to evaluate in.<br/>
        /// Compared to contextId that may be reused across processes, this is guaranteed to be<br/>
        /// system-unique, so it can be used to prevent accidental evaluation of the expression<br/>
        /// in context different than intended (e.g. as a result of navigation across process<br/>
        /// boundaries).<br/>
        /// This is mutually exclusive with `contextId`.</param>
        /// <param name="SerializationOptions">Specifies the result serialization. If provided, overrides<br/>
        /// `generatePreview` and `returnByValue`.</param>
        public static Runtime.EvaluateRequest Evaluate(string Expression, string? ObjectGroup = default, bool? IncludeCommandLineAPI = default, bool? Silent = default, Runtime.ExecutionContextId? ContextId = default, bool? ReturnByValue = default, bool? GeneratePreview = default, bool? UserGesture = default, bool? AwaitPromise = default, bool? ThrowOnSideEffect = default, Runtime.TimeDelta? Timeout = default, bool? DisableBreaks = default, bool? ReplMode = default, bool? AllowUnsafeEvalBlockedByCSP = default, string? UniqueContextId = default, Runtime.SerializationOptions? SerializationOptions = default)
        {
            return new Runtime.EvaluateRequest(Expression, ObjectGroup, IncludeCommandLineAPI, Silent, ContextId, ReturnByValue, GeneratePreview, UserGesture, AwaitPromise, ThrowOnSideEffect, Timeout, DisableBreaks, ReplMode, AllowUnsafeEvalBlockedByCSP, UniqueContextId, SerializationOptions);
        }
        /// <summary>
        /// Evaluates expression on global object.
        /// </summary>
        /// <param name="Expression">Expression to evaluate.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects.</param>
        /// <param name="IncludeCommandLineAPI">Determines whether Command Line API should be available during the evaluation.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="ContextId">Specifies in which execution context to perform evaluation. If the parameter is omitted the<br/>
        /// evaluation will be performed in the context of the inspected page.<br/>
        /// This is mutually exclusive with `uniqueContextId`, which offers an<br/>
        /// alternative way to identify the execution context that is more reliable<br/>
        /// in a multi-process environment.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object that should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="UserGesture">Whether execution should be treated as initiated by user in the UI.</param>
        /// <param name="AwaitPromise">Whether execution should `await` for resulting value and return once awaited promise is<br/>
        /// resolved.</param>
        /// <param name="ThrowOnSideEffect">Whether to throw an exception if side effect cannot be ruled out during evaluation.<br/>
        /// This implies `disableBreaks` below.</param>
        /// <param name="Timeout">Terminate execution after timing out (number of milliseconds).</param>
        /// <param name="DisableBreaks">Disable breakpoints during execution.</param>
        /// <param name="ReplMode">Setting this flag to true enables `let` re-declaration and top-level `await`.<br/>
        /// Note that `let` variables can only be re-declared if they originate from<br/>
        /// `replMode` themselves.</param>
        /// <param name="AllowUnsafeEvalBlockedByCSP">The Content Security Policy (CSP) for the target might block &apos;unsafe-eval&apos;<br/>
        /// which includes eval(), Function(), setTimeout() and setInterval()<br/>
        /// when called with non-callable arguments. This flag bypasses CSP for this<br/>
        /// evaluation and allows unsafe-eval. Defaults to true.</param>
        /// <param name="UniqueContextId">An alternative way to specify the execution context to evaluate in.<br/>
        /// Compared to contextId that may be reused across processes, this is guaranteed to be<br/>
        /// system-unique, so it can be used to prevent accidental evaluation of the expression<br/>
        /// in context different than intended (e.g. as a result of navigation across process<br/>
        /// boundaries).<br/>
        /// This is mutually exclusive with `contextId`.</param>
        /// <param name="SerializationOptions">Specifies the result serialization. If provided, overrides<br/>
        /// `generatePreview` and `returnByValue`.</param>
        [Core.MethodName("Runtime.evaluate")]
        public record EvaluateRequest(
            string Expression,
            string? ObjectGroup = default,
            bool? IncludeCommandLineAPI = default,
            bool? Silent = default,
            Runtime.ExecutionContextId? ContextId = default,
            bool? ReturnByValue = default,
            bool? GeneratePreview = default,
            bool? UserGesture = default,
            bool? AwaitPromise = default,
            bool? ThrowOnSideEffect = default,
            Runtime.TimeDelta? Timeout = default,
            bool? DisableBreaks = default,
            bool? ReplMode = default,
            bool? AllowUnsafeEvalBlockedByCSP = default,
            string? UniqueContextId = default,
            Runtime.SerializationOptions? SerializationOptions = default
        ) : Core.ICommand<EvaluateRequestResult>
        {
        }
        /// <summary>
        /// Evaluates expression on global object.
        /// </summary>
        /// <param name="Result">Evaluation result.</param>
        /// <param name="ExceptionDetails">Exception details.</param>
        public record EvaluateRequestResult(
            Runtime.RemoteObject Result,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the isolate id.
        /// </summary>
        public static Runtime.GetIsolateIdRequest GetIsolateId()
        {
            return new Runtime.GetIsolateIdRequest();
        }
        /// <summary>
        /// Returns the isolate id.
        /// </summary>
        [Core.MethodName("Runtime.getIsolateId")]
        public record GetIsolateIdRequest() : Core.ICommand<GetIsolateIdRequestResult>
        {
        }
        /// <summary>
        /// Returns the isolate id.
        /// </summary>
        /// <param name="Id">The isolate id.</param>
        public record GetIsolateIdRequestResult(
            string Id
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns the JavaScript heap usage.<br/>
        /// It is the total usage of the corresponding isolate not scoped to a particular Runtime.
        /// </summary>
        public static Runtime.GetHeapUsageRequest GetHeapUsage()
        {
            return new Runtime.GetHeapUsageRequest();
        }
        /// <summary>
        /// Returns the JavaScript heap usage.<br/>
        /// It is the total usage of the corresponding isolate not scoped to a particular Runtime.
        /// </summary>
        [Core.MethodName("Runtime.getHeapUsage")]
        public record GetHeapUsageRequest() : Core.ICommand<GetHeapUsageRequestResult>
        {
        }
        /// <summary>
        /// Returns the JavaScript heap usage.<br/>
        /// It is the total usage of the corresponding isolate not scoped to a particular Runtime.
        /// </summary>
        /// <param name="UsedSize">Used JavaScript heap size in bytes.</param>
        /// <param name="TotalSize">Allocated JavaScript heap size in bytes.</param>
        /// <param name="EmbedderHeapUsedSize">Used size in bytes in the embedder&apos;s garbage-collected heap.</param>
        /// <param name="BackingStorageSize">Size in bytes of backing storage for array buffers and external strings.</param>
        public record GetHeapUsageRequestResult(
            double UsedSize,
            double TotalSize,
            double EmbedderHeapUsedSize,
            double BackingStorageSize
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns properties of a given object. Object group of the result is inherited from the target<br/>
        /// object.
        /// </summary>
        /// <param name="ObjectId">Identifier of the object to return properties for.</param>
        /// <param name="OwnProperties">If true, returns properties belonging only to the element itself, not to its prototype<br/>
        /// chain.</param>
        /// <param name="AccessorPropertiesOnly">If true, returns accessor properties (with getter/setter) only; internal properties are not<br/>
        /// returned either.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the results.</param>
        /// <param name="NonIndexedPropertiesOnly">If true, returns non-indexed properties only.</param>
        public static Runtime.GetPropertiesRequest GetProperties(Runtime.RemoteObjectId ObjectId, bool? OwnProperties = default, bool? AccessorPropertiesOnly = default, bool? GeneratePreview = default, bool? NonIndexedPropertiesOnly = default)
        {
            return new Runtime.GetPropertiesRequest(ObjectId, OwnProperties, AccessorPropertiesOnly, GeneratePreview, NonIndexedPropertiesOnly);
        }
        /// <summary>
        /// Returns properties of a given object. Object group of the result is inherited from the target<br/>
        /// object.
        /// </summary>
        /// <param name="ObjectId">Identifier of the object to return properties for.</param>
        /// <param name="OwnProperties">If true, returns properties belonging only to the element itself, not to its prototype<br/>
        /// chain.</param>
        /// <param name="AccessorPropertiesOnly">If true, returns accessor properties (with getter/setter) only; internal properties are not<br/>
        /// returned either.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the results.</param>
        /// <param name="NonIndexedPropertiesOnly">If true, returns non-indexed properties only.</param>
        [Core.MethodName("Runtime.getProperties")]
        public record GetPropertiesRequest(
            Runtime.RemoteObjectId ObjectId,
            bool? OwnProperties = default,
            bool? AccessorPropertiesOnly = default,
            bool? GeneratePreview = default,
            bool? NonIndexedPropertiesOnly = default
        ) : Core.ICommand<GetPropertiesRequestResult>
        {
        }
        /// <summary>
        /// Returns properties of a given object. Object group of the result is inherited from the target<br/>
        /// object.
        /// </summary>
        /// <param name="Result">Object properties.</param>
        /// <param name="InternalProperties">Internal object properties (only of the element itself).</param>
        /// <param name="PrivateProperties">Object private properties.</param>
        /// <param name="ExceptionDetails">Exception details.</param>
        public record GetPropertiesRequestResult(
            IReadOnlyList<Runtime.PropertyDescriptor> Result,
            IReadOnlyList<Runtime.InternalPropertyDescriptor>? InternalProperties = default,
            IReadOnlyList<Runtime.PrivatePropertyDescriptor>? PrivateProperties = default,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns all let, const and class variables from global scope.
        /// </summary>
        /// <param name="ExecutionContextId">Specifies in which execution context to lookup global scope variables.</param>
        public static Runtime.GlobalLexicalScopeNamesRequest GlobalLexicalScopeNames(Runtime.ExecutionContextId? ExecutionContextId = default)
        {
            return new Runtime.GlobalLexicalScopeNamesRequest(ExecutionContextId);
        }
        /// <summary>
        /// Returns all let, const and class variables from global scope.
        /// </summary>
        /// <param name="ExecutionContextId">Specifies in which execution context to lookup global scope variables.</param>
        [Core.MethodName("Runtime.globalLexicalScopeNames")]
        public record GlobalLexicalScopeNamesRequest(
            Runtime.ExecutionContextId? ExecutionContextId = default
        ) : Core.ICommand<GlobalLexicalScopeNamesRequestResult>
        {
        }
        /// <summary>
        /// Returns all let, const and class variables from global scope.
        /// </summary>
        public record GlobalLexicalScopeNamesRequestResult(
            IReadOnlyList<string> Names
        ) : Core.IType
        {
        }
        /// <param name="PrototypeObjectId">Identifier of the prototype to return objects for.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release the results.</param>
        public static Runtime.QueryObjectsRequest QueryObjects(Runtime.RemoteObjectId PrototypeObjectId, string? ObjectGroup = default)
        {
            return new Runtime.QueryObjectsRequest(PrototypeObjectId, ObjectGroup);
        }
        /// <param name="PrototypeObjectId">Identifier of the prototype to return objects for.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release the results.</param>
        [Core.MethodName("Runtime.queryObjects")]
        public record QueryObjectsRequest(
            Runtime.RemoteObjectId PrototypeObjectId,
            string? ObjectGroup = default
        ) : Core.ICommand<QueryObjectsRequestResult>
        {
        }
        /// <param name="Objects">Array with objects.</param>
        public record QueryObjectsRequestResult(
            Runtime.RemoteObject Objects
        ) : Core.IType
        {
        }
        /// <summary>
        /// Releases remote object with given id.
        /// </summary>
        /// <param name="ObjectId">Identifier of the object to release.</param>
        public static Runtime.ReleaseObjectRequest ReleaseObject(Runtime.RemoteObjectId ObjectId)
        {
            return new Runtime.ReleaseObjectRequest(ObjectId);
        }
        /// <summary>
        /// Releases remote object with given id.
        /// </summary>
        /// <param name="ObjectId">Identifier of the object to release.</param>
        [Core.MethodName("Runtime.releaseObject")]
        public record ReleaseObjectRequest(
            Runtime.RemoteObjectId ObjectId
        ) : Core.ICommand<ReleaseObjectRequestResult>
        {
        }
        /// <summary>
        /// Releases remote object with given id.
        /// </summary>
        public record ReleaseObjectRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Releases all remote objects that belong to a given group.
        /// </summary>
        /// <param name="ObjectGroup">Symbolic object group name.</param>
        public static Runtime.ReleaseObjectGroupRequest ReleaseObjectGroup(string ObjectGroup)
        {
            return new Runtime.ReleaseObjectGroupRequest(ObjectGroup);
        }
        /// <summary>
        /// Releases all remote objects that belong to a given group.
        /// </summary>
        /// <param name="ObjectGroup">Symbolic object group name.</param>
        [Core.MethodName("Runtime.releaseObjectGroup")]
        public record ReleaseObjectGroupRequest(
            string ObjectGroup
        ) : Core.ICommand<ReleaseObjectGroupRequestResult>
        {
        }
        /// <summary>
        /// Releases all remote objects that belong to a given group.
        /// </summary>
        public record ReleaseObjectGroupRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Tells inspected instance to run if it was waiting for debugger to attach.
        /// </summary>
        public static Runtime.RunIfWaitingForDebuggerRequest RunIfWaitingForDebugger()
        {
            return new Runtime.RunIfWaitingForDebuggerRequest();
        }
        /// <summary>
        /// Tells inspected instance to run if it was waiting for debugger to attach.
        /// </summary>
        [Core.MethodName("Runtime.runIfWaitingForDebugger")]
        public record RunIfWaitingForDebuggerRequest() : Core.ICommand<RunIfWaitingForDebuggerRequestResult>
        {
        }
        /// <summary>
        /// Tells inspected instance to run if it was waiting for debugger to attach.
        /// </summary>
        public record RunIfWaitingForDebuggerRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Runs script with given id in a given context.
        /// </summary>
        /// <param name="ScriptId">Id of the script to run.</param>
        /// <param name="ExecutionContextId">Specifies in which execution context to perform script run. If the parameter is omitted the<br/>
        /// evaluation will be performed in the context of the inspected page.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="IncludeCommandLineAPI">Determines whether Command Line API should be available during the evaluation.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object which should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="AwaitPromise">Whether execution should `await` for resulting value and return once awaited promise is<br/>
        /// resolved.</param>
        public static Runtime.RunScriptRequest RunScript(Runtime.ScriptId ScriptId, Runtime.ExecutionContextId? ExecutionContextId = default, string? ObjectGroup = default, bool? Silent = default, bool? IncludeCommandLineAPI = default, bool? ReturnByValue = default, bool? GeneratePreview = default, bool? AwaitPromise = default)
        {
            return new Runtime.RunScriptRequest(ScriptId, ExecutionContextId, ObjectGroup, Silent, IncludeCommandLineAPI, ReturnByValue, GeneratePreview, AwaitPromise);
        }
        /// <summary>
        /// Runs script with given id in a given context.
        /// </summary>
        /// <param name="ScriptId">Id of the script to run.</param>
        /// <param name="ExecutionContextId">Specifies in which execution context to perform script run. If the parameter is omitted the<br/>
        /// evaluation will be performed in the context of the inspected page.</param>
        /// <param name="ObjectGroup">Symbolic group name that can be used to release multiple objects.</param>
        /// <param name="Silent">In silent mode exceptions thrown during evaluation are not reported and do not pause<br/>
        /// execution. Overrides `setPauseOnException` state.</param>
        /// <param name="IncludeCommandLineAPI">Determines whether Command Line API should be available during the evaluation.</param>
        /// <param name="ReturnByValue">Whether the result is expected to be a JSON object which should be sent by value.</param>
        /// <param name="GeneratePreview">Whether preview should be generated for the result.</param>
        /// <param name="AwaitPromise">Whether execution should `await` for resulting value and return once awaited promise is<br/>
        /// resolved.</param>
        [Core.MethodName("Runtime.runScript")]
        public record RunScriptRequest(
            Runtime.ScriptId ScriptId,
            Runtime.ExecutionContextId? ExecutionContextId = default,
            string? ObjectGroup = default,
            bool? Silent = default,
            bool? IncludeCommandLineAPI = default,
            bool? ReturnByValue = default,
            bool? GeneratePreview = default,
            bool? AwaitPromise = default
        ) : Core.ICommand<RunScriptRequestResult>
        {
        }
        /// <summary>
        /// Runs script with given id in a given context.
        /// </summary>
        /// <param name="Result">Run result.</param>
        /// <param name="ExceptionDetails">Exception details.</param>
        public record RunScriptRequestResult(
            Runtime.RemoteObject Result,
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Enables or disables async call stacks tracking.
        /// </summary>
        /// <param name="MaxDepth">Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async<br/>
        /// call stacks (default).</param>
        public static Runtime.SetAsyncCallStackDepthRequest SetAsyncCallStackDepth(int MaxDepth)
        {
            return new Runtime.SetAsyncCallStackDepthRequest(MaxDepth);
        }
        /// <summary>
        /// Enables or disables async call stacks tracking.
        /// </summary>
        /// <param name="MaxDepth">Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async<br/>
        /// call stacks (default).</param>
        [Core.MethodName("Runtime.setAsyncCallStackDepth")]
        public record SetAsyncCallStackDepthRequest(
            int MaxDepth
        ) : Core.ICommand<SetAsyncCallStackDepthRequestResult>
        {
        }
        /// <summary>
        /// Enables or disables async call stacks tracking.
        /// </summary>
        public record SetAsyncCallStackDepthRequestResult() : Core.IType
        {
        }
        public static Runtime.SetCustomObjectFormatterEnabledRequest SetCustomObjectFormatterEnabled(bool Enabled)
        {
            return new Runtime.SetCustomObjectFormatterEnabledRequest(Enabled);
        }
        [Core.MethodName("Runtime.setCustomObjectFormatterEnabled")]
        public record SetCustomObjectFormatterEnabledRequest(
            bool Enabled
        ) : Core.ICommand<SetCustomObjectFormatterEnabledRequestResult>
        {
        }
        public record SetCustomObjectFormatterEnabledRequestResult() : Core.IType
        {
        }
        public static Runtime.SetMaxCallStackSizeToCaptureRequest SetMaxCallStackSizeToCapture(int Size)
        {
            return new Runtime.SetMaxCallStackSizeToCaptureRequest(Size);
        }
        [Core.MethodName("Runtime.setMaxCallStackSizeToCapture")]
        public record SetMaxCallStackSizeToCaptureRequest(
            int Size
        ) : Core.ICommand<SetMaxCallStackSizeToCaptureRequestResult>
        {
        }
        public record SetMaxCallStackSizeToCaptureRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Terminate current or next JavaScript execution.<br/>
        /// Will cancel the termination when the outer-most script execution ends.
        /// </summary>
        public static Runtime.TerminateExecutionRequest TerminateExecution()
        {
            return new Runtime.TerminateExecutionRequest();
        }
        /// <summary>
        /// Terminate current or next JavaScript execution.<br/>
        /// Will cancel the termination when the outer-most script execution ends.
        /// </summary>
        [Core.MethodName("Runtime.terminateExecution")]
        public record TerminateExecutionRequest() : Core.ICommand<TerminateExecutionRequestResult>
        {
        }
        /// <summary>
        /// Terminate current or next JavaScript execution.<br/>
        /// Will cancel the termination when the outer-most script execution ends.
        /// </summary>
        public record TerminateExecutionRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// If executionContextId is empty, adds binding with the given name on the<br/>
        /// global objects of all inspected contexts, including those created later,<br/>
        /// bindings survive reloads.<br/>
        /// Binding function takes exactly one argument, this argument should be string,<br/>
        /// in case of any other input, function throws an exception.<br/>
        /// Each binding function call produces Runtime.bindingCalled notification.
        /// </summary>
        /// <param name="ExecutionContextId">If specified, the binding would only be exposed to the specified<br/>
        /// execution context. If omitted and `executionContextName` is not set,<br/>
        /// the binding is exposed to all execution contexts of the target.<br/>
        /// This parameter is mutually exclusive with `executionContextName`.<br/>
        /// Deprecated in favor of `executionContextName` due to an unclear use case<br/>
        /// and bugs in implementation (crbug.com/1169639). `executionContextId` will be<br/>
        /// removed in the future.</param>
        /// <param name="ExecutionContextName">If specified, the binding is exposed to the executionContext with<br/>
        /// matching name, even for contexts created after the binding is added.<br/>
        /// See also `ExecutionContext.name` and `worldName` parameter to<br/>
        /// `Page.addScriptToEvaluateOnNewDocument`.<br/>
        /// This parameter is mutually exclusive with `executionContextId`.</param>
        public static Runtime.AddBindingRequest AddBinding(string Name, Runtime.ExecutionContextId? ExecutionContextId = default, string? ExecutionContextName = default)
        {
            return new Runtime.AddBindingRequest(Name, ExecutionContextId, ExecutionContextName);
        }
        /// <summary>
        /// If executionContextId is empty, adds binding with the given name on the<br/>
        /// global objects of all inspected contexts, including those created later,<br/>
        /// bindings survive reloads.<br/>
        /// Binding function takes exactly one argument, this argument should be string,<br/>
        /// in case of any other input, function throws an exception.<br/>
        /// Each binding function call produces Runtime.bindingCalled notification.
        /// </summary>
        /// <param name="ExecutionContextId">If specified, the binding would only be exposed to the specified<br/>
        /// execution context. If omitted and `executionContextName` is not set,<br/>
        /// the binding is exposed to all execution contexts of the target.<br/>
        /// This parameter is mutually exclusive with `executionContextName`.<br/>
        /// Deprecated in favor of `executionContextName` due to an unclear use case<br/>
        /// and bugs in implementation (crbug.com/1169639). `executionContextId` will be<br/>
        /// removed in the future.</param>
        /// <param name="ExecutionContextName">If specified, the binding is exposed to the executionContext with<br/>
        /// matching name, even for contexts created after the binding is added.<br/>
        /// See also `ExecutionContext.name` and `worldName` parameter to<br/>
        /// `Page.addScriptToEvaluateOnNewDocument`.<br/>
        /// This parameter is mutually exclusive with `executionContextId`.</param>
        [Core.MethodName("Runtime.addBinding")]
        public record AddBindingRequest(
            string Name,
            Runtime.ExecutionContextId? ExecutionContextId = default,
            string? ExecutionContextName = default
        ) : Core.ICommand<AddBindingRequestResult>
        {
        }
        /// <summary>
        /// If executionContextId is empty, adds binding with the given name on the<br/>
        /// global objects of all inspected contexts, including those created later,<br/>
        /// bindings survive reloads.<br/>
        /// Binding function takes exactly one argument, this argument should be string,<br/>
        /// in case of any other input, function throws an exception.<br/>
        /// Each binding function call produces Runtime.bindingCalled notification.
        /// </summary>
        public record AddBindingRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// This method does not remove binding function from global object but<br/>
        /// unsubscribes current runtime agent from Runtime.bindingCalled notifications.
        /// </summary>
        public static Runtime.RemoveBindingRequest RemoveBinding(string Name)
        {
            return new Runtime.RemoveBindingRequest(Name);
        }
        /// <summary>
        /// This method does not remove binding function from global object but<br/>
        /// unsubscribes current runtime agent from Runtime.bindingCalled notifications.
        /// </summary>
        [Core.MethodName("Runtime.removeBinding")]
        public record RemoveBindingRequest(
            string Name
        ) : Core.ICommand<RemoveBindingRequestResult>
        {
        }
        /// <summary>
        /// This method does not remove binding function from global object but<br/>
        /// unsubscribes current runtime agent from Runtime.bindingCalled notifications.
        /// </summary>
        public record RemoveBindingRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// This method tries to lookup and populate exception details for a<br/>
        /// JavaScript Error object.<br/>
        /// Note that the stackTrace portion of the resulting exceptionDetails will<br/>
        /// only be populated if the Runtime domain was enabled at the time when the<br/>
        /// Error was thrown.
        /// </summary>
        /// <param name="ErrorObjectId">The error object for which to resolve the exception details.</param>
        public static Runtime.GetExceptionDetailsRequest GetExceptionDetails(Runtime.RemoteObjectId ErrorObjectId)
        {
            return new Runtime.GetExceptionDetailsRequest(ErrorObjectId);
        }
        /// <summary>
        /// This method tries to lookup and populate exception details for a<br/>
        /// JavaScript Error object.<br/>
        /// Note that the stackTrace portion of the resulting exceptionDetails will<br/>
        /// only be populated if the Runtime domain was enabled at the time when the<br/>
        /// Error was thrown.
        /// </summary>
        /// <param name="ErrorObjectId">The error object for which to resolve the exception details.</param>
        [Core.MethodName("Runtime.getExceptionDetails")]
        public record GetExceptionDetailsRequest(
            Runtime.RemoteObjectId ErrorObjectId
        ) : Core.ICommand<GetExceptionDetailsRequestResult>
        {
        }
        /// <summary>
        /// This method tries to lookup and populate exception details for a<br/>
        /// JavaScript Error object.<br/>
        /// Note that the stackTrace portion of the resulting exceptionDetails will<br/>
        /// only be populated if the Runtime domain was enabled at the time when the<br/>
        /// Error was thrown.
        /// </summary>
        public record GetExceptionDetailsRequestResult(
            Runtime.ExceptionDetails? ExceptionDetails = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Notification is issued every time when binding is called.
        /// </summary>
        /// <param name="ExecutionContextId">Identifier of the context where the call was made.</param>
        [Core.MethodName("Runtime.bindingCalled")]
        public record BindingCalled(
            string Name,
            string Payload,
            Runtime.ExecutionContextId ExecutionContextId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when console API was called.
        /// </summary>
        /// <param name="Type">Type of the call.</param>
        /// <param name="Args">Call arguments.</param>
        /// <param name="ExecutionContextId">Identifier of the context where the call was made.</param>
        /// <param name="Timestamp">Call timestamp.</param>
        /// <param name="StackTrace">Stack trace captured when the call was made. The async stack chain is automatically reported for<br/>
        /// the following call types: `assert`, `error`, `trace`, `warning`. For other types the async call<br/>
        /// chain can be retrieved using `Debugger.getStackTrace` and `stackTrace.parentId` field.</param>
        /// <param name="Context">Console context descriptor for calls on non-default console context (not console.*):<br/>
        /// &apos;anonymous#unique-logger-id&apos; for call on unnamed context, &apos;name#unique-logger-id&apos; for call<br/>
        /// on named context.</param>
        [Core.MethodName("Runtime.consoleAPICalled")]
        public record ConsoleAPICalled(
            string Type,
            IReadOnlyList<Runtime.RemoteObject> Args,
            Runtime.ExecutionContextId ExecutionContextId,
            Runtime.Timestamp Timestamp,
            Runtime.StackTrace? StackTrace = default,
            string? Context = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when unhandled exception was revoked.
        /// </summary>
        /// <param name="Reason">Reason describing why exception was revoked.</param>
        /// <param name="ExceptionId">The id of revoked exception, as reported in `exceptionThrown`.</param>
        [Core.MethodName("Runtime.exceptionRevoked")]
        public record ExceptionRevoked(
            string Reason,
            int ExceptionId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when exception was thrown and unhandled.
        /// </summary>
        /// <param name="Timestamp">Timestamp of the exception.</param>
        [Core.MethodName("Runtime.exceptionThrown")]
        public record ExceptionThrown(
            Runtime.Timestamp Timestamp,
            Runtime.ExceptionDetails ExceptionDetails
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when new execution context is created.
        /// </summary>
        /// <param name="Context">A newly created execution context.</param>
        [Core.MethodName("Runtime.executionContextCreated")]
        public record ExecutionContextCreated(
            Runtime.ExecutionContextDescription Context
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when execution context is destroyed.
        /// </summary>
        /// <param name="ExecutionContextId">Id of the destroyed context</param>
        /// <param name="ExecutionContextUniqueId">Unique Id of the destroyed context</param>
        [Core.MethodName("Runtime.executionContextDestroyed")]
        public record ExecutionContextDestroyed(
            Runtime.ExecutionContextId ExecutionContextId,
            string ExecutionContextUniqueId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when all executionContexts were cleared in browser
        /// </summary>
        [Core.MethodName("Runtime.executionContextsCleared")]
        public record ExecutionContextsCleared(
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when object should be inspected (for example, as a result of inspect() command line API<br/>
        /// call).
        /// </summary>
        /// <param name="ExecutionContextId">Identifier of the context where the call was made.</param>
        [Core.MethodName("Runtime.inspectRequested")]
        public record InspectRequested(
            Runtime.RemoteObject Object,
            JsonObject Hints,
            Runtime.ExecutionContextId? ExecutionContextId = default
        ) : Core.IEvent
        {
        }
    }
}
