// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class ServiceWorker
    {
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record RegistrationID(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// ServiceWorker registration.
        /// </summary>
        public record ServiceWorkerRegistration(
            ServiceWorker.RegistrationID RegistrationId,
            string ScopeURL,
            bool IsDeleted
        ) : Core.IType
        {
        }
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ServiceWorkerVersionRunningStatus(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly ServiceWorkerVersionRunningStatus STOPPED = new("stopped");
            public static readonly ServiceWorkerVersionRunningStatus STARTING = new("starting");
            public static readonly ServiceWorkerVersionRunningStatus RUNNING = new("running");
            public static readonly ServiceWorkerVersionRunningStatus STOPPING = new("stopping");
        }
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ServiceWorkerVersionStatus(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly ServiceWorkerVersionStatus NEW = new("new");
            public static readonly ServiceWorkerVersionStatus INSTALLING = new("installing");
            public static readonly ServiceWorkerVersionStatus INSTALLED = new("installed");
            public static readonly ServiceWorkerVersionStatus ACTIVATING = new("activating");
            public static readonly ServiceWorkerVersionStatus ACTIVATED = new("activated");
            public static readonly ServiceWorkerVersionStatus REDUNDANT = new("redundant");
        }
        /// <summary>
        /// ServiceWorker version.
        /// </summary>
        /// <param name="ScriptLastModified">The Last-Modified header value of the main script.</param>
        /// <param name="ScriptResponseTime">The time at which the response headers of the main script were received from the server.<br/>
        /// For cached script it is the last time the cache entry was validated.</param>
        public record ServiceWorkerVersion(
            string VersionId,
            ServiceWorker.RegistrationID RegistrationId,
            string ScriptURL,
            ServiceWorker.ServiceWorkerVersionRunningStatus RunningStatus,
            ServiceWorker.ServiceWorkerVersionStatus Status,
            double? ScriptLastModified = default,
            double? ScriptResponseTime = default,
            IReadOnlyList<Target.TargetID>? ControlledClients = default,
            Target.TargetID? TargetId = default,
            string? RouterRules = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// ServiceWorker error message.
        /// </summary>
        public record ServiceWorkerErrorMessage(
            string ErrorMessage,
            ServiceWorker.RegistrationID RegistrationId,
            string VersionId,
            string SourceURL,
            int LineNumber,
            int ColumnNumber
        ) : Core.IType
        {
        }
        public static ServiceWorker.DeliverPushMessageRequest DeliverPushMessage(string Origin, ServiceWorker.RegistrationID RegistrationId, string Data)
        {
            return new ServiceWorker.DeliverPushMessageRequest(Origin, RegistrationId, Data);
        }
        [Core.MethodName("ServiceWorker.deliverPushMessage")]
        public record DeliverPushMessageRequest(
            string Origin,
            ServiceWorker.RegistrationID RegistrationId,
            string Data
        ) : Core.ICommand<DeliverPushMessageRequestResult>
        {
        }
        public record DeliverPushMessageRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.DisableRequest Disable()
        {
            return new ServiceWorker.DisableRequest();
        }
        [Core.MethodName("ServiceWorker.disable")]
        public record DisableRequest() : Core.ICommand<DisableRequestResult>
        {
        }
        public record DisableRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.DispatchSyncEventRequest DispatchSyncEvent(string Origin, ServiceWorker.RegistrationID RegistrationId, string Tag, bool LastChance)
        {
            return new ServiceWorker.DispatchSyncEventRequest(Origin, RegistrationId, Tag, LastChance);
        }
        [Core.MethodName("ServiceWorker.dispatchSyncEvent")]
        public record DispatchSyncEventRequest(
            string Origin,
            ServiceWorker.RegistrationID RegistrationId,
            string Tag,
            bool LastChance
        ) : Core.ICommand<DispatchSyncEventRequestResult>
        {
        }
        public record DispatchSyncEventRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.DispatchPeriodicSyncEventRequest DispatchPeriodicSyncEvent(string Origin, ServiceWorker.RegistrationID RegistrationId, string Tag)
        {
            return new ServiceWorker.DispatchPeriodicSyncEventRequest(Origin, RegistrationId, Tag);
        }
        [Core.MethodName("ServiceWorker.dispatchPeriodicSyncEvent")]
        public record DispatchPeriodicSyncEventRequest(
            string Origin,
            ServiceWorker.RegistrationID RegistrationId,
            string Tag
        ) : Core.ICommand<DispatchPeriodicSyncEventRequestResult>
        {
        }
        public record DispatchPeriodicSyncEventRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.EnableRequest Enable()
        {
            return new ServiceWorker.EnableRequest();
        }
        [Core.MethodName("ServiceWorker.enable")]
        public record EnableRequest() : Core.ICommand<EnableRequestResult>
        {
        }
        public record EnableRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.SetForceUpdateOnPageLoadRequest SetForceUpdateOnPageLoad(bool ForceUpdateOnPageLoad)
        {
            return new ServiceWorker.SetForceUpdateOnPageLoadRequest(ForceUpdateOnPageLoad);
        }
        [Core.MethodName("ServiceWorker.setForceUpdateOnPageLoad")]
        public record SetForceUpdateOnPageLoadRequest(
            bool ForceUpdateOnPageLoad
        ) : Core.ICommand<SetForceUpdateOnPageLoadRequestResult>
        {
        }
        public record SetForceUpdateOnPageLoadRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.SkipWaitingRequest SkipWaiting(string ScopeURL)
        {
            return new ServiceWorker.SkipWaitingRequest(ScopeURL);
        }
        [Core.MethodName("ServiceWorker.skipWaiting")]
        public record SkipWaitingRequest(
            string ScopeURL
        ) : Core.ICommand<SkipWaitingRequestResult>
        {
        }
        public record SkipWaitingRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.StartWorkerRequest StartWorker(string ScopeURL)
        {
            return new ServiceWorker.StartWorkerRequest(ScopeURL);
        }
        [Core.MethodName("ServiceWorker.startWorker")]
        public record StartWorkerRequest(
            string ScopeURL
        ) : Core.ICommand<StartWorkerRequestResult>
        {
        }
        public record StartWorkerRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.StopAllWorkersRequest StopAllWorkers()
        {
            return new ServiceWorker.StopAllWorkersRequest();
        }
        [Core.MethodName("ServiceWorker.stopAllWorkers")]
        public record StopAllWorkersRequest() : Core.ICommand<StopAllWorkersRequestResult>
        {
        }
        public record StopAllWorkersRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.StopWorkerRequest StopWorker(string VersionId)
        {
            return new ServiceWorker.StopWorkerRequest(VersionId);
        }
        [Core.MethodName("ServiceWorker.stopWorker")]
        public record StopWorkerRequest(
            string VersionId
        ) : Core.ICommand<StopWorkerRequestResult>
        {
        }
        public record StopWorkerRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.UnregisterRequest Unregister(string ScopeURL)
        {
            return new ServiceWorker.UnregisterRequest(ScopeURL);
        }
        [Core.MethodName("ServiceWorker.unregister")]
        public record UnregisterRequest(
            string ScopeURL
        ) : Core.ICommand<UnregisterRequestResult>
        {
        }
        public record UnregisterRequestResult() : Core.IType
        {
        }
        public static ServiceWorker.UpdateRegistrationRequest UpdateRegistration(string ScopeURL)
        {
            return new ServiceWorker.UpdateRegistrationRequest(ScopeURL);
        }
        [Core.MethodName("ServiceWorker.updateRegistration")]
        public record UpdateRegistrationRequest(
            string ScopeURL
        ) : Core.ICommand<UpdateRegistrationRequestResult>
        {
        }
        public record UpdateRegistrationRequestResult() : Core.IType
        {
        }
        [Core.MethodName("ServiceWorker.workerErrorReported")]
        public record WorkerErrorReported(
            ServiceWorker.ServiceWorkerErrorMessage ErrorMessage
        ) : Core.IEvent
        {
        }
        [Core.MethodName("ServiceWorker.workerRegistrationUpdated")]
        public record WorkerRegistrationUpdated(
            IReadOnlyList<ServiceWorker.ServiceWorkerRegistration> Registrations
        ) : Core.IEvent
        {
        }
        [Core.MethodName("ServiceWorker.workerVersionUpdated")]
        public record WorkerVersionUpdated(
            IReadOnlyList<ServiceWorker.ServiceWorkerVersion> Versions
        ) : Core.IEvent
        {
        }
    }
}
