// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class SystemInfo
    {
        /// <summary>
        /// Describes a single graphics processor (GPU).
        /// </summary>
        /// <param name="VendorId">PCI ID of the GPU vendor, if available; 0 otherwise.</param>
        /// <param name="DeviceId">PCI ID of the GPU device, if available; 0 otherwise.</param>
        /// <param name="VendorString">String description of the GPU vendor, if the PCI ID is not available.</param>
        /// <param name="DeviceString">String description of the GPU device, if the PCI ID is not available.</param>
        /// <param name="DriverVendor">String description of the GPU driver vendor.</param>
        /// <param name="DriverVersion">String description of the GPU driver version.</param>
        /// <param name="SubSysId">Sub sys ID of the GPU, only available on Windows.</param>
        /// <param name="Revision">Revision of the GPU, only available on Windows.</param>
        public record GPUDevice(
            double VendorId,
            double DeviceId,
            string VendorString,
            string DeviceString,
            string DriverVendor,
            string DriverVersion,
            double? SubSysId = default,
            double? Revision = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Describes the width and height dimensions of an entity.
        /// </summary>
        /// <param name="Width">Width in pixels.</param>
        /// <param name="Height">Height in pixels.</param>
        public record Size(
            int Width,
            int Height
        ) : Core.IType
        {
        }
        /// <summary>
        /// Describes a supported video decoding profile with its associated minimum and<br/>
        /// maximum resolutions.
        /// </summary>
        /// <param name="Profile">Video codec profile that is supported, e.g. VP9 Profile 2.</param>
        /// <param name="MaxResolution">Maximum video dimensions in pixels supported for this |profile|.</param>
        /// <param name="MinResolution">Minimum video dimensions in pixels supported for this |profile|.</param>
        public record VideoDecodeAcceleratorCapability(
            string Profile,
            SystemInfo.Size MaxResolution,
            SystemInfo.Size MinResolution
        ) : Core.IType
        {
        }
        /// <summary>
        /// Describes a supported video encoding profile with its associated maximum<br/>
        /// resolution and maximum framerate.
        /// </summary>
        /// <param name="Profile">Video codec profile that is supported, e.g H264 Main.</param>
        /// <param name="MaxResolution">Maximum video dimensions in pixels supported for this |profile|.</param>
        /// <param name="MaxFramerateNumerator">Maximum encoding framerate in frames per second supported for this<br/>
        /// |profile|, as fraction&apos;s numerator and denominator, e.g. 24/1 fps,<br/>
        /// 24000/1001 fps, etc.</param>
        public record VideoEncodeAcceleratorCapability(
            string Profile,
            SystemInfo.Size MaxResolution,
            int MaxFramerateNumerator,
            int MaxFramerateDenominator
        ) : Core.IType
        {
        }
        /// <summary>
        /// YUV subsampling type of the pixels of a given image.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record SubsamplingFormat(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly SubsamplingFormat YUV420 = new("yuv420");
            public static readonly SubsamplingFormat YUV422 = new("yuv422");
            public static readonly SubsamplingFormat YUV444 = new("yuv444");
        }
        /// <summary>
        /// Image format of a given image.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record ImageType(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly ImageType JPEG = new("jpeg");
            public static readonly ImageType WEBP = new("webp");
            public static readonly ImageType UNKNOWN = new("unknown");
        }
        /// <summary>
        /// Provides information about the GPU(s) on the system.
        /// </summary>
        /// <param name="Devices">The graphics devices on the system. Element 0 is the primary GPU.</param>
        /// <param name="DriverBugWorkarounds">An optional array of GPU driver bug workarounds.</param>
        /// <param name="VideoDecoding">Supported accelerated video decoding capabilities.</param>
        /// <param name="VideoEncoding">Supported accelerated video encoding capabilities.</param>
        /// <param name="AuxAttributes">An optional dictionary of additional GPU related attributes.</param>
        /// <param name="FeatureStatus">An optional dictionary of graphics features and their status.</param>
        public record GPUInfo(
            IReadOnlyList<SystemInfo.GPUDevice> Devices,
            IReadOnlyList<string> DriverBugWorkarounds,
            IReadOnlyList<SystemInfo.VideoDecodeAcceleratorCapability> VideoDecoding,
            IReadOnlyList<SystemInfo.VideoEncodeAcceleratorCapability> VideoEncoding,
            JsonObject? AuxAttributes = default,
            JsonObject? FeatureStatus = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Represents process info.
        /// </summary>
        /// <param name="Type">Specifies process type.</param>
        /// <param name="Id">Specifies process id.</param>
        /// <param name="CpuTime">Specifies cumulative CPU usage in seconds across all threads of the<br/>
        /// process since the process start.</param>
        public record ProcessInfo(
            string Type,
            int Id,
            double CpuTime
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns information about the system.
        /// </summary>
        public static SystemInfo.GetInfoRequest GetInfo()
        {
            return new SystemInfo.GetInfoRequest();
        }
        /// <summary>
        /// Returns information about the system.
        /// </summary>
        [Core.MethodName("SystemInfo.getInfo")]
        public record GetInfoRequest() : Core.ICommand<GetInfoRequestResult>
        {
        }
        /// <summary>
        /// Returns information about the system.
        /// </summary>
        /// <param name="Gpu">Information about the GPUs on the system.</param>
        /// <param name="ModelName">A platform-dependent description of the model of the machine. On Mac OS, this is, for<br/>
        /// example, &apos;MacBookPro&apos;. Will be the empty string if not supported.</param>
        /// <param name="ModelVersion">A platform-dependent description of the version of the machine. On Mac OS, this is, for<br/>
        /// example, &apos;10.1&apos;. Will be the empty string if not supported.</param>
        /// <param name="CommandLine">The command line string used to launch the browser. Will be the empty string if not<br/>
        /// supported.</param>
        public record GetInfoRequestResult(
            SystemInfo.GPUInfo Gpu,
            string ModelName,
            string ModelVersion,
            string CommandLine
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns information about the feature state.
        /// </summary>
        public static SystemInfo.GetFeatureStateRequest GetFeatureState(string FeatureState)
        {
            return new SystemInfo.GetFeatureStateRequest(FeatureState);
        }
        /// <summary>
        /// Returns information about the feature state.
        /// </summary>
        [Core.MethodName("SystemInfo.getFeatureState")]
        public record GetFeatureStateRequest(
            string FeatureState
        ) : Core.ICommand<GetFeatureStateRequestResult>
        {
        }
        /// <summary>
        /// Returns information about the feature state.
        /// </summary>
        public record GetFeatureStateRequestResult(
            bool FeatureEnabled
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns information about all running processes.
        /// </summary>
        public static SystemInfo.GetProcessInfoRequest GetProcessInfo()
        {
            return new SystemInfo.GetProcessInfoRequest();
        }
        /// <summary>
        /// Returns information about all running processes.
        /// </summary>
        [Core.MethodName("SystemInfo.getProcessInfo")]
        public record GetProcessInfoRequest() : Core.ICommand<GetProcessInfoRequestResult>
        {
        }
        /// <summary>
        /// Returns information about all running processes.
        /// </summary>
        /// <param name="ProcessInfo">An array of process info blocks.</param>
        public record GetProcessInfoRequestResult(
            IReadOnlyList<SystemInfo.ProcessInfo> ProcessInfo
        ) : Core.IType
        {
        }
    }
}
