// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class Target
    {
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record TargetID(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <summary>
        /// Unique identifier of attached debugging session.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record SessionID(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
        }
        /// <param name="Type">List of types: https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_agent_host_impl.cc?ss=chromium&amp;q=f:devtools%20-f:out%20%22::kTypeTab%5B%5D%22</param>
        /// <param name="Attached">Whether the target has an attached client.</param>
        /// <param name="CanAccessOpener">Whether the target has access to the originating window.</param>
        /// <param name="OpenerId">Opener target Id</param>
        /// <param name="OpenerFrameId">Frame id of originating window (is only set if target has an opener).</param>
        /// <param name="ParentFrameId">Id of the parent frame, only present for the &quot;iframe&quot; targets.</param>
        /// <param name="Subtype">Provides additional details for specific target types. For example, for<br/>
        /// the type of &quot;page&quot;, this may be set to &quot;prerender&quot;.</param>
        public record TargetInfo(
            Target.TargetID TargetId,
            string Type,
            string Title,
            string Url,
            bool Attached,
            bool CanAccessOpener,
            Target.TargetID? OpenerId = default,
            Page.FrameId? OpenerFrameId = default,
            Page.FrameId? ParentFrameId = default,
            Browser.BrowserContextID? BrowserContextId = default,
            string? Subtype = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// A filter used by target query/discovery/auto-attach operations.
        /// </summary>
        /// <param name="Exclude">If set, causes exclusion of matching targets from the list.</param>
        /// <param name="Type">If not present, matches any type.</param>
        public record FilterEntry(
            bool? Exclude = default,
            string? Type = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// The entries in TargetFilter are matched sequentially against targets and<br/>
        /// the first entry that matches determines if the target is included or not,<br/>
        /// depending on the value of `exclude` field in the entry.<br/>
        /// If filter is not specified, the one assumed is<br/>
        /// [{type: &quot;browser&quot;, exclude: true}, {type: &quot;tab&quot;, exclude: true}, {}]<br/>
        /// (i.e. include everything but `browser` and `tab`).
        /// </summary>
        [JsonConverter(typeof(Core.ArrayTypeConverter))]
        public record TargetFilter(
            IReadOnlyList<Target.FilterEntry> Items
        ) : Core.ArrayType<Target.FilterEntry>(Items)
        {
        }
        public record RemoteLocation(
            string Host,
            int Port
        ) : Core.IType
        {
        }
        /// <summary>
        /// The state of the target window.
        /// </summary>
        [JsonConverter(typeof(Core.PrimitiveTypeConverter))]
        public record WindowState(
            string Value
        ) : Core.PrimitiveType<string>(Value)
        {
            public static readonly WindowState NORMAL = new("normal");
            public static readonly WindowState MINIMIZED = new("minimized");
            public static readonly WindowState MAXIMIZED = new("maximized");
            public static readonly WindowState FULLSCREEN = new("fullscreen");
        }
        /// <summary>
        /// Activates (focuses) the target.
        /// </summary>
        public static Target.ActivateTargetRequest ActivateTarget(Target.TargetID TargetId)
        {
            return new Target.ActivateTargetRequest(TargetId);
        }
        /// <summary>
        /// Activates (focuses) the target.
        /// </summary>
        [Core.MethodName("Target.activateTarget")]
        public record ActivateTargetRequest(
            Target.TargetID TargetId
        ) : Core.ICommand<ActivateTargetRequestResult>
        {
        }
        /// <summary>
        /// Activates (focuses) the target.
        /// </summary>
        public record ActivateTargetRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Attaches to the target with given id.
        /// </summary>
        /// <param name="Flatten">Enables &quot;flat&quot; access to the session via specifying sessionId attribute in the commands.<br/>
        /// We plan to make this the default, deprecate non-flattened mode,<br/>
        /// and eventually retire it. See crbug.com/991325.</param>
        public static Target.AttachToTargetRequest AttachToTarget(Target.TargetID TargetId, bool? Flatten = default)
        {
            return new Target.AttachToTargetRequest(TargetId, Flatten);
        }
        /// <summary>
        /// Attaches to the target with given id.
        /// </summary>
        /// <param name="Flatten">Enables &quot;flat&quot; access to the session via specifying sessionId attribute in the commands.<br/>
        /// We plan to make this the default, deprecate non-flattened mode,<br/>
        /// and eventually retire it. See crbug.com/991325.</param>
        [Core.MethodName("Target.attachToTarget")]
        public record AttachToTargetRequest(
            Target.TargetID TargetId,
            bool? Flatten = default
        ) : Core.ICommand<AttachToTargetRequestResult>
        {
        }
        /// <summary>
        /// Attaches to the target with given id.
        /// </summary>
        /// <param name="SessionId">Id assigned to the session.</param>
        public record AttachToTargetRequestResult(
            Target.SessionID SessionId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Attaches to the browser target, only uses flat sessionId mode.
        /// </summary>
        public static Target.AttachToBrowserTargetRequest AttachToBrowserTarget()
        {
            return new Target.AttachToBrowserTargetRequest();
        }
        /// <summary>
        /// Attaches to the browser target, only uses flat sessionId mode.
        /// </summary>
        [Core.MethodName("Target.attachToBrowserTarget")]
        public record AttachToBrowserTargetRequest() : Core.ICommand<AttachToBrowserTargetRequestResult>
        {
        }
        /// <summary>
        /// Attaches to the browser target, only uses flat sessionId mode.
        /// </summary>
        /// <param name="SessionId">Id assigned to the session.</param>
        public record AttachToBrowserTargetRequestResult(
            Target.SessionID SessionId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Closes the target. If the target is a page that gets closed too.
        /// </summary>
        public static Target.CloseTargetRequest CloseTarget(Target.TargetID TargetId)
        {
            return new Target.CloseTargetRequest(TargetId);
        }
        /// <summary>
        /// Closes the target. If the target is a page that gets closed too.
        /// </summary>
        [Core.MethodName("Target.closeTarget")]
        public record CloseTargetRequest(
            Target.TargetID TargetId
        ) : Core.ICommand<CloseTargetRequestResult>
        {
        }
        /// <summary>
        /// Closes the target. If the target is a page that gets closed too.
        /// </summary>
        /// <param name="Success">Always set to true. If an error occurs, the response indicates protocol error.</param>
        public record CloseTargetRequestResult(
            bool Success
        ) : Core.IType
        {
        }
        /// <summary>
        /// Inject object to the target&apos;s main frame that provides a communication<br/>
        /// channel with browser target.<br/>
        /// <br/>
        /// Injected object will be available as `window[bindingName]`.<br/>
        /// <br/>
        /// The object has the following API:<br/>
        /// - `binding.send(json)` - a method to send messages over the remote debugging protocol<br/>
        /// - `binding.onmessage = json =&gt; handleMessage(json)` - a callback that will be called for the protocol notifications and command responses.
        /// </summary>
        /// <param name="BindingName">Binding name, &apos;cdp&apos; if not specified.</param>
        /// <param name="InheritPermissions">If true, inherits the current root session&apos;s permissions (default: false).</param>
        public static Target.ExposeDevToolsProtocolRequest ExposeDevToolsProtocol(Target.TargetID TargetId, string? BindingName = default, bool? InheritPermissions = default)
        {
            return new Target.ExposeDevToolsProtocolRequest(TargetId, BindingName, InheritPermissions);
        }
        /// <summary>
        /// Inject object to the target&apos;s main frame that provides a communication<br/>
        /// channel with browser target.<br/>
        /// <br/>
        /// Injected object will be available as `window[bindingName]`.<br/>
        /// <br/>
        /// The object has the following API:<br/>
        /// - `binding.send(json)` - a method to send messages over the remote debugging protocol<br/>
        /// - `binding.onmessage = json =&gt; handleMessage(json)` - a callback that will be called for the protocol notifications and command responses.
        /// </summary>
        /// <param name="BindingName">Binding name, &apos;cdp&apos; if not specified.</param>
        /// <param name="InheritPermissions">If true, inherits the current root session&apos;s permissions (default: false).</param>
        [Core.MethodName("Target.exposeDevToolsProtocol")]
        public record ExposeDevToolsProtocolRequest(
            Target.TargetID TargetId,
            string? BindingName = default,
            bool? InheritPermissions = default
        ) : Core.ICommand<ExposeDevToolsProtocolRequestResult>
        {
        }
        /// <summary>
        /// Inject object to the target&apos;s main frame that provides a communication<br/>
        /// channel with browser target.<br/>
        /// <br/>
        /// Injected object will be available as `window[bindingName]`.<br/>
        /// <br/>
        /// The object has the following API:<br/>
        /// - `binding.send(json)` - a method to send messages over the remote debugging protocol<br/>
        /// - `binding.onmessage = json =&gt; handleMessage(json)` - a callback that will be called for the protocol notifications and command responses.
        /// </summary>
        public record ExposeDevToolsProtocolRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than<br/>
        /// one.
        /// </summary>
        /// <param name="DisposeOnDetach">If specified, disposes this context when debugging session disconnects.</param>
        /// <param name="ProxyServer">Proxy server, similar to the one passed to --proxy-server</param>
        /// <param name="ProxyBypassList">Proxy bypass list, similar to the one passed to --proxy-bypass-list</param>
        /// <param name="OriginsWithUniversalNetworkAccess">An optional list of origins to grant unlimited cross-origin access to.<br/>
        /// Parts of the URL other than those constituting origin are ignored.</param>
        public static Target.CreateBrowserContextRequest CreateBrowserContext(bool? DisposeOnDetach = default, string? ProxyServer = default, string? ProxyBypassList = default, IReadOnlyList<string>? OriginsWithUniversalNetworkAccess = default)
        {
            return new Target.CreateBrowserContextRequest(DisposeOnDetach, ProxyServer, ProxyBypassList, OriginsWithUniversalNetworkAccess);
        }
        /// <summary>
        /// Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than<br/>
        /// one.
        /// </summary>
        /// <param name="DisposeOnDetach">If specified, disposes this context when debugging session disconnects.</param>
        /// <param name="ProxyServer">Proxy server, similar to the one passed to --proxy-server</param>
        /// <param name="ProxyBypassList">Proxy bypass list, similar to the one passed to --proxy-bypass-list</param>
        /// <param name="OriginsWithUniversalNetworkAccess">An optional list of origins to grant unlimited cross-origin access to.<br/>
        /// Parts of the URL other than those constituting origin are ignored.</param>
        [Core.MethodName("Target.createBrowserContext")]
        public record CreateBrowserContextRequest(
            bool? DisposeOnDetach = default,
            string? ProxyServer = default,
            string? ProxyBypassList = default,
            IReadOnlyList<string>? OriginsWithUniversalNetworkAccess = default
        ) : Core.ICommand<CreateBrowserContextRequestResult>
        {
        }
        /// <summary>
        /// Creates a new empty BrowserContext. Similar to an incognito profile but you can have more than<br/>
        /// one.
        /// </summary>
        /// <param name="BrowserContextId">The id of the context created.</param>
        public record CreateBrowserContextRequestResult(
            Browser.BrowserContextID BrowserContextId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Returns all browser contexts created with `Target.createBrowserContext` method.
        /// </summary>
        public static Target.GetBrowserContextsRequest GetBrowserContexts()
        {
            return new Target.GetBrowserContextsRequest();
        }
        /// <summary>
        /// Returns all browser contexts created with `Target.createBrowserContext` method.
        /// </summary>
        [Core.MethodName("Target.getBrowserContexts")]
        public record GetBrowserContextsRequest() : Core.ICommand<GetBrowserContextsRequestResult>
        {
        }
        /// <summary>
        /// Returns all browser contexts created with `Target.createBrowserContext` method.
        /// </summary>
        /// <param name="BrowserContextIds">An array of browser context ids.</param>
        /// <param name="DefaultBrowserContextId">The id of the default browser context if available.</param>
        public record GetBrowserContextsRequestResult(
            IReadOnlyList<Browser.BrowserContextID> BrowserContextIds,
            Browser.BrowserContextID? DefaultBrowserContextId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Creates a new page.
        /// </summary>
        /// <param name="Url">The initial URL the page will be navigated to. An empty string indicates about:blank.</param>
        /// <param name="Left">Frame left origin in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="Top">Frame top origin in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="Width">Frame width in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="Height">Frame height in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="WindowState">Frame window state (requires newWindow to be true or headless shell).<br/>
        /// Default is normal.</param>
        /// <param name="BrowserContextId">The browser context to create the page in.</param>
        /// <param name="EnableBeginFrameControl">Whether BeginFrames for this target will be controlled via DevTools (headless shell only,<br/>
        /// not supported on MacOS yet, false by default).</param>
        /// <param name="NewWindow">Whether to create a new Window or Tab (false by default, not supported by headless shell).</param>
        /// <param name="Background">Whether to create the target in background or foreground (false by default, not supported<br/>
        /// by headless shell).</param>
        /// <param name="ForTab">Whether to create the target of type &quot;tab&quot;.</param>
        /// <param name="Hidden">Whether to create a hidden target. The hidden target is observable via protocol, but not<br/>
        /// present in the tab UI strip. Cannot be created with `forTab: true`, `newWindow: true` or<br/>
        /// `background: false`. The life-time of the tab is limited to the life-time of the session.</param>
        /// <param name="Focus">If specified, the option is used to determine if the new target should<br/>
        /// be focused or not. By default, the focus behavior depends on the<br/>
        /// value of the background field. For example, background=false and focus=false<br/>
        /// will result in the target tab being opened but the browser window remain<br/>
        /// unchanged (if it was in the background, it will remain in the background)<br/>
        /// and background=false with focus=undefined will result in the window being focused.<br/>
        /// Using background: true and focus: true is not supported and will result in an error.</param>
        public static Target.CreateTargetRequest CreateTarget(string Url, int? Left = default, int? Top = default, int? Width = default, int? Height = default, Target.WindowState? WindowState = default, Browser.BrowserContextID? BrowserContextId = default, bool? EnableBeginFrameControl = default, bool? NewWindow = default, bool? Background = default, bool? ForTab = default, bool? Hidden = default, bool? Focus = default)
        {
            return new Target.CreateTargetRequest(Url, Left, Top, Width, Height, WindowState, BrowserContextId, EnableBeginFrameControl, NewWindow, Background, ForTab, Hidden, Focus);
        }
        /// <summary>
        /// Creates a new page.
        /// </summary>
        /// <param name="Url">The initial URL the page will be navigated to. An empty string indicates about:blank.</param>
        /// <param name="Left">Frame left origin in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="Top">Frame top origin in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="Width">Frame width in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="Height">Frame height in DIP (requires newWindow to be true or headless shell).</param>
        /// <param name="WindowState">Frame window state (requires newWindow to be true or headless shell).<br/>
        /// Default is normal.</param>
        /// <param name="BrowserContextId">The browser context to create the page in.</param>
        /// <param name="EnableBeginFrameControl">Whether BeginFrames for this target will be controlled via DevTools (headless shell only,<br/>
        /// not supported on MacOS yet, false by default).</param>
        /// <param name="NewWindow">Whether to create a new Window or Tab (false by default, not supported by headless shell).</param>
        /// <param name="Background">Whether to create the target in background or foreground (false by default, not supported<br/>
        /// by headless shell).</param>
        /// <param name="ForTab">Whether to create the target of type &quot;tab&quot;.</param>
        /// <param name="Hidden">Whether to create a hidden target. The hidden target is observable via protocol, but not<br/>
        /// present in the tab UI strip. Cannot be created with `forTab: true`, `newWindow: true` or<br/>
        /// `background: false`. The life-time of the tab is limited to the life-time of the session.</param>
        /// <param name="Focus">If specified, the option is used to determine if the new target should<br/>
        /// be focused or not. By default, the focus behavior depends on the<br/>
        /// value of the background field. For example, background=false and focus=false<br/>
        /// will result in the target tab being opened but the browser window remain<br/>
        /// unchanged (if it was in the background, it will remain in the background)<br/>
        /// and background=false with focus=undefined will result in the window being focused.<br/>
        /// Using background: true and focus: true is not supported and will result in an error.</param>
        [Core.MethodName("Target.createTarget")]
        public record CreateTargetRequest(
            string Url,
            int? Left = default,
            int? Top = default,
            int? Width = default,
            int? Height = default,
            Target.WindowState? WindowState = default,
            Browser.BrowserContextID? BrowserContextId = default,
            bool? EnableBeginFrameControl = default,
            bool? NewWindow = default,
            bool? Background = default,
            bool? ForTab = default,
            bool? Hidden = default,
            bool? Focus = default
        ) : Core.ICommand<CreateTargetRequestResult>
        {
        }
        /// <summary>
        /// Creates a new page.
        /// </summary>
        /// <param name="TargetId">The id of the page opened.</param>
        public record CreateTargetRequestResult(
            Target.TargetID TargetId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Detaches session with given id.
        /// </summary>
        /// <param name="SessionId">Session to detach.</param>
        /// <param name="TargetId">Deprecated.</param>
        public static Target.DetachFromTargetRequest DetachFromTarget(Target.SessionID? SessionId = default, Target.TargetID? TargetId = default)
        {
            return new Target.DetachFromTargetRequest(SessionId, TargetId);
        }
        /// <summary>
        /// Detaches session with given id.
        /// </summary>
        /// <param name="SessionId">Session to detach.</param>
        /// <param name="TargetId">Deprecated.</param>
        [Core.MethodName("Target.detachFromTarget")]
        public record DetachFromTargetRequest(
            Target.SessionID? SessionId = default,
            Target.TargetID? TargetId = default
        ) : Core.ICommand<DetachFromTargetRequestResult>
        {
        }
        /// <summary>
        /// Detaches session with given id.
        /// </summary>
        public record DetachFromTargetRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Deletes a BrowserContext. All the belonging pages will be closed without calling their<br/>
        /// beforeunload hooks.
        /// </summary>
        public static Target.DisposeBrowserContextRequest DisposeBrowserContext(Browser.BrowserContextID BrowserContextId)
        {
            return new Target.DisposeBrowserContextRequest(BrowserContextId);
        }
        /// <summary>
        /// Deletes a BrowserContext. All the belonging pages will be closed without calling their<br/>
        /// beforeunload hooks.
        /// </summary>
        [Core.MethodName("Target.disposeBrowserContext")]
        public record DisposeBrowserContextRequest(
            Browser.BrowserContextID BrowserContextId
        ) : Core.ICommand<DisposeBrowserContextRequestResult>
        {
        }
        /// <summary>
        /// Deletes a BrowserContext. All the belonging pages will be closed without calling their<br/>
        /// beforeunload hooks.
        /// </summary>
        public record DisposeBrowserContextRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Returns information about a target.
        /// </summary>
        public static Target.GetTargetInfoRequest GetTargetInfo(Target.TargetID? TargetId = default)
        {
            return new Target.GetTargetInfoRequest(TargetId);
        }
        /// <summary>
        /// Returns information about a target.
        /// </summary>
        [Core.MethodName("Target.getTargetInfo")]
        public record GetTargetInfoRequest(
            Target.TargetID? TargetId = default
        ) : Core.ICommand<GetTargetInfoRequestResult>
        {
        }
        /// <summary>
        /// Returns information about a target.
        /// </summary>
        public record GetTargetInfoRequestResult(
            Target.TargetInfo TargetInfo
        ) : Core.IType
        {
        }
        /// <summary>
        /// Retrieves a list of available targets.
        /// </summary>
        /// <param name="Filter">Only targets matching filter will be reported. If filter is not specified<br/>
        /// and target discovery is currently enabled, a filter used for target discovery<br/>
        /// is used for consistency.</param>
        public static Target.GetTargetsRequest GetTargets(Target.TargetFilter? Filter = default)
        {
            return new Target.GetTargetsRequest(Filter);
        }
        /// <summary>
        /// Retrieves a list of available targets.
        /// </summary>
        /// <param name="Filter">Only targets matching filter will be reported. If filter is not specified<br/>
        /// and target discovery is currently enabled, a filter used for target discovery<br/>
        /// is used for consistency.</param>
        [Core.MethodName("Target.getTargets")]
        public record GetTargetsRequest(
            Target.TargetFilter? Filter = default
        ) : Core.ICommand<GetTargetsRequestResult>
        {
        }
        /// <summary>
        /// Retrieves a list of available targets.
        /// </summary>
        /// <param name="TargetInfos">The list of targets.</param>
        public record GetTargetsRequestResult(
            IReadOnlyList<Target.TargetInfo> TargetInfos
        ) : Core.IType
        {
        }
        /// <summary>
        /// Sends protocol message over session with given id.<br/>
        /// Consider using flat mode instead; see commands attachToTarget, setAutoAttach,<br/>
        /// and crbug.com/991325.
        /// </summary>
        /// <param name="SessionId">Identifier of the session.</param>
        /// <param name="TargetId">Deprecated.</param>
        [Obsolete]
        public static Target.SendMessageToTargetRequest SendMessageToTarget(string Message, Target.SessionID? SessionId = default, Target.TargetID? TargetId = default)
        {
            return new Target.SendMessageToTargetRequest(Message, SessionId, TargetId);
        }
        /// <summary>
        /// Sends protocol message over session with given id.<br/>
        /// Consider using flat mode instead; see commands attachToTarget, setAutoAttach,<br/>
        /// and crbug.com/991325.
        /// </summary>
        /// <param name="SessionId">Identifier of the session.</param>
        /// <param name="TargetId">Deprecated.</param>
        [Obsolete]
        [Core.MethodName("Target.sendMessageToTarget")]
        public record SendMessageToTargetRequest(
            string Message,
            Target.SessionID? SessionId = default,
            Target.TargetID? TargetId = default
        ) : Core.ICommand<SendMessageToTargetRequestResult>
        {
        }
        /// <summary>
        /// Sends protocol message over session with given id.<br/>
        /// Consider using flat mode instead; see commands attachToTarget, setAutoAttach,<br/>
        /// and crbug.com/991325.
        /// </summary>
        [Obsolete]
        public record SendMessageToTargetRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Controls whether to automatically attach to new targets which are considered<br/>
        /// to be directly related to this one (for example, iframes or workers).<br/>
        /// When turned on, attaches to all existing related targets as well. When turned off,<br/>
        /// automatically detaches from all currently attached targets.<br/>
        /// This also clears all targets added by `autoAttachRelated` from the list of targets to watch<br/>
        /// for creation of related targets.<br/>
        /// You might want to call this recursively for auto-attached targets to attach<br/>
        /// to all available targets.
        /// </summary>
        /// <param name="AutoAttach">Whether to auto-attach to related targets.</param>
        /// <param name="WaitForDebuggerOnStart">Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger`<br/>
        /// to run paused targets.</param>
        /// <param name="Flatten">Enables &quot;flat&quot; access to the session via specifying sessionId attribute in the commands.<br/>
        /// We plan to make this the default, deprecate non-flattened mode,<br/>
        /// and eventually retire it. See crbug.com/991325.</param>
        /// <param name="Filter">Only targets matching filter will be attached.</param>
        public static Target.SetAutoAttachRequest SetAutoAttach(bool AutoAttach, bool WaitForDebuggerOnStart, bool? Flatten = default, Target.TargetFilter? Filter = default)
        {
            return new Target.SetAutoAttachRequest(AutoAttach, WaitForDebuggerOnStart, Flatten, Filter);
        }
        /// <summary>
        /// Controls whether to automatically attach to new targets which are considered<br/>
        /// to be directly related to this one (for example, iframes or workers).<br/>
        /// When turned on, attaches to all existing related targets as well. When turned off,<br/>
        /// automatically detaches from all currently attached targets.<br/>
        /// This also clears all targets added by `autoAttachRelated` from the list of targets to watch<br/>
        /// for creation of related targets.<br/>
        /// You might want to call this recursively for auto-attached targets to attach<br/>
        /// to all available targets.
        /// </summary>
        /// <param name="AutoAttach">Whether to auto-attach to related targets.</param>
        /// <param name="WaitForDebuggerOnStart">Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger`<br/>
        /// to run paused targets.</param>
        /// <param name="Flatten">Enables &quot;flat&quot; access to the session via specifying sessionId attribute in the commands.<br/>
        /// We plan to make this the default, deprecate non-flattened mode,<br/>
        /// and eventually retire it. See crbug.com/991325.</param>
        /// <param name="Filter">Only targets matching filter will be attached.</param>
        [Core.MethodName("Target.setAutoAttach")]
        public record SetAutoAttachRequest(
            bool AutoAttach,
            bool WaitForDebuggerOnStart,
            bool? Flatten = default,
            Target.TargetFilter? Filter = default
        ) : Core.ICommand<SetAutoAttachRequestResult>
        {
        }
        /// <summary>
        /// Controls whether to automatically attach to new targets which are considered<br/>
        /// to be directly related to this one (for example, iframes or workers).<br/>
        /// When turned on, attaches to all existing related targets as well. When turned off,<br/>
        /// automatically detaches from all currently attached targets.<br/>
        /// This also clears all targets added by `autoAttachRelated` from the list of targets to watch<br/>
        /// for creation of related targets.<br/>
        /// You might want to call this recursively for auto-attached targets to attach<br/>
        /// to all available targets.
        /// </summary>
        public record SetAutoAttachRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Adds the specified target to the list of targets that will be monitored for any related target<br/>
        /// creation (such as child frames, child workers and new versions of service worker) and reported<br/>
        /// through `attachedToTarget`. The specified target is also auto-attached.<br/>
        /// This cancels the effect of any previous `setAutoAttach` and is also cancelled by subsequent<br/>
        /// `setAutoAttach`. Only available at the Browser target.
        /// </summary>
        /// <param name="WaitForDebuggerOnStart">Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger`<br/>
        /// to run paused targets.</param>
        /// <param name="Filter">Only targets matching filter will be attached.</param>
        public static Target.AutoAttachRelatedRequest AutoAttachRelated(Target.TargetID TargetId, bool WaitForDebuggerOnStart, Target.TargetFilter? Filter = default)
        {
            return new Target.AutoAttachRelatedRequest(TargetId, WaitForDebuggerOnStart, Filter);
        }
        /// <summary>
        /// Adds the specified target to the list of targets that will be monitored for any related target<br/>
        /// creation (such as child frames, child workers and new versions of service worker) and reported<br/>
        /// through `attachedToTarget`. The specified target is also auto-attached.<br/>
        /// This cancels the effect of any previous `setAutoAttach` and is also cancelled by subsequent<br/>
        /// `setAutoAttach`. Only available at the Browser target.
        /// </summary>
        /// <param name="WaitForDebuggerOnStart">Whether to pause new targets when attaching to them. Use `Runtime.runIfWaitingForDebugger`<br/>
        /// to run paused targets.</param>
        /// <param name="Filter">Only targets matching filter will be attached.</param>
        [Core.MethodName("Target.autoAttachRelated")]
        public record AutoAttachRelatedRequest(
            Target.TargetID TargetId,
            bool WaitForDebuggerOnStart,
            Target.TargetFilter? Filter = default
        ) : Core.ICommand<AutoAttachRelatedRequestResult>
        {
        }
        /// <summary>
        /// Adds the specified target to the list of targets that will be monitored for any related target<br/>
        /// creation (such as child frames, child workers and new versions of service worker) and reported<br/>
        /// through `attachedToTarget`. The specified target is also auto-attached.<br/>
        /// This cancels the effect of any previous `setAutoAttach` and is also cancelled by subsequent<br/>
        /// `setAutoAttach`. Only available at the Browser target.
        /// </summary>
        public record AutoAttachRelatedRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Controls whether to discover available targets and notify via<br/>
        /// `targetCreated/targetInfoChanged/targetDestroyed` events.
        /// </summary>
        /// <param name="Discover">Whether to discover available targets.</param>
        /// <param name="Filter">Only targets matching filter will be attached. If `discover` is false,<br/>
        /// `filter` must be omitted or empty.</param>
        public static Target.SetDiscoverTargetsRequest SetDiscoverTargets(bool Discover, Target.TargetFilter? Filter = default)
        {
            return new Target.SetDiscoverTargetsRequest(Discover, Filter);
        }
        /// <summary>
        /// Controls whether to discover available targets and notify via<br/>
        /// `targetCreated/targetInfoChanged/targetDestroyed` events.
        /// </summary>
        /// <param name="Discover">Whether to discover available targets.</param>
        /// <param name="Filter">Only targets matching filter will be attached. If `discover` is false,<br/>
        /// `filter` must be omitted or empty.</param>
        [Core.MethodName("Target.setDiscoverTargets")]
        public record SetDiscoverTargetsRequest(
            bool Discover,
            Target.TargetFilter? Filter = default
        ) : Core.ICommand<SetDiscoverTargetsRequestResult>
        {
        }
        /// <summary>
        /// Controls whether to discover available targets and notify via<br/>
        /// `targetCreated/targetInfoChanged/targetDestroyed` events.
        /// </summary>
        public record SetDiscoverTargetsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Enables target discovery for the specified locations, when `setDiscoverTargets` was set to<br/>
        /// `true`.
        /// </summary>
        /// <param name="Locations">List of remote locations.</param>
        public static Target.SetRemoteLocationsRequest SetRemoteLocations(IReadOnlyList<Target.RemoteLocation> Locations)
        {
            return new Target.SetRemoteLocationsRequest(Locations);
        }
        /// <summary>
        /// Enables target discovery for the specified locations, when `setDiscoverTargets` was set to<br/>
        /// `true`.
        /// </summary>
        /// <param name="Locations">List of remote locations.</param>
        [Core.MethodName("Target.setRemoteLocations")]
        public record SetRemoteLocationsRequest(
            IReadOnlyList<Target.RemoteLocation> Locations
        ) : Core.ICommand<SetRemoteLocationsRequestResult>
        {
        }
        /// <summary>
        /// Enables target discovery for the specified locations, when `setDiscoverTargets` was set to<br/>
        /// `true`.
        /// </summary>
        public record SetRemoteLocationsRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Gets the targetId of the DevTools page target opened for the given target<br/>
        /// (if any).
        /// </summary>
        /// <param name="TargetId">Page or tab target ID.</param>
        public static Target.GetDevToolsTargetRequest GetDevToolsTarget(Target.TargetID TargetId)
        {
            return new Target.GetDevToolsTargetRequest(TargetId);
        }
        /// <summary>
        /// Gets the targetId of the DevTools page target opened for the given target<br/>
        /// (if any).
        /// </summary>
        /// <param name="TargetId">Page or tab target ID.</param>
        [Core.MethodName("Target.getDevToolsTarget")]
        public record GetDevToolsTargetRequest(
            Target.TargetID TargetId
        ) : Core.ICommand<GetDevToolsTargetRequestResult>
        {
        }
        /// <summary>
        /// Gets the targetId of the DevTools page target opened for the given target<br/>
        /// (if any).
        /// </summary>
        /// <param name="TargetId">The targetId of DevTools page target if exists.</param>
        public record GetDevToolsTargetRequestResult(
            Target.TargetID? TargetId = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Opens a DevTools window for the target.
        /// </summary>
        /// <param name="TargetId">This can be the page or tab target ID.</param>
        /// <param name="PanelId">The id of the panel we want DevTools to open initially. Currently<br/>
        /// supported panels are elements, console, network, sources, resources<br/>
        /// and performance.</param>
        public static Target.OpenDevToolsRequest OpenDevTools(Target.TargetID TargetId, string? PanelId = default)
        {
            return new Target.OpenDevToolsRequest(TargetId, PanelId);
        }
        /// <summary>
        /// Opens a DevTools window for the target.
        /// </summary>
        /// <param name="TargetId">This can be the page or tab target ID.</param>
        /// <param name="PanelId">The id of the panel we want DevTools to open initially. Currently<br/>
        /// supported panels are elements, console, network, sources, resources<br/>
        /// and performance.</param>
        [Core.MethodName("Target.openDevTools")]
        public record OpenDevToolsRequest(
            Target.TargetID TargetId,
            string? PanelId = default
        ) : Core.ICommand<OpenDevToolsRequestResult>
        {
        }
        /// <summary>
        /// Opens a DevTools window for the target.
        /// </summary>
        /// <param name="TargetId">The targetId of DevTools page target.</param>
        public record OpenDevToolsRequestResult(
            Target.TargetID TargetId
        ) : Core.IType
        {
        }
        /// <summary>
        /// Issued when attached to target because of auto-attach or `attachToTarget` command.
        /// </summary>
        /// <param name="SessionId">Identifier assigned to the session used to send/receive messages.</param>
        [Core.MethodName("Target.attachedToTarget")]
        public record AttachedToTarget(
            Target.SessionID SessionId,
            Target.TargetInfo TargetInfo,
            bool WaitingForDebugger
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when detached from target for any reason (including `detachFromTarget` command). Can be<br/>
        /// issued multiple times per target if multiple sessions have been attached to it.
        /// </summary>
        /// <param name="SessionId">Detached session identifier.</param>
        /// <param name="TargetId">Deprecated.</param>
        [Core.MethodName("Target.detachedFromTarget")]
        public record DetachedFromTarget(
            Target.SessionID SessionId,
            Target.TargetID? TargetId = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Notifies about a new protocol message received from the session (as reported in<br/>
        /// `attachedToTarget` event).
        /// </summary>
        /// <param name="SessionId">Identifier of a session which sends a message.</param>
        /// <param name="TargetId">Deprecated.</param>
        [Core.MethodName("Target.receivedMessageFromTarget")]
        public record ReceivedMessageFromTarget(
            Target.SessionID SessionId,
            string Message,
            Target.TargetID? TargetId = default
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when a possible inspection target is created.
        /// </summary>
        [Core.MethodName("Target.targetCreated")]
        public record TargetCreated(
            Target.TargetInfo TargetInfo
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when a target is destroyed.
        /// </summary>
        [Core.MethodName("Target.targetDestroyed")]
        public record TargetDestroyed(
            Target.TargetID TargetId
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when a target has crashed.
        /// </summary>
        /// <param name="Status">Termination status type.</param>
        /// <param name="ErrorCode">Termination error code.</param>
        [Core.MethodName("Target.targetCrashed")]
        public record TargetCrashed(
            Target.TargetID TargetId,
            string Status,
            int ErrorCode
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Issued when some information about a target has changed. This only happens between<br/>
        /// `targetCreated` and `targetDestroyed`.
        /// </summary>
        [Core.MethodName("Target.targetInfoChanged")]
        public record TargetInfoChanged(
            Target.TargetInfo TargetInfo
        ) : Core.IEvent
        {
        }
    }
}
