// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Nodes;

namespace NoDriver.Cdp
{
    public static partial class WebMCP
    {
        /// <summary>
        /// Tool annotations
        /// </summary>
        /// <param name="ReadOnly">A hint indicating that the tool does not modify any state.</param>
        /// <param name="Autosubmit">If the declarative tool was declared with the autosubmit attribute.</param>
        public record Annotation(
            bool? ReadOnly = default,
            bool? Autosubmit = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Definition of a tool that can be invoked.
        /// </summary>
        /// <param name="Name">Tool name.</param>
        /// <param name="Description">Tool description.</param>
        /// <param name="FrameId">Frame identifier associated with the tool registration.</param>
        /// <param name="InputSchema">Schema for the tool&apos;s input parameters.</param>
        /// <param name="Annotations">Optional annotations for the tool.</param>
        /// <param name="BackendNodeId">Optional node ID for declarative tools.</param>
        /// <param name="StackTrace">The stack trace at the time of the registration.</param>
        public record Tool(
            string Name,
            string Description,
            Page.FrameId FrameId,
            JsonObject? InputSchema = default,
            WebMCP.Annotation? Annotations = default,
            DOM.BackendNodeId? BackendNodeId = default,
            Runtime.StackTrace? StackTrace = default
        ) : Core.IType
        {
        }
        /// <summary>
        /// Enables the WebMCP domain, allowing events to be sent. Enabling the domain will trigger a toolsAdded event for<br/>
        /// all currently registered tools.
        /// </summary>
        public static WebMCP.EnableRequest Enable()
        {
            return new WebMCP.EnableRequest();
        }
        /// <summary>
        /// Enables the WebMCP domain, allowing events to be sent. Enabling the domain will trigger a toolsAdded event for<br/>
        /// all currently registered tools.
        /// </summary>
        [Core.MethodName("WebMCP.enable")]
        public record EnableRequest() : Core.ICommand<EnableRequestResult>
        {
        }
        /// <summary>
        /// Enables the WebMCP domain, allowing events to be sent. Enabling the domain will trigger a toolsAdded event for<br/>
        /// all currently registered tools.
        /// </summary>
        public record EnableRequestResult() : Core.IType
        {
        }
        /// <summary>
        /// Event fired when new tools are added.
        /// </summary>
        /// <param name="Tools">Array of tools that were added.</param>
        [Core.MethodName("WebMCP.toolsAdded")]
        public record ToolsAdded(
            IReadOnlyList<WebMCP.Tool> Tools
        ) : Core.IEvent
        {
        }
        /// <summary>
        /// Event fired when tools are removed.
        /// </summary>
        /// <param name="Tools">Array of tools that were removed.</param>
        [Core.MethodName("WebMCP.toolsRemoved")]
        public record ToolsRemoved(
            IReadOnlyList<WebMCP.Tool> Tools
        ) : Core.IEvent
        {
        }
    }
}
